### ISSUE TITLE
Add a release changelog

### ISSUE THREAD

**Issue by joewalnes** [joewalnes/websocketd#105]
Now that there are many more users, there should be a changes.txt (or .md) included with releases.

**Comment by asergeyev** [comment]
I propose simple file that would list things we put to release info. Detailed changelog is usually overkill and hard to read....

**Comment by joewalnes** [comment]
Yep, just a high level overview is fine.

**Comment by asergeyev** [comment]
(see CHANGES file in any of distributions or repository root dir)

**Comment by daledude** [comment]
Not updated for 0.2.11?

**Comment by asergeyev** [comment]
Sorry, yeah, adding now...

**Comment by asergeyev** [comment]
@joewalnes should I quietly re-release 2.11? (or make 2.11p1 of some sort or just keep one we got)

**Comment by joewalnes** [comment]
Just go to 2.12.
