### ISSUE TITLE
Experimental websocketd binaries (OpenBSD, Solaris)

### ISSUE THREAD

**Issue by joewalnes** [joewalnes/websocketd#107]
Blame this: https://twitter.com/joewalnes/status/567497770156957696

Should be straight forwards go can output openbsd binaries.

@asergeyev: Update release/Makefile. GOOS settings here https://golang.org/doc/install/source#environment

@joewalnes: Update website. Modify OpenBSD logo to fit with page.

@sl4mmy: Hi! Can you help us test?

**Comment by abedra** [comment]
@joewalnes i've got an OpenBSD box if you need additional testers.

**Comment by joewalnes** [comment]
@abedra Sweet

**Comment by joewalnes** [comment]
@asergeyev Oooh, Solaris too. Feeling adventurous. Anyone have a Solaris box we can test on?

I draw the line at Plan9.

**Comment by asergeyev** [comment]
:) one of those days I'll try go and websocketd on Solaris...

Added 2.10 binaries and unsigned CHECKSUMS.experimental file to release.

Anyone could report that those work? :)

**Comment by asergeyev** [comment]
One of those days we should probably cut number of os-arch combinations (e.g. trimming heavier on i386 ones)

**Comment by asergeyev** [comment]
Well to make it easy to try:
* https://github.com/joewalnes/websocketd/releases/download/v0.2.10/websocketd-0.2.10-openbsd_386.zip
* https://github.com/joewalnes/websocketd/releases/download/v0.2.10/websocketd-0.2.10-openbsd_amd64.zip
* https://github.com/joewalnes/websocketd/releases/download/v0.2.10/websocketd-0.2.10-solaris_amd64.zip

**Comment by sl4mmy** [comment]
Trying to build this on OpenBSD amd64-current.  Why is go embedded?  Setting GOPATH=/path/to/websocketd/go-workspace:/usr/local/go and GOROOT=/usr/local/bin appears to work with go v1.4.1 installed from packages.

I'll create a port for this, but the ports tree is currently locked for imports.  I'll try and get it imported as soon as the tree is unlocked.

**Comment by asergeyev** [comment]
Did you have luck with binaries I published above (those were compiled on Linux with go cross compiler)? I don't see a problem with port but since websocketd code is likely to be updated every few months I wonder if anyone would be able to maintain that port... 

Otherwise it's going to be stuck at given version and that would not be good for anyone.

**Comment by sl4mmy** [comment]
Yeah, I only have an amd64 box handy so I couldn't test your i386 binary, but the amd64 binary you posted above worked, too.

I'm happy to maintain the port.  I don't foresee it taking too much work to track your releases.  The initial port was really simple, and I spoke with @joewalnes about some things we can try on the ports' side to make it even easier to track.

**Comment by asergeyev** [comment]
Neat. BTW... any thoughts about Freebsd port too since they would be pretty much similar?

**Comment by sl4mmy** [comment]
I'm not a FreeBSD user and am not familiar with their ports infrastructure, sorry.

**Comment by asergeyev** [comment]
not sure if this one should stay open or not.

**Comment by joewalnes** [comment]
The binaries are good. I've still got to make changes to the website, so we'll leave the issue open.

**Comment by joewalnes** [comment]
Did some icons. Pushed to website.

![2015-02-19 at 10 01 am](https://cloud.githubusercontent.com/assets/48950/6270280/60f7291c-b81e-11e4-97e6-e9548137db34.png)

**Comment by sl4mmy** [comment]
The OpenBSD port was just imported http://marc.info/?l=openbsd-ports-cvs&m=142781635923233&w=2

**Comment by asergeyev** [comment]
Cool, thanks for help!
