### ISSUE TITLE
C process reading from STDIN not exiting

### ISSUE THREAD

**Issue by mitchi** [joewalnes/websocketd#117]
Hello,

I wanted to have this little utility (JSON to C STRING) work through websockets. 
It works but the process stays alive after the work, since fgets is a blocking function. I don't know golang but can you close the stream ? It works with the command processor and doesn't block, can you do the same with websockets?

```javascript
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

char transformLine(char *oldline, char *newline)
{
	char * oldp = oldline;
	char * newp = newline;
	
	//Check for null ptrs
	if (oldline == NULL || newline == NULL) return -1;

	//Check to see if the line is valid
	*newp++ = '"';
	while (1) 
	{

		if (*oldp == 13 || *oldp == 10 || *oldp == 0) {
			*newp++ = '"';
			*newp++ = '\n'; //comment this line to have single line json
			break;
		}

		if (*oldp == '"') {
			*newp++ = '\\';
			*newp++ = '"';
			oldp++;
			continue;
		}

		*newp++ = *oldp++;
	}
}


int main(void)
{

	//Read string from STDIN
	static char line[500];
	static char buffer[500];
	// Disable output buffering.
    setbuf(stdout, NULL);

	while (fgets(line, 500, stdin) != NULL) {
			memset(buffer,0, 500);
			transformLine(line, buffer);
			printf(buffer);
	}

	return 0;


}
```

**Comment by asergeyev** [comment]
Stream closes when webpage would act on socket, e.g. call "ws.close();"
Your program could detect something sent from websocket and close connection too, that would cause websocketd to report administrative close to websocket in the browser.

**Comment by mitchi** [comment]
Thank you! 
So the solution is either to set a sentinel value, detect it and terminate the c program.
Or  to close the socket from the browser. 
I didn't know I could use this blocking behavior before. It's good to have. I don't think CGI supported this?
I tried the browser socket close, works fine.

**Comment by asergeyev** [comment]
Good, I'll close it then...

Yes, websockets is very different in nature from CGI,  websocketd makes them look similar.
