### ISSUE TITLE
devconsole cannot send messages in Firefox 35.0.1

### ISSUE THREAD

**Issue by nileshtrivedi** [joewalnes/websocketd#121]
devconsole in FF 35.0.1 is able to connect and receive messages but cannot send messages. No error is thrown. Sending messages works fine in Chrome.

**Comment by asergeyev** [comment]
What operating system is it about? Anything shown in browser console (https://developer.mozilla.org/en-US/docs/Tools/Web_Console)?

In past this piece was causing issues, I wonder if something is not matching Enter key code again...
https://github.com/joewalnes/websocketd/blob/master/libwebsocketd/console.go#L172

**Comment by USA24** [comment]
http://witter.com/usasunlight.JPG

**Comment by nileshtrivedi** [comment]
This was on Ubuntu 14.04. Nothing in the browser console.

**Comment by slafs** [comment]
Same here! Firefox on Ubuntu 14.04. Nothing at the dev console.

**Comment by asergeyev** [comment]
So far I checked on 35.0 on Fedora and it worked....  looking for newer one...

**Comment by asergeyev** [comment]
Well.. it works for me in 36.0 now too... I wonder if it's just a fluke of particular version... Can you upgrade Firefox and try to report if it fixes devconsole for it? (make sure you do not forget to connect to ws:// address first clicking ✔ button)

**Comment by slafs** [comment]
Still nothing on FF 36.0 on Ubuntu 14.04. After debugging the JS code it seems like the 'keydown' event object doesn't have ``keyIdentifier`` attribute. Although it has ``key``(``Enter``), ``which`` (13) and ``keyCode`` (13).

**Comment by slafs** [comment]
Ah... Just realized I was using the older version (0.2.9) instead of the latest one (0.2.10). You should update your Wiki page since it links to older versions (https://github.com/joewalnes/websocketd/wiki/Download-and-install).

**Comment by asergeyev** [comment]
Fixed, thanks!
