### ISSUE TITLE
Unbuffering by default? Is it possible?

### ISSUE THREAD

**Issue by asergeyev** [joewalnes/websocketd#122]
So, there is ton of people who complain that examples do not work in the way expected and insert stdout flush where possible. 

While it's valid technique I wonder if we could suggest something in websocketd instead.

There is stdbuf util nowadays which is implemented in [libstdbuf.c  and stdbuf.c](http://git.savannah.gnu.org/gitweb/?p=coreutils.git;a=tree;f=src), and the description of "how it works" could be read in [this article] (http://www.pixelbeat.org/programming/stdio_buffering/).

Idea here would be to check if libstdbuf is present and it yes - LD_PRELOAD it similarly to what stdbuf does. Would work on *nix -derived systems and Windows likely does not need this fix anyway (needs checking if it's line buffered already)

**Comment by joewalnes** [comment]
Interesting idea.

I agree that buffering-by-default is causing a problem for new users. I was thinking we could solve it in a language specific way (e.g. for python, export PYTHONUNBUFFER=1), but your proposal is very interesting.

My immediate thoughts are:
- If this works flawlessly it will be awesome
- If it sorta-works-but-not-always it may do more harm than good as users won't understand it. We'd get the "it works on my machine but not on a server" situation
- Is it possible to get working across many different linux distros?
- What about OSX, FreeBSD, etc?

**Comment by asergeyev** [comment]
Looks like it's recent versions of coreutils only and it would be not easy to find... I need to research this a bit more....  Agree with your points "should work almost for anyone"

**Comment by asergeyev** [comment]
If we go that way, doing things similarly to what libstdbuf does [without messing with borrowing GPL code]... Are we comfortable to have libwebsocketdwrapper.c file and makefile for its compilation, install to /usr/libexec/websocketd/libwebsocketdwrapper.so  that we will use as LD_PRELOAD for all scripts we execute?

**Comment by asergeyev** [comment]
on other hand libexpect is truly universal/multiplatform one....  and "unbuffer" command just works, maybe people should be recommended to use it for third-party scripts that should be working under websocketd and could not be changed to be unbuffered

**Comment by joewalnes** [comment]
I still have concerns that this will introduce a lot of complexity to release/install process. Are there other approaches? What does libexpect's unbuffer actually do?

**Comment by joewalnes** [comment]
Also, why is it that when scripts are called via bash they are never buffered? Is it because they are running in a pty? Can websocketd do the same? I wonder what the side-effects are.

**Comment by asergeyev** [comment]
Yes. But that's the core of the problem, PTY creation is very platform-specific and that's why exp_spawnl is quite complicated. Sources are  http://www.nist.gov/el/msid/expect.cfm 

I still wonder if someone could point me to place where glibc (or whoever it is) performs terminal presence detection and maybe we can trick it.

**Comment by asergeyev** [comment]
isatty() dos it... (system function) On other hand... BSD/Linux have this: http://man7.org/linux/man-pages/man3/forkpty.3.html

BUT, after thinking some looks like it's dream that we don't need to pursue, **generathing thousands of pty is definitely not a good way to run code**.

And, since we could not do this in stdbuf style without replicating stdbuf, we probably should not get into expect/pty also.  I'll end on recommending these two to run programs that could not be fixed as easy as python/perl code:

    websocket [options] stdbuf command
    websocket [options] unbuffer command

We also have --passenv and technically could run some stuff like this:

    env LD_PRELOAD=/usr/libexec/coreutils/libstdbuf.so _STDBUF_O=L websocketd --passenv=LD_PRELOAD,_STDBUF_O ...

but that looks way more complex :)
