### ISSUE TITLE
We probably need some way to know what binary origins are...

### ISSUE THREAD

**Issue by asergeyev** [joewalnes/websocketd#123]
When looking at historic versions we do not have easy way of telling which one was compiled with which Go compiler/runtime/stdlib. Also later we would not know if it was binary we made or was compiled in ports/repository provider, etc...

That makes me think if we should add this info to --version or create special flag to get detailed information about build environment (e.g. new flag  --buildinfo)

**Comment by joewalnes** [comment]
+1

We can find it if needed by going and looking at the release/Makefile for the tag, but still it would be nice to see in --version.

**Comment by asergeyev** [comment]
Well..  Now we have

    $ websocketd --version
    websocketd 0.2.10


My suggestion is to do something like this:

    diff --git a/version.go b/version.go
    index 4769ee7..66a58eb 100644
    --- a/version.go
    +++ b/version.go
    @@ -5,14 +5,17 @@
     
     package main
     
    +import (
    +       "fmt"
    +       "runtime"
    +)
    +
     // This value can be set for releases at build time using:
    -//   go {build|run} -ldflags "-X main.version 1.2.3.4".
    +//   go {build|run} -ldflags "-X main.version 1.2.3 -X main.buildinfo timestamp-@githubuser-    platform".
     // If unset, Version() shall return "DEVBUILD".
    -var version string
    +var version string = "DEVBUILD"
    +var buildinfo string = "--"
     
     func Version() string {
    -       if version == "" {
    -               return "DEVBUILD"
    -       }
    -       return version
    +       return fmt.Sprintf("%s (%s %s-%s) %s", version, runtime.Version(), runtime.GOOS, runtime.GOARCH, buildinfo)
     }


That leads to this (basically this way probably should be in release/Makefile):

    $ go run -ldflags \
                "-X main.version 0.2.11 -X main.buildinfo \"$(date +%s) $(git config user.email)\"" \
                *.go --version
    websocketd 0.2.11 (go1.4.2 linux-amd64) 1425415916 abc@alexsergeyev.com

**Comment by asergeyev** [comment]
Points not covered:
* SHA1 of current git tree (could be useful)
* SHA1 of one dependency we have (golang.org/x/netwebsocket)

**Comment by asergeyev** [comment]
I think we closed that one, it's merged in.
