### ISSUE TITLE
IBM s390 architecture

### ISSUE THREAD

**Issue by daixtr** [joewalnes/websocketd#124]
i tried to follow the steps, i got this:

./go get ./go-workspace/src/github.com/joewalnes/websocketd
./go: line 4: /opt/misc/snakeden/websocketd-master/go-v1.4.linux-386/bin/go: cannot execute binary file
make: *** [websocketd] Error 126

Is there a workaround? Thanks

**Comment by joewalnes** [comment]
Sorry, no workaround. The Go compiler doesn't target s390 architecture.
