### ISSUE TITLE
Strange exit codes

### ISSUE THREAD

**Issue by LinusU** [joewalnes/websocketd#127]
I noticed that running `websocketd --version` exists with the code `2`, when it probably should be `0`. What is the reasoning behind that?

Here is the relevant code: [config.go L137](https://github.com/joewalnes/websocketd/blob/9f9f81e96d59932eaed556bfe7a5202aba14428d/config.go#L137)

**Comment by asergeyev** [comment]
Maybe @joewalnes had reasons to make it different from normal runs, I was not around for that :)

Started here:
https://github.com/joewalnes/websocketd/commit/e34d79f11600601d5f45d6a4952a73f75ab7a48c

**Comment by joewalnes** [comment]
No reason. It's a bug.

**Comment by LinusU** [comment]
Would you accept a pull request that changes it to `0`?

It complicates the Homebrew formula a bit as it is: Homebrew/homebrew#37030

**Comment by joewalnes** [comment]
Yep
