### ISSUE TITLE
"Could not launch process" when executing windows .cmd files

### ISSUE THREAD

**Issue by eparon** [joewalnes/websocketd#129]
i'm trying to use websocketd on windows with the examples provided on this repo and i'm getting an error stating:
Could not launch process .\count.cmd  (fork/exec .\count.cmd: The directory name is invalid.)
Devconsole output:
Sun, 22 Feb 2015 13:50:03 +0200 | ACCESS | session    | url:'http://127.0.0.1:8080/' id:'1424605803830285500' remote:'127.0.0.1' command:'.\count.cmd' origin:'http://127.0.0.1:8080' | CONNECT
Sun, 22 Feb 2015 13:50:03 +0200 | ERROR  | process    | url:'http://127.0.0.1:8080/' id:'1424605803830285500' remote:'127.0.0.1' command:'.\count.cmd' origin:'http://127.0.0.1:8080' | Could not launch process .\count.cmd  (fork/exec .\count.cmd: The directory name is invalid.)
Sun, 22 Feb 2015 13:50:03 +0200 | ACCESS | session    | url:'http://127.0.0.1:8080/' id:'1424605803830285500' remote:'127.0.0.1' command:'.\count.cmd' origin:'http://127.0.0.1:8080' | DISCONNECT

i'm running websocketd.exe, as: 
websocketd.exe --port=8080 --devconsole count.cmd
or by:
websocketd.exe --port=8080 --devconsole 

Example files are located in the same folder as websocketd.exe and at the web console i'm trying to connect to ws://127.0.0.1:8080/count.cmd and I can also run the .cmd files without problems on command line (running count.cmd gives the desired output).

when i'm running websocketd using an .exe file as command argument there are no errors and the process starts without problems.

is there something wrong from my side? are .cmd files still supported as command arguments?

**Comment by asergeyev** [comment]
Which of two count.cmd are you trying to run?  Is it in your current directory? Can you run it just in console?

Generally you should be able to execute count.cmd from your command interpreter in order for websocket to be able to do the same.  I'm curious what is happening... Just need some more answers from you first.

**Comment by eparon** [comment]
hello asergeyev and thanks for your response!

there's only one count.cmd which invokes cscript in order to run count.vbs. i'm trying to run count.cmd (as mentioned at readme file).

i can run count.cmd from my console without problems - everything is running normally from there.
i can also run .vbs files if i give as command to websocketd.exe the statement "cscript.exe /nologo count.vbs" however this produces an output that is not desired, as there is no "@echo off" command before running cscript

**Comment by asergeyev** [comment]
I'll try to get Windows machine to play with....

**Comment by eparon** [comment]
thanks in advance for your time :)

**Comment by asergeyev** [comment]
Requires option "--passenv PATH" for now, see #144 where we will think of addressing it in future version.

**Comment by deniskuang** [comment]
Version 0.2.11 have the same problem!

**Comment by asergeyev** [comment]
I'll be checking it when I'll have chance.

**Comment by GHExplorer** [comment]
Can't get it to work.

There is greeter.cmd and greeter.vbs in both the c:\websocketd folder, and the c:\websocketd\examples folder, just to cover all bases for now.

I've tried various permutations of the commands, and nothing works.

E.g., all of these were tried:
websocketd --port=3010 --dir=examples --passenv %PATH% --devconsole
websocketd --port=3010 --dir=examples --passenv PATH --devconsole
websocketd --port=3010 --passenv PATH --devconsole greeter.cmd
websocketd --port=3010 --dir=examples --devconsole


The first example,
websocketd --port=3010 --dir=examples --passenv %PATH% --devconsole

Right away, it returns this, on the command line

Ambiguous. Provided COMMAND and --dir argument. Please only specify just one.

Usage:

  Export a single executable program a WebSocket server:
    websocketd [options] COMMAND [command args]

  Or, export an entire directory of executables as WebSocket endpoints:
    websocketd [options] --dir=SOMEDIR

  Or, show extended help message using:
    websocketd --help


The second example,

websocketd --port=3010 --dir=examples --passenv PATH --devconsole

Sun, 17 Jan 2016 13:54:45 -0500 | INFO   | server     |  | Serving from directory      : C:\websocketd\examples
Sun, 17 Jan 2016 13:54:45 -0500 | INFO   | server     |  | Starting WebSocket server   : ws://mypc:3010/
Sun, 17 Jan 2016 13:54:45 -0500 | INFO   | server     |  | Developer console enabled   : http://mypc:3010


After putting the address
	http://mypc:3010/greeter.cmd

into the browser, we get the development console, that shows 

	ws://mypc:3010/greeter.cmd

, with a checkbox


, and the command line returns

un, 17 Jan 2016 13:59:27 -0500 | ACCESS | http       | url:'http://mypc:3010/greeter.cmd' | DEVCONSOLE
Sun, 17 Jan 2016 13:59:28 -0500 | ACCESS | http       | url:'http://mypc:3010/favicon.ico' | DEVCONSOLE

When I either click the checkbox, or press <ENTER> on that line,

Sun, 17 Jan 2016 14:00:29 -0500 | ACCESS | session    | url:'http://mypc:3010/greeter.cmd' id:'1453057229710790200' remote:'192.....' command:'C:\websocketd\examples\greeter.cmd' origin:'http://d
cwhatthe:3010' | CONNECT
Sun, 17 Jan 2016 14:00:29 -0500 | ERROR  | process    | url:'http://mypc:3010/greeter.cmd' id:'1453057229710790200' remote:'192.....' command:'C:\websocketd\examples\greeter.cmd' origin:'http://d
cwhatthe:3010' | Could not launch process C:\websocketd\examples\greeter.cmd  (fork/exec C:\websocketd\examples\greeter.cmd: The directory name is invalid.)
Sun, 17 Jan 2016 14:00:29 -0500 | ACCESS | session    | url:'http://mypc:3010/greeter.cmd' id:'1453057229710790200' remote:'192.....' command:'C:\websocketd\examples\greeter.cmd' origin:'http://d
cwhatthe:3010' | DISCONNECT



I've tried all of the above, and other permutations, and nothing works.

**Comment by asergeyev** [comment]
so with the second example do you have C:\websocketd\examples\greeter.cmd ?

**Comment by GHExplorer** [comment]
Yes, it's there.  I'm only having problem with the development console.  Using staticdir, there's no problem running the basic utility.


So e.g., I created a batch file wsecho.bat in the examples folder,
*****
@echo off

Echo this is in the examples folder, DC
Echo what
Echo the
Echo heeeel
Echo is
Echo going
Echo on,
Echo dere?
*****

, and then ran this on the command line:

websocketd --port=3010 --staticdir=examples


Then, with http://mypc:3010 in the address bar,

the browser returns a directory of files in the examples folder.

, and http://mypc:3010/wsecho.bat echoes the batch file stdout, as expected, in the browser.

**Comment by asergeyev** [comment]
So what happens if you do same thing and --dir instead of --staticdir? Does it work with devconsole?

**Comment by GHExplorer** [comment]
These commands

websocketd --port=3010 --dir=examples --devconsole count.cmd
websocketd --port=3010 --dir=examples --passenv PATH --devconsole count.cmd


both produce this:

  Export a single executable program a WebSocket server:
    websocketd [options] COMMAND [command args]

  Or, export an entire directory of executables as WebSocket endpoints:
    websocketd [options] --dir=SOMEDIR

  Or, show extended help message using:
    websocketd --help


, and as mentioned above, none of these work:

websocketd --port=3010 --dir=examples --passenv %PATH% --devconsole
websocketd --port=3010 --dir=examples --passenv PATH --devconsole
websocketd --port=3010 --passenv PATH --devconsole greeter.cmd
websocketd --port=3010 --dir=examples --devconsole

**Comment by asergeyev** [comment]
websocketd --port=3010 --dir=examples --devconsole

assuming that your count.cmd is in examples directory

then connect to ws://localhost:3010/count.cmd in browser's devconsole.

**Comment by GHExplorer** [comment]
Nope.  I already did all this, at the start.

1.  It won't take localhost.  It needs the computer name.

2.  http://mypc:3010/ brings up the console.  But when I type in the command name in the console,

ws://mypc:3010/count.cmd

, it returns the error that I reported in my first post:


Mon, 18 Jan 2016 19:28:26 -0500 | ACCESS | http       | url:'http://mypc:3010/favicon.ico' | DEVCONSOLE
Mon, 18 Jan 2016 19:28:26 -0500 | ERROR  | process    | url:'http://mypc:3010/count.cmd' id:'145...' remote:'192....' command:'C:\websocketd\examples\count.cmd' origin:'http://mypc:3010' | Could not launch process C:\websocketd\examples\count.cmd  (fork/exec C:\websocketd\examples\count.cmd: The directory name is invalid.)
Mon, 18 Jan 2016 19:28:26 -0500 | ACCESS | session    | url:'http://mypc:3010/count.cmd' id:'145...' remote:'192....' command:'C:\websocketd\examples\count.cmd' origin:'http://mypc:3010' | DISCONNECT



Maybe I'm not explaining things clearly.  The devconsole doesn't work right, on my Windows 8.1 PC.  It comes up and looks good, but the command line insists that the directory name is invalid.  I've confirmed that both the directory name, and the count.cmd file, is in the directory.

I'll try it on another PC, and see if the results are different there.

**Comment by asergeyev** [comment]
> I'll try it on another PC, and see if the results are different there.
Any news?

**Comment by jadromiro** [comment]
I am also experiencing the same error "The directory name is invalid." on my two windows machines using Win 10 64bit and websocketd-0.2.11 for 64bit. I tried many combinations of input parameters and tested it directly or through devconsole option and nothing helped - I suspect there is something wrong with filling values to std. variables SCRIPT_NAME, PATH_INFO, PATH_TRANSLATED. Is there any working solution or workaround ? 

[log.txt](https://github.com/joewalnes/websocketd/files/856546/log.txt)

**Comment by asergeyev** [comment]
Could you share your count.bat too?

Also, could you run d:\Software\websocket\count.bat from command line?

**Comment by jadromiro** [comment]
Yes, I can run d:\Software\websocket\count.bat from same cmd line (just had to rename bat to txt for attaching). I also tried to set all permisions on count.bat file, didn't help.
[count.txt](https://github.com/joewalnes/websocketd/files/856668/count.txt)
[log2.txt](https://github.com/joewalnes/websocketd/files/856664/log2.txt)

**Comment by bkrajendra** [comment]
Im trying to run this project made for windows. https://github.com/dab00/ws-console

I'm also getting same error : 

```
"fork/exec G:\websocketd\src\websocketd\console.cmd: The directory name is invalid.)"
```

While i'm able to run it (console.cmd) from command.(tried bat version too)
I've also added  G:\websocketd\src\websocketd containing websocketd.exe to windows path.

also tried adding console.cmd to same folder, but nothing worked.
Even tried using v0.2.8 mention in above repo. but its same error.

The static dir part is working ok and it serves the content of path given.

is it a issue related to path naming in windows and linux?

As in windows path are simply relative or absolute with "\xxx\xx\"
While in linux/cygwin/mingwin its little different as "./" for executing etc.

As ive tried --staticdir=. it serves same dir content, but for serving sub dir content --staticdir=/subdir does not work, it needs to be  --staticdir=./subdir

**Comment by sg552** [comment]
still not work under windows.
doesn't work for my ruby scripts under windows.

```
websocketd --port=3010 --staticdir=. ruby my_script.rb   ( doesn't work) 
```

I searched around, found no solution nor no examples for windows.   will keep an eye on this issue.

**Comment by asergeyev** [comment]
@sg552 ... any chance you can try it with new version? I pre-released 0.3.0 and wonder if things we changed there would help because we don't wipe environment variables in windows anymore to have clean state of websocketd (I believe that was the reason to have multiple problems when running websocketd under windows)

**Comment by asergeyev** [comment]
@bkrajendra I changed cmd files in examples slightly so that they should work from any directory. Could you re-sync and try to run them with/without websocketd?

**Comment by asergeyev** [comment]
I'll close in hopes there would be new comments if it's still a problem.

**Comment by bkrajendra** [comment]
Hi @asergeyev 
today i tested latest release 0.3.0
Everything seems to work very fine now in windows 10 64 bit
This is what i tested:
with vbscript example directory ive run
```
websocketd.exe --port=8080 --devconsole count.cmd
```
connected from browser http://127.0.0.1:8080/
and it run as expected! :)
Also tried:
```
websocketd.exe --port=8080 --devconsole cscript /nologo count.vbs
```
This was real issue earlier, but now this also worked very fine.

This is what i've done:
added G:\websocketd\ folder with websocketd.exe in windows environment path
Now i can run it from anywhere.

**Comment by sg552** [comment]
@asergeyev  I will give a try later and report here if meet any problems. thanks !
