### ISSUE TITLE
Unable to install on Linux

### ISSUE THREAD

**Issue by flik** [joewalnes/websocketd#130]
How can I install this on linux ? I have downloaded linux version

**Comment by slafs** [comment]
just read the ``INSTALL`` file that is in the package you downloaded

**Comment by flik** [comment]
thanks man :)

**Comment by flik** [comment]
@slafs  Where should I put html file ?

**Comment by flik** [comment]
@slafs  by the way, I have find a solution. we can make useable by : sudo mv websocketd /usr/local/bin/websocketd
after move just type 
$ websocketd --help
Now, websocketd command works everywhere :)

**Comment by slafs** [comment]
I guess you should be more elaborate with your questions and what you're trying to do. A general advice ;). 

The ``/usr/local/bin/websocketd`` thing works because you probably have ``/usr/local/bin`` on your ``PATH`` environment variable.

**Comment by flik** [comment]
This path by default set in environment variables under linux.

**Comment by asergeyev** [comment]
Actually if anyone wants to contribute to INSTALL file, you are welcome. I think it might have some clarity... I'll close issue since there is no major work to expect.
