### ISSUE TITLE
How do you know when a client closes the connection ?

### ISSUE THREAD

**Issue by Botnary** [joewalnes/websocketd#136]
Is there a way from server side to know when a user closes the connection ?

**Comment by joewalnes** [comment]
When the client side closes the connection, websocketd will kill the process that's handling that process. If you need to do additional cleanup you can listen for this signal.

**Comment by Botnary** [comment]
Ok thanks, but for example in my server.php do i receive such signal that the process was killed ?

**Comment by joewalnes** [comment]
To process signals in PHP see:
http://php.net/manual/en/function.pcntl-signal.php

**Comment by Botnary** [comment]
Great! thanks for pointing in the right direction ;)
