### ISSUE TITLE
No docs for the apparent CGI server feature.

### ISSUE THREAD

**Issue by carc1n0gen** [joewalnes/websocketd#138]
The home page mentions a CGI server feature that allows for dynamic content.  I have been unable to find docs on how to do this.  It is either missing or buried somewhere.

**Comment by asergeyev** [comment]
websocketd --help; feature is buried just because it's probably something that should not be in websocketd in future, see #134

**Comment by joewalnes** [comment]
I don't think this a sufficient resolution of the issue.

We should either remove CGI from the features of the homepage or improve discoverability of the CGI docs. Reopening issue until we do one of these.

**Comment by bgailer** [comment]
CGI how-to:

websocketd shell  script:
#!/bin/bash
./websocketd --port=8080 --cgidir=cgi ./c10.py | sed "s/^.*|//" &

Place a program (e.g. cgitest.py) in cgi directory:
#!/usr/bin/python3.4
import cgi
import cgitb
cgitb.enable()
print("Content-Type: text/html")
print()
print("""<! doctype html>
<html>
<head>
<meta http-equiv="cache-control" content="no-cache" />
<meta charset="UTF-8">
</head>
<body>
313
</body>
</html>""")

Invoke:  http://http://199.167.xxx.xxx:8080/cgitest.py

**Comment by asergeyev** [comment]
How about this? https://github.com/joewalnes/websocketd/wiki/Run-a-CGI-script-or-host-static-HTML

**Comment by asergeyev** [comment]
I'll close since I don't expect anything but maybe edits at that page.
