### ISSUE TITLE
Websocketd Capacity

### ISSUE THREAD

**Issue by JesusIslam** [joewalnes/websocketd#139]
Is there any benchmark about how many connections Websocketd could handle, how many msg/s, etc?

**Comment by asergeyev** [comment]
It does depend on application that you're running. Work on writing capacity testing tool and do some profiling is in my todo,  I just don't know when I'll get there.

There is way to do something simple if your script is not requiring much input. You could write curl request that does upgrade to ws:// and reads data. Then you could realistically gnu-parallel it and see what kind of throughput rates you're going to see.

**Comment by joewalnes** [comment]
No, there isn't. I'm going to close this issue as I think it's something more appropriately implemented by an unbiased third party.
