### ISSUE TITLE
DevConsole: if accessed over https://, default URL to wss://

### ISSUE THREAD

**Issue by joewalnes** [joewalnes/websocketd#142]
When accessing the dev console over HTTPS, make sure the default URL starts with wss://

**Comment by asergeyev** [comment]
Can you check it in latest code. I think it was fixed and later moved to TellURL logic... As long as --ssl* options are present... 
 
https://github.com/joewalnes/websocketd/blob/108d82f5ac79a524436667c32a17d35d8d092fc9/libwebsocketd/http.go#L148

Were you using insecure proxying from secure frontend?

**Comment by joewalnes** [comment]
Yeah, this is when running behind a proxy.

Simplest thing to do is determine the ws:// URL on the client side using JavaScript:

    location.href.replace(/^http(s?):\/\//, 'ws$1://')

**Comment by asergeyev** [comment]
Should be fixed.
