### ISSUE TITLE
Incorrect URLs on console when --address not specified

### ISSUE THREAD

**Issue by joewalnes** [joewalnes/websocketd#143]
When starting without `--address`, the console displays:

    | Starting WebSocket server   : ws://:5000/
    | Developer console enabled   : http://:5000/

These are invalid URLs. Simplest thing would be to replace "" with "0.0.0.0"

**Comment by asergeyev** [comment]
Well. Since it's minor it's in master without PR, let me know how it works for you.  On related note I'm not quite sure whether 'popstate' (history back in browser) handler is necessary to have or no.

**Comment by asergeyev** [comment]
Shup that was fix for #142, not this one... amending commit

**Comment by asergeyev** [comment]
back to your topic of this ticket... I think it's good behavior as currently configured. 

--address 0.0.0.0  means "Listen on all IPv4 interfaces"
--address [::] means "Listen on all IPv6 addresses"

and  empty is truly "listen on anything".

**Comment by asergeyev** [comment]
we might get away with saying that default value for address is combination of two but then we need two sockets, while we could get away with one... Not big deal IMO... Could be also causing creation of different env variables anyway...

**Comment by asergeyev** [comment]
for some unknown reason using two 0.0.0.0 and [::] is not possible in the moment.. I wonder if there is go stdlib bug somewhere.

**Comment by asergeyev** [comment]
Needs to be looked again after #57, even if we will have short-term fix here.

**Comment by joewalnes** [comment]
My main goal is the link that is printed out is something that can be understood by a browser (both in URL bar and WebSocket constructor)

**Comment by asergeyev** [comment]
0.0.0.0:port would not open in browser though

**Comment by asergeyev** [comment]
Maybe show it as  "http://hostname:port/ (any {IP|IPv4|IPv6} interface)" would work? (varying thing in parens)

**Comment by joewalnes** [comment]
Interesting...




Typing http://0.0.0.0:port into the browser usually works. Sorta. It's contentious... Technically 0.0.0.0 is non routable, but it happens to work in browsers and many other web frameworks use it.




It turns out the Chrome team recently fixed this because it really shouldn't work. But everyone complained that 0.0.0.0 stopped working so they decided to unfix it again :)

https://code.google.com/p/chromium/issues/detail?id=428046





With this in mind I think using http://0.0.0.0 will be good enough and work in most browsers.

**Comment by asergeyev** [comment]
See if you open dev console then you'll end up with ws://0.0.0.0:xxx/ which would not work. Why you don't like hostname idea?

**Comment by joewalnes** [comment]
Good point about ws://0.0.0.0 not working.

How do you suggest we resolve the hostname?

**Comment by asergeyev** [comment]
I'd just use [os.Hostname()](http://golang.org/pkg/os/#Hostname) for those cases when --address not given and only for that logline, not for actually using that hostname to listen.

**Comment by joewalnes** [comment]
Ok, seems good
