### ISSUE TITLE
Support subprotocol negotiation

### ISSUE THREAD

**Issue by nichtich** [joewalnes/websocketd#147]
The list of subprotocols requested by the client could be passed as environment variable to the script. To pass back the selected subprotocol, the script would have to write it to a pipe or file (its location also passed via ENV). If websocketd does not find this suggested pipe/file it would act as now, so the solution is backwards compatible.

**Comment by asergeyev** [comment]
I think it's overkill... Look at technological history of web-servers in general. You have to have something very special implemented to redirect HTTP 1.0 clients or HTTP 2.0 clients to separate services; you normally support everything you can in one.

Similarly with websocketd... We abstract out from frame exchange protocol and replace it to message-exchange for underlying program(s).  This makes it possible to ignore technical details about protocol itself and just communicate in messages.

In my opinion, if our users would see that we do not support some particular sub-protocol, they should just ask to add it's support. Such support will be implemented in HTTP side of websocketd, leaving Handler side (program runner)  intact.

**Comment by nichtich** [comment]
A less complicated feature would be a `--subprotocol` parameter with a fixed value that clients must include in its list of accepted subprotocols to establish connection. Most services stick to one subprotocol anyway or just assume clients to implicitly know the protocol details.

**Comment by nichtich** [comment]
Having read again RFC6455 I now think that subprotocols are of little use because a server MUST NOT return a subprotocol name unless the subprotocol has explicitly be included in the client request. My use case was to return the subprotocol as additional metadata for clients such as HTTP content type - this is not allowed with websockets.
