### ISSUE TITLE
Origin parsing error invalid URI for request

### ISSUE THREAD

**Issue by ArthurTu** [joewalnes/websocketd#148]
I came across this error when I connect to server with ip address from remote machine.
```
Tue, 05 May 2015 08:40:42 +0000 | ACCESS | session    | url:'http://172.17.0.5:8080/' id:'1430815242569060824' remote:'172.17.42.1' command:'count.sh' | Origin parsing error: parse 172.17.0.5:8080: invalid URI for request
```
server is on `172.17.0.5:8080`. When I connect from localhost, everything works fine.

websocketd version is `0.2.10`.

**Comment by asergeyev** [comment]
Could you please add your OS and browser too? Thanks!

**Comment by asergeyev** [comment]
yeah, even with two IPs like in your example I could not replicate that :( Old browser or somehow differently compiled websocketd is on top of my suspicions so far.

![screenshot from 2015-05-09 00 02 11](https://cloud.githubusercontent.com/assets/715656/7548617/ec29c8de-f5de-11e4-8182-f802f315a361.png)

**Comment by ArthurTu** [comment]
Sorry about the delay.

I encountered previous problem when using websocketd inside [docker](https://www.docker.com/).

This may related to internet settings of docker containers. Exposing the port is not enough (with `--expose`).

To solve this problem, if we want to access websocketd container from host, map the port to host (with `-p`). If access from another container, use `--link` parameters.

**Comment by asergeyev** [comment]
If you have way to record in-container tcpdump or other representation of raw HTTP headers that make it to websocketd's TCP socket, I don't mind to dig further. 

I'm not fully familiar with how docker manages network interfaces, have no idea what could be involved... :(  If it's very critical for you, I'm open to try debug things with your Dockerfile.
