### ISSUE TITLE
Flag for adding custom headers: --header

### ISSUE THREAD

**Issue by asergeyev** [joewalnes/websocketd#151]
as per dicsussion in #150, we might benefit from ability of operator to add custom headers to output websocketd generates. I suggest we add following few that could be used multiple times:
*  --header   (add header on all answers)
*  --header-ws  (add header to ws-upgraded answers)
*  --header-http  (add header to not-upgraded ssl and non-ssl answers, this includes errors and devconsole)

Thoughts?

**Comment by joewalnes** [comment]
+1.

**Comment by asergeyev** [comment]
Should be possible to add headers now.
