### ISSUE TITLE
Not seeing any of the headers in response

### ISSUE THREAD

**Issue by VincentVToscano** [joewalnes/websocketd#155]
Loving websocketd so far. It's quite possible the headers are working, but I'm doing something wrong. I have viewed the response headers and have not found any of the following custom header. Am I entering them correctly?

```websocketd --port=8080 ./count.sh --header="Server:Hello" --header-http="ServerPlain: Demo" --header-ws="HowIs:This" &```

**Comment by asergeyev** [comment]
Are you using 0.2.10? That feature is not in released websocketd yet. You need to compile your own.

**Comment by VincentVToscano** [comment]
Thanks for getting back to me. 

Yes, version = websocketd 0.2.10

I'm running the executable on Ubuntu 14.04

**Comment by asergeyev** [comment]
can you try to compile from github? You'd just need need go (golang package I believe), then you can try to do

    GOPATH=/path/to/some/dir  go get github.com/joewalnes/websocketd

and you should get websocketd in /path/to/some/dir/bin

**Comment by VincentVToscano** [comment]
Heres what I have so far
```
sudo apt-get install build-essential checkinstall git-core
sudo chown $USER /usr/local/src
sudo chmod u+rwx /usr/local/src
sudo apt-get install golang
go version
go version go1.2.1 linux/amd64
mkdir ~/.go
echo "GOPATH=$HOME/.go" >> ~/.bashrc
echo "export GOPATH" >> ~/.bashrc
echo "PATH=\$PATH:\$GOPATH/bin" >> ~/.bashrc
source ~/.bashrc
cd /usr/local/src
go get github.com/joewalnes/websocketd
websocketd --version
websocketd DEVBUILD (go1.2.1 linux-amd64) --
```
So it's now installed. Verified that it's working with the demo. I can see counting 1 -10. I cannot see the response header/s though. Here are the response headers:

Response Headers
-------------------
Connection:Upgrade
Sec-WebSocket-Accept:O/b9/6n0LnW4S7jSgBQmZbmVcfg=
Upgrade:websocket

**Comment by asergeyev** [comment]
Could you give me your command line string again?  If it's what you have above..  you need to move --header* options before command. Otherwise websocketd just uses those args to create command it's going to execute.

**Comment by VincentVToscano** [comment]
That was it, I can see the headers! Thank you.
