### ISSUE TITLE
Not sure - python -i commands works, but not all

### ISSUE THREAD

**Issue by erm3nda** [joewalnes/websocketd#156]
I don't know how to perfectly explain that, because im not english. I'll try me best.

I've successfully tried the websocket creating a bash console using ` websocketd --port=1234 --devconsole bash`. Played it and worked out of the box.

Also, i was able to send python -i command, then go inside python interpreter and testing it with `import os` and `so.system("touch proof.txt")` and worked too, also i can leave with exit() then go back to bash.

But, i can't start the selenim webdriver.Firefox() nor the webdriver.Remote().
Wich log do i have to look for? Thanks.

***Updated: Some output from the shell:***

        Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host     127.0.0.1 on port 7055 after 45000 ms.
    Firefox console output:
        
    (process:13649): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
    Error: no display specified
    
	    at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:120)
	    ... 19 more
    14:50:37.659 WARN - Exception: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
    
    (process:13649): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
    Error: no display specified

**Comment by erm3nda** [comment]
I have make it work using the selenium-server-standalone-2.44.0.jar server with code `webdriver = webdriver.Remote(command_executor='http://127.0.0.1:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)` instead the python's selenium module. I've paste the output of the websocketd here http://pastebin.com/9nRb2RLu.

I don't know why the webdriver.Firefox() didn't run, but the standalone server saves my day.

**Comment by joewalnes** [comment]
Try adding `--passenv DISPLAY` to websocketd command line. It looks like selenium forks FireFox which requires an X environment, which requires the DISPLAY environment variable.

**Comment by erm3nda** [comment]
Did you mean that? `websocketd --port=1234 --devconsole --passenv
DISPLAY=:1 bash`

~~ Self signed ~~


2015-06-21 20:01 GMT+02:00 Joe Walnes <notifications@github.com>:

**Comment by joewalnes** [comment]
Try `websocketd --port=1234--devconsole --passenv=DISPLAY python (whatever)`. The passenv flag will use the value from the parent environment.

**Comment by erm3nda** [comment]
2015-06-21 20:18 GMT+02:00 ErM3nDa <erm3nda@gmail.com>:

> websocketd --port=1234 --devconsole --passenv DISPLAY=:1 bash


What i did now is: *export DISPLAY=:1 && websocketd --port=1234
--devconsole --passenv DISPLAY bash*
and now i can do echo $DISPLAY on the browser and has the value passed, but
still doesn't apply to the firefox instance from webdriver.Firefox().

I tried also to load pytrhon -i directly instead bash, but didn't work.
Also tried to set os.environ["DISPLAY"] = ":1"

Finally, i set the value of $DISPLAY from the .bashrc, so it's loaded every
login.
Didn't work.

~~ Self signed ~~

**Comment by erm3nda** [comment]
My mistake on the command.

I've tried now *websocketd --port=1234 --devconsole --passenv=DISPLAY bash*
and still not work.

From the regular ssh shell is working the webdriver.Firefox().

~~ Self signed ~~


2015-06-21 20:40 GMT+02:00 ErM3nDa <erm3nda@gmail.com>:

>
> 2015-06-21 20:18 GMT+02:00 ErM3nDa <erm3nda@gmail.com>:
>
>> websocketd --port=1234 --devconsole --passenv DISPLAY=:1 bash
>
>
> What i did now is: *export DISPLAY=:1 && websocketd --port=1234
> --devconsole --passenv DISPLAY bash*
> and now i can do echo $DISPLAY on the browser and has the value passed,
> but still doesn't apply to the firefox instance from webdriver.Firefox().
>
> I tried also to load pytrhon -i directly instead bash, but didn't work.
> Also tried to set os.environ["DISPLAY"] = ":1"
>
> Finally, i set the value of $DISPLAY from the .bashrc, so it's loaded
> every login.
> Didn't work.
>
> ~~ Self signed ~~
>
>

**Comment by joewalnes** [comment]
You will probably have more luck posting the error to the Selenium user mailing list and finding out exactly which env variables need to be set. websocketd will hide most vars by default (for security).

**Comment by erm3nda** [comment]
Ok, thank you.
I see on the output something related to PATH, but im really confused.
Is this (https://groups.google.com/forum/#!forum/selenium-users) the user mailing list? 

Best regards.

**Comment by joewalnes** [comment]
Yes, that's the list.

**Comment by asergeyev** [comment]
Closing for now... Feel free to re-open for future comments.
