### ISSUE TITLE
How to do 360 messaging.

### ISSUE THREAD

**Issue by QRMarketing** [joewalnes/websocketd#157]
I see how you count down and send a message. But I don't quite understand how you receive a message process it and the send the response bacK. Say in php.

**Comment by asergeyev** [comment]
I think you start with something like this:

    $inputline = trim(fgets(STDIN));

There is also greeter example:  https://github.com/joewalnes/websocketd/blob/master/examples/php/greeter.php

**Comment by asergeyev** [comment]
I guess we can close this, let me know if there is something that did not work as you're expecting.
