### ISSUE TITLE
WebSocket disconnections not being detected, on RHEL 6.5

### ISSUE THREAD

**Issue by tehsenaus** [joewalnes/websocketd#159]
I'm running the count example (with an increased limit in the loop), with version 0.2.10-linux_amd64 of websocketd:

```
$ ./websocketd --port=8080 --address=127.0.0.1 ./count.sh
Tue, 30 Jun 2015 06:35:42 -0400 | INFO   | server     |  | Serving using application   : ./count.sh
Tue, 30 Jun 2015 06:35:42 -0400 | INFO   | server     |  | Starting WebSocket server   : ws://127.0.0.1:8080/
```

I'm then connecting with wscat (https://www.npmjs.com/package/wscat):
```
$ wscat -c ws://localhost:8080
connected (press CTRL+C to quit)
  < 1
  < 2
```

```
Tue, 30 Jun 2015 06:39:27 -0400 | ACCESS | session    | url:'http://localhost:8080/' id:'1435660767452014352' remote:'localhost' command:'./count.sh' origin:'localhost:8080' | CONNECT
```

But when I disconnect via Ctrl+C in wscat, nothing happens.

Here is the OS info:
```
$ uname -a
Linux vm-6223-8580 2.6.32-431.46.2.el6.x86_64 #1 SMP Mon Dec 15 14:20:02 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

This is working as expected when I use websocketify (https://www.npmjs.com/package/websocketify):
```
$ websocketify --port=8080 --address=127.0.0.1 ./count.sh
websocketify: starting child process: ./count.sh
websocketify: stopping child process
```

**Comment by asergeyev** [comment]
Well.. That's good find, thank you!
I tried to rework that already but it was rolled back with bunch of unstable changes, so it never made it... Now recovered! (will merge in next 10 min)

**Comment by asergeyev** [comment]
Do you have "go" to compile it yourself and run it?

**Comment by tehsenaus** [comment]
Thanks for the quick response - I don't have go though.

**Comment by asergeyev** [comment]
What OS are you using?

**Comment by asergeyev** [comment]
https://github.com/joewalnes/websocketd/releases/tag/untagged-8f9c96aed6ac4a5a39b4 can you see this draft release? Risky enough to try? :)

**Comment by asergeyev** [comment]
@joewalnes since it's big enough update and it's being almost 6 months since last release anyway do you think it's time to put real 0.2.11 release?

**Comment by joewalnes** [comment]
Sounds good

**Comment by asergeyev** [comment]
@tehsenaus closed ticket does not mean you could not post again, feel free to comment, I just think there is nothing to do at this point

**Comment by asergeyev** [comment]
Just got word that link was not working, here is pre-release for 0.2.11
https://github.com/joewalnes/websocketd/releases/tag/v0.2.11
