### ISSUE TITLE
Memory Leak? "Cannot Allocate Memory"

### ISSUE THREAD

**Issue by cubicalmonkey** [joewalnes/websocketd#161]
After running for websocketd for about one or two weeks, I sometimes begin failing to establish connections and logging : "fork/exec ./socket_Script: cannot allocate memory"
Killing the process and restarting makes everything work again.

Running websocketd-0.2.10

             total       used       free     shared    buffers     cached
             Mem:      12332864    3747828    8585036     273404     283624    2636560
             -/+ buffers/cache:     827644   11505220
             Swap:            0          0          0

Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt7-1 (2015-03-01) x86_64 GNU/Linux

**Comment by asergeyev** [comment]
pstree shows any processes it forked and not destroyed?

**Comment by asergeyev** [comment]
if yes it would be same as #159

**Comment by cubicalmonkey** [comment]
Yep, that appears to be my issue. Thanks!
# pstree 
        │               └─websocketd─┬─5*[socket_script]
        │                            └─39*[{websocketd}]

**Comment by asergeyev** [comment]
Try test release if you can.

https://github.com/joewalnes/websocketd/releases/tag/untagged-8f9c96aed6ac4a5a39b4

**Comment by cubicalmonkey** [comment]
Happy to try the test release but your link is giving me a 404.

**Comment by asergeyev** [comment]
OK. I'll pre-release more officially then.

**Comment by asergeyev** [comment]
https://github.com/joewalnes/websocketd/releases/tag/v0.2.11 this then

**Comment by asergeyev** [comment]
@cubicalmonkey could you check please?

**Comment by cubicalmonkey** [comment]
So far so good.

**Comment by asergeyev** [comment]
Ok, keep us posted please.

**Comment by cubicalmonkey** [comment]
Started seeing this randomly in my output logs since moving to v0.2.11.
May be unrelated but figured I’d post it here just in case. 

2015/07/10 07:26:41 http: panic serving x.x.x.x:54066: runtime error: index out of range
goroutine 84827 [running]:
net/http.func·011()
        /u/go/src/github.com/joewalnes/websocketd/release/go-local/1.4.2/go/src/net/http/server.go:1130 +0xbb
github.com/joewalnes/websocketd/libwebsocketd.(*WebsocketdServer).TellURL(0xc20801e640, 0x7547f0, 0x4, 0x0, 0x0, 0xc245cc2284, 0x1, 0x0, 0x0)
        /u/go/src/github.com/joewalnes/websocketd/release/go-path/src/github.com/joewalnes/websocketd/libwebsocketd/http.go:182 +0x248
github.com/joewalnes/websocketd/libwebsocketd.(*WebsocketdServer).ServeHTTP(0xc20801e640, 0x7f35e91ba398, 0xc230e535e0, 0xc269a30f70)
        /u/go/src/github.com/joewalnes/websocketd/release/go-path/src/github.com/joewalnes/websocketd/libwebsocketd/http.go:84 +0x210
net/http.(*ServeMux).ServeHTTP(0xc20803c6f0, 0x7f35e91ba398, 0xc230e535e0, 0xc269a30f70)
        /u/go/src/github.com/joewalnes/websocketd/release/go-local/1.4.2/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc20803a2a0, 0x7f35e91ba398, 0xc230e535e0, 0xc269a30f70)
        /u/go/src/github.com/joewalnes/websocketd/release/go-local/1.4.2/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc230e52dc0)
        /u/go/src/github.com/joewalnes/websocketd/release/go-local/1.4.2/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /u/go/src/github.com/joewalnes/websocketd/release/go-local/1.4.2/go/src/net/http/server.go:1751 +0x35e

**Comment by asergeyev** [comment]
That's a new one, thanks!

**Comment by asergeyev** [comment]
fixed in  #163; since there is really just annoyance from it I'd not create release just yet.
