### ISSUE TITLE
A more clear way to push data to client

### ISSUE THREAD

**Issue by xialvjun** [joewalnes/websocketd#164]
>Everytime a browser connects to that URL, the websocketd server will start a new instance of your process.

That's strange... Why not:

```
client A
var ws = new WebSocket('ws://localhost:8080/A');

ws.onmessage = function(event) {
  console.log('A got message: ' + event.data);
};

client B
var ws = new WebSocket('ws://localhost:8080/B');

ws.onmessage = function(event) {
  console.log('B got message: ' + event.data);
};

server
println("A\t"+"message contentA");
println("B\t"+"message contentB");
```

Then `websocketd --port=8080 server` client A will only log `A got message: A    message contentA`, client B will only log `B got message: B    message contentB`....I think this way is much clear...:)

**Comment by asergeyev** [comment]
It's a bit harder than just "println". Server has to read lines from clients and pass them to program that's running, program that's running has ability to see what client is talking to them using environment variables, lines that come from program go to clients regardless of timeouts... If client disconnects or timesout we need to kill program that was running for it. That's design of websocketd. 


Making support for singleton programs was discussed (aka demultiplexing) in #50, #84, #95, #132; #135; you could comment on the opinions stated there.

**Comment by asergeyev** [comment]
I'll keep it open for a few days in case if I misunderstood you.

**Comment by xialvjun** [comment]
Well, I'm using WebSockets just for pushing data from server to clients.   
For clients pulling data from server, I use ajax...
I know it's not informal, but it's easy to understand.
