### ISSUE TITLE
Port sharing?

### ISSUE THREAD

**Issue by ColorfullyMe** [joewalnes/websocketd#165]
Good day.
First want to say great tool/project, thanks!

Is there any way to use `websocketd` with node.js's express on the same port on some PaaS provider(Openshift)?

`socket.io` works with `express` for instance and binds to same port somehow...

**Comment by asergeyev** [comment]
If you already have port open by one application it's unlikely you could bind it with second one.  But... you can run both websocketd and express on different ports and use some HTTP router (nginx, haproxy, etc) on port that decides which application should answer...

**Comment by ColorfullyMe** [comment]
@asergeyev Thanks! Looks logical to me too. Use some router is the way I should go. I think i was mislead  by this: ![](https://help.openshift.com/hc/en-us/article_attachments/201584904/Web_Socket_and_Http_routing_on_OpenShift.png) found [here](https://help.openshift.com/hc/en-us/articles/203263674-What-external-ports-are-available-on-OpenShift-). 
What do you think: Why do they say > "...bind to port 8080 on the gear IP for both WS and nonWS apps."?
