### ISSUE TITLE
Update release build chain  to support go 1.5 compile/link tools

### ISSUE THREAD

**Issue by asergeyev** [joewalnes/websocketd#168]
Multi-platform compilation is now easier out of the box, we need to change Makefile and related things in /release folder to take advantage of those

**Comment by joewalnes** [comment]
+1

**Comment by asergeyev** [comment]
Implemented following:
* detect os/arch
* load binary go from https://golang.org
* build using GOOS and GOARCH with pre-built multiplatform compiler (no need to rebuild go as we did before)

It's working fine now with go v1.5.1... It definitely would not work on Windows and on ARM though and may need changes for building on everything non-linux.

**Comment by asergeyev** [comment]
Done in #173 btw
