### ISSUE TITLE
basic auth

### ISSUE THREAD

**Issue by jots** [joewalnes/websocketd#172]
would be nice if websocketd supported basicauth like:
--auth=user:password

other than that, super awesome program!

**Comment by asergeyev** [comment]
It might be trickier than that to work... maybe .htpasswd files of some sort and flag to enable it... Maybe it's better to go along middleware idea from #141 or could be just generally in #133 wishlist for folks to support it...

**Comment by asergeyev** [comment]
also if we think "authorization" it instantly adds question if we should support client TLS cert/ca auth

**Comment by asergeyev** [comment]
Since there are alternative solutions (when websocket is behind nginx for example) and there are decent amount of work in order to make users happy I'll close this one... Leaving it for future ideas though...
