### ISSUE TITLE
Compression Support

### ISSUE THREAD

**Issue by randywallace** [joewalnes/websocketd#174]
Is there a way to support the `permessage-deflate` extension?  My browser (latest Chrome) is sending `permessage-deflate` (`Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits`) and `Accept-Encoding: gzip, deflate, sdch` in the request, if that helps.

I'm using websocketd to push logs over the wire to a frontend `tail -f` viewer, and would like to reduce network bandwidth usage if possible.. if I missed something in the documentation and/or source, don't hesitate to tell me I'm and idiot :)

**Comment by asergeyev** [comment]
Sorry, right now it's not yet supported, but we'd need to look into that:

   https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-28

**Comment by asergeyev** [comment]
You can technically get away compressing things yourself and unpacking them using some pure JS implementation but it would be pretty clunky....

**Comment by asergeyev** [comment]
Wow... websocket golib is recommending to use gorilla now....

**Comment by asergeyev** [comment]
Ok... I wonder if it'll work under 0.3.0 after migrating to gorilla.

**Comment by asergeyev** [comment]
Although I'm not sure how it'll work. Ideas?
