### ISSUE TITLE
Support building with Go installed in system

### ISSUE THREAD

**Issue by woky** [joewalnes/websocketd#175]
Hello.

> WebSockets the UNIX way

I'm not sure what your notion of the *UNIX way* is, but mine is certainly not having a separate runtime for every shit downloaded from GitHub. That's the *Apple way* or the *Microsoft way* (or the *Docker way*). Can't you just write in the README something like the following?

> You either need Go 1.5 or you need to build it with `make with_go`

I've managed to build the program with the following:

    sed -i 's;github.com/joewalnes/websocketd/libwebsocketd;./libwebsocketd;' *.go
    go build

but it took me some time to figure out what to change.

**Comment by asergeyev** [comment]
no, that's not quite right... In go way it's just

    go get github.com/joewalnes/websocketd

and then binary should be in your $GOPATH/bin

**Comment by woky** [comment]
Oh. Sorry for the fuss and thanks for the enlightenment.

**Comment by asergeyev** [comment]
No worries, ask away when you need something else. I also like your suggestion about changing something in README...
