### ISSUE TITLE
compared to http2 push ?

### ISSUE THREAD

**Issue by gedw99** [joewalnes/websocketd#177]
i am wondering if this is out of date now that http2 Push is pretty much supported on most modern OS and browsers.

It would be awesome maybe if the websocketd and http2 push could be integrated perhaps.
you get the ease of use of websocketd, and the fallback it offers.

**Comment by asergeyev** [comment]
Server push is for sending resource to a client which wasn't asked yet but could be needed/useful to render a page.

WebSocket is bi-directional channel between client and server.

I really do not see how they would overlap. Surely the space where WebSockets are useful would shrink with HTTP2 but so far there is really no easy alternative. As for support..... I think HTTP/2 is getting there.. Would be some time when clients would universally support it though... 



More info:
* http://stackoverflow.com/questions/28582935/does-http-2-make-websockets-obsolete
* https://github.com/http2/http2-spec/wiki/Implementations
* http://tools.ietf.org/html/draft-hirano-httpbis-websocket-over-http2-01 (slowly dying unfortunately, there is no official RFC I guess)


I don't know yet how those implementations would react to upgrade session request that's standard for HTTP/1.1 Websocket.

**Comment by gedw99** [comment]
support is good:
http://caniuse.com/#feat=http2

ios 9 now support it

**Comment by gedw99** [comment]
Regarding making web sockets redundant, i did some research.
True, "websockets over http2" are not here yet. The framing aspects is where the work is it seems.

The best architecture i could find is:
1. Run a  gRPC server. Easy.
2. In the DMZ, run a gateway server. https://github.com/gengo/grpc-gateway

so you get the bi-diectional streams for all server to server comm and mobile to server
But the gateway is only for traditional Restful Http. The browser basically.

Still curious how to map web sockets to grpc. The gateway might do it but need to read a bit more.
curious what you think.

**Comment by asergeyev** [comment]
this project is about bringing console stdio apps to web using websockets. IMO there is no reason to map anything to other technologies since websockets still would work for HTTP/2 delivered HTMLs.

**Comment by aj664** [comment]
good?  websockets is better...
http://caniuse.com/#search=websocket

**Comment by gedw99** [comment]
@alex

Yes your right. I was just wanting feedback as I said.

Will close
