### ISSUE TITLE
Setting up Websocketd on RPi

### ISSUE THREAD

**Issue by Shrest** [joewalnes/websocketd#178]
Wanted to try websocketd on raspberry pi with Raspbian, I started with this page :https://github.com/joewalnes/websocketd/wiki/Raspberry-pi
I could complete the first step(Pre-requisites). However, unable to go beyond that. Let me explain.
I downloaded go1.2.2.linux-arm-arm-multiarch-armv6-1.tar.gz from Dave's website to a pen drive & tried 

$ cd /media/pendrive
$ tar -C /home/pi -xzf go1.2.2.linux-arm-arm-multiarch-armv6-1.tar.gz

I get the following 
"tar(child) : go1.2.2.linux-arm-arm-multiarch-armv6-1.tar.gz : cannot open :No such file or directory
 tar(child) : Error is not recoverable :exiting now
 tar  : child returned status 2
tar: Error is not recoverable :exiting now"

Then, I wanted to try downloading the file directly to RPi, so tried the following:

$tar - C /home/pi -xzf http://dave.cheney.net/paste/go1.2.2.linux-arm-arm-multiarch-armv6-1.tar.gz

which yield the following result:
"tar(child) : cannot connect to http:resolve failed
 gzip :stdin : unexpected end of file
tar : child returned status 128
tar: Error is not recoverable:exiting now"

RPi is connected to internet and it is working.

Im not sure what is the missing part here. Request advise. Thank you.

Note : Tried using version 1.2.2 since 1.2 as listed on the page was not available on Dave's website.

**Comment by asergeyev** [comment]
Why not just download ARM compiled websocketd and try it?

http://github.com/joewalnes/websocketd/releases/download/v0.2.11/websocketd-0.2.11-linux_arm.zip

But I'm not sure if that would work if there is some issues with DNS name resolution...

Try something along these lines:

    $ sudo apt-get install unzip
    $ wget http://github.com/joewalnes/websocketd/releases/download/v0.2.11/websocketd-0.2.11-linux_arm.zip
    $ unzip websocketd-0.2.11-linux_arm.zip
    $ ./websocketd --help

**Comment by Shrest** [comment]
Thats super quick. Thanks. I will try that and get back. 
Am I missing something in my earlier trials? just curious.

**Comment by mem** [comment]
If you have (or can install) Go 1.5, you can do this:

```
$ mkdir websocketd
$ cd websocketd
$ GOPATH=$PWD GOOS=linux GOARCH=arm go install -v github.com/joewalnes/websocketd
```

This will download and compile everything you need to run websocketd in the RPi. At the end you'll have a websocketd binary in bin/linux_arm/

**Comment by asergeyev** [comment]
Just to clarify what @mem pointed out - you can compile ARM binary yourself ***on your regular machine*** and just move result binary to your RPi.

**Comment by asergeyev** [comment]
> Am I missing something in my earlier trials? just curious.
It's hard to tell. It looks harder to diagnose than to recommend approach that could be described in couple sentences.

**Comment by Shrest** [comment]
Thanks that helped. I tested using on Chrome in the developer console and it worked. 

In order to test it with a web page. I tried with the following html +javascript code(reference: Mozilla documentation on using web sockets)

index.html:
-------------------------------------------------------------
<!DOCTYPE html>
 <html>
  <head>
  <meta charset ="utf-8">
   <script src = "jQuery-2.1.4.js"></script>

   <script type = "text/javascript">
   $(function(){
                      var ws = new WebSocket('ws://rpi_ipaddress:8080'/);

                      ws.open=function(){
                                      $('h1').css('color','green');
                                      };
                      ws.onerror=function(){
                                      $('h1').css('color','red');
                                      };
                      ws.onmessage = function(event){
                                                  console.log('Count is :'+event.data);
                                                  $('div').append($('<p>',{text:event.data}));
                                                 };
                 });
</script>
</head>
<body>
   <h1> WebSockets Test </h1>
<form>
  <input type = "text"/>
</form>
<div> </div>
</body>
</html>
---------------------------------------------------------------

However, this is not working. Html elements - text & textbook appear on screen, but web socket connection is not happening. I believe something to do with javascript, Im not sure.
Can you help me get this working.Thanks.

**Comment by asergeyev** [comment]
Is websocket showing anything to you in window it's running? Can you telnet to port it's listening from locally? What command line you're using to start websocketd?

**Comment by Shrest** [comment]
I compiled the C program on websocketd.com & named it as My-program. Used

$ ./websocketd --port=8080 /home/pi/My-program

Two sentences appeared immediately indicating server is running on ws://raspberrypi:8080

When I open the html file above, nothing changes on the LXterminal.

However, if from a laptop, connected over ethernet to RPi, I try to access http://rpi_address:8080, the web browser shows the html text & text box. On LXTerminal, following appears:

(Date) (Time) |  ACCESS  |   http  |  url://rpi_ipaddress:8080/'  | NOT FOUND

(Date) (Time) |  ACCESS  |   http  |  url://rpi_ipaddress:8080/'  | favicon ico |  NOT FOUND

If it helps,I installed apache & the html file is in /var/www/

**Comment by asergeyev** [comment]
To check if it's functioning then it should be enough to run something like

    ./websocketd --devconsole --port=8080 echo OK

and then opening http://rpi_address:8080 from laptop, hitting connect button there and verifying it could show you OK


If this works I wonder if just running /home/pi/My-program behaves as you expect (reading input and printing something in STDOUT)

**Comment by asergeyev** [comment]
(Although could still be problem with websocket, we never tried it on ARM)

**Comment by Shrest** [comment]
I will try that. (./websocketd --devconsole --port=8080 echo ok)
However, there is one thing I was mentioning which made me think websocketd is fine - may be Im wrong. When I run ./websocketd --port=8080 /home/pi/My-program on RPi and try with the Javascript (from websocketd.com example) on Developer Console of Chrome on the laptop connected by a ethernet link to RPi, it gives the output on the developer console & LXterminal on RPi shows web socket connected. However, when I try it with a html page as explained above, it doesn't work.

**Comment by joewalnes** [comment]
I think a user contributed that wiki page: https://github.com/joewalnes/websocketd/wiki/Raspberry-pi. I just read it and it looks very complicated.

I tested websocketd on a RPi last year and it was simply a case of downloading the arm version from the downloads page and running it, just like on any other machine. @Shrest can you confirm this works (I don't have an RPi to hand)? If it does, we should just delete that page as it's confusing.

**Comment by Shrest** [comment]
@joewalnes It didnot work for me. I think its worth replacing that page with the simple instructions that @asergeyev has provided here. 
I look to get this working from a web page & contribute to the page. Awaiting that moment of seeing data from RPi on a webpage with a lot of excitement.Hopefully sooner...

**Comment by joewalnes** [comment]
Ok good. I have deleted that confusing Raspberry Pi page from the wiki. RPi
users should follow the same instructions as anyone else.

**Comment by Shrest** [comment]
@joewalnes That sounds good.

@asergeyev I tested with devconsole and it worked, ensuring websocketd is working fine. I did some investigation and found that the issue is with '$' in the html file. Developer console in Chrome  tells me " uncaught ReferenceError: $ is not defined". So, websocketd works on arm. Issue is getting the data to the webpage. But I don't know why "$" couldn't be identified, Im working on that now.If you have any idea, feel free to share.Thanks.

**Comment by asergeyev** [comment]
:)

**Comment by asergeyev** [comment]
Since it's now not a websocketd issue I'll keep it closed... But as advice I'd try to see if $ is supposed to be defined in some external lib, say jquery and it's not being loaded.

Or you might trim action that's dealing with $ and see what would work and what would not. Did you get HTML as example from somewhere?

**Comment by Shrest** [comment]
Yes. Websocketd issue is closed. Thanks for the cool tool and fantastic support.

**Comment by joewalnes** [comment]
@Shrest The issue is the example on that page uses jQuery. You need to include it in your page before using `$`.

```html
<script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
```

**Comment by Shrest** [comment]
Im using a local jQuery file. Once I reloaded the jQuery library file. It worked. I can see the data from RPi on the web page. Its been fun so far. Now, Im getting into plotting this on the page. I see good options including smoothie charts. 

Thanks @asergeyev and @joewalnes

**Comment by khalida** [comment]
> If you have (or can install) Go 1.5, you can do this:
> 
> ```
> $ mkdir websocketd
> $ cd websocketd
> $ GOPATH=$PWD GOOS=linux GOARCH=arm go install -v github.com/joewalnes/websocketd
> ```
> 
> This will download and compile everything you need to run websocketd in the RPi. At the end you'll have a websocketd binary in bin/linux_arm/

This is such a great way of installing it - how am I only learning about go now? Instructions for installing `golang` on rpi: https://stackoverflow.com/questions/48348262/install-go-golang-on-raspbian

Also, you need to do `go get` before you can `go install` - or at least I did (might be a better way to do both at once which I'm not aware of?)
