### ISSUE TITLE
SSL connection fails on Windows

### ISSUE THREAD

**Issue by Konstantinacc** [joewalnes/websocketd#181]
By running the command: `websocketd.exe --port=8080 --ssl --sslcert="localhost.crt"  --sslkey="localhost.key" cscript /nologo count.vbs`
and opening the `count.hmtl` page at: `https://localhost:8080/count.html` connection fails with error:
`TLS handshake error from 127.0.0.1:49246: CryptAcquireContext: Invalid Signature.`

Tested on Windows 7x64 using the count.vbs and count.html provided in [examples](https://github.com/joewalnes/websocketd/tree/master/examples) and websocketd.exe version 0.2.11.
Tried both a certificate signed from a CA and a self-signed certificate installed in `certmgr.msc`.

The above example worked as expected on Linux with both certificates.

Any ideas what can be the cause of this issue and how it can be fixed?

**Comment by asergeyev** [comment]
Anything useful with --loglevel=debug in websocketd?

Can you test on remote port, using --address=YOURIP?  
Can you see port being open? (can you telnet to that port from your linux machine?) Can you try to use "openssl s_client --connect ip:port" to see SSL hanshake debug info?

**Comment by Konstantinacc** [comment]
The above output was received with `--loglevel=debug` enabled.

Also tested using the option `--address=myip` but the result was the same.

Using telnet I can see that the port is open, and by running the command:
`openssl s_client -connect ip:port` the output is the following:
```CONNECTED(00000003)
140420566996640:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:s23_clnt.c:770:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 295 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---```

**Comment by asergeyev** [comment]
Well... There is really nothing that seem to be working for me too...  I tried with self-signed cert, tried with real one, tried with different kinds of options... Also tried to compile websocketd using go for windows and it did not work too...  Looks like go's SSL implementation is not quite windows friendly.

Can anyone confirm/deny that?

**Comment by TLaborde** [comment]
Similar problem here. I ca nexport a pfx file, transform it with openssl to a cer and a key file, but i'm getting the following error:
2016/03/29 13:06:47 http: TLS handshake error from 10.X.X.X:54213: CryptAcquireContext: Provider DLL failed to initialize correctly.
Not more information with debug mode, and openssl give me the same info...

On windows server 2k12 R2, all up to date, if it helps.

Is there something else i can go to help drill down on that issue?

**Comment by asergeyev** [comment]
I guess there should be some conversation with go-windows devs. Whoever write SSL lib parts and tests that work in Windows... To figure why our generic code has issues and how it's different from whatever they have.

**Comment by TLaborde** [comment]
I used a workaround by having IIS on the server to server as reverse proxy doing the SSL part. Issue could be related to chain of trust but i didn't have time to dig deeper...

**Comment by asergeyev** [comment]
thanks. At least something

**Comment by SwiftHacker** [comment]
Experiencing the exact same issue. Used websocketd in a small application for OS X, worked beautifully... but when I tried to update my Windows version to work with websocketd as well, it keeps giving me the errors: 

On Windows 7: CryptAcquireContext: Invalid Signature.
On Windows 8 & 10: CryptAcquireContext: Provider DLL failed to initialize correctly.

I also tried compiling websocketd using go for Windows. Also tried different types of certificates/options. Tried running it in compatibility mode, tried the 32/64 bit versions... nothing seems to work. Dependency walker didn't really give any useful clues either.

Websocketd _DOES WORK_ on Windows Server 2008, however (same codebase as Windows Vista). So I guess some DLL's got updated in Windows 7 and that's screwing go up? Not really useful though because I can't touch the Windows DLL's on users PC's. Not sure what to try next.

**Comment by asergeyev** [comment]
I'd suggest searching in golang mailing lists. It's problem that affects all go applications.

**Comment by asergeyev** [comment]
Windows users. could anyone try this for me? Using --passenv %SystemRoot%   or maybe without % signs... to start websocketd with SSL...   I now wonder if that's reason for the errors.

**Comment by olegzhuravel81** [comment]
Hello.
Command:
websocketd.exe --port=8080 --ssl --sslcert="alice.crt" --sslkey="alice.key" --passenv %SystemRoot% cscript /nologo count.vbs
returns the same error: CryptAcquireContext: Provider DLL failed to initialize correctly.

**Comment by asergeyev** [comment]
Thanks.... Will look again to see if someone else solved/fixed similar problem in other go projects...

**Comment by asergeyev** [comment]
Can someone check websocketd now under windows? Without any passenv since there is no way to cleanup windows environment partially, I decided to just keep it in full.

**Comment by asergeyev** [comment]
If someone could report back if SSL works under Windows with 0.3.0, we would be able to release it :)

**Comment by bogdanlazanu** [comment]
I was just struggling with version **0.2.12** and was getting "2017/12/18 14:15:45 http: TLS handshake error from 192.168.201.57:2405: CryptAcquireContext: Provider DLL failed to initialize correctly."

I tried version **0.3.0** and the error is gone, I can now use wss on Windows 10 x64.

**Comment by asergeyev** [comment]
Awesome!

**Comment by asergeyev** [comment]
@bogdanlazanu  do you have chance to try it with IE browser, does it work? (there is #275  that has details on the issue)

**Comment by bogdanlazanu** [comment]
@asergeyev  I just tested on:

- Chrome 63.0.3239.108 (Official Build) (64-bit)
- Firefox 57.0.2 (64-bit)
- Edge 41.16299.15.0
- Internet Explorer 11.98.16299.0

They all work.

**Comment by asergeyev** [comment]
It's good start, thank you very much, @bogdanlazanu

**Comment by rizanx** [comment]
I'm using websocketd version 0.3.0 in Windows. websockets is not working if SSL is enabled
 I'm facing the TLS handshake error. I tried self-signed and valid SSL certificate. Both are ends up vain.

- For SSL, I used _**websocketd.exe --port=8080 --ssl --sslcert="C:\Program Files (x86)\MyApp\Config\self-signed.crt" --sslkey="C:\Program Files (x86)\Prolaborate\Config\self-signed.key" MyAppSubscriber.exe**_  command to start websocketd.

- I used OpenSSL to create certificate and key files from .pfx.

Am I missing anything.

**Comment by rizanx** [comment]
> I was just struggling with version **0.2.12** and was getting "2017/12/18 14:15:45 http: TLS handshake error from 192.168.201.57:2405: CryptAcquireContext: Provider DLL failed to initialize correctly."
> 
> I tried version **0.3.0** and the error is gone, I can now use wss on Windows 10 x64.

I too faced the same issue in older version in windows. Updating to latest version also not helping. Don't know what am missing.
