### ISSUE TITLE
Issue with the watch command

### ISSUE THREAD

**Issue by angelopoerio** [joewalnes/websocketd#182]
If I try to run websocketd with the following script it keeps returning errors
```bash
#!/bin/bash
watch -n 20 netstat -t
```

This is what I get:
```bash
Fri, 06 Nov 2015 12:49:46 +0100 | INFO   | server     |  | Serving using application   : ./test.sh 
Fri, 06 Nov 2015 12:49:46 +0100 | INFO   | server     |  | Starting WebSocket server   : ws://angelo-OptiPlex-390:9000/
Fri, 06 Nov 2015 12:49:54 +0100 | ACCESS | session    | url:'http://localhost:9000/' id:'1446810594862650110' remote:'localhost' command:'./test.sh' origin:'file://' | CONNECT
Fri, 06 Nov 2015 12:49:54 +0100 | ERROR  | stderr     | url:'http://localhost:9000/' id:'1446810594862650110' remote:'localhost' command:'./test.sh' origin:'file://' pid:'5995' | Error opening terminal: unknown.
Fri, 06 Nov 2015 12:49:54 +0100 | ACCESS | session    | url:'http://localhost:9000/' id:'1446810594862650110' remote:'localhost' command:'./test.sh' origin:'file://' pid:'5995' | DISCONNECT
```

It can't grab the STDOUT of the command.

**Comment by asergeyev** [comment]
Watch is not using stdout really... it sends data to terminal. if you really want that all output in websocketd you rather to do something like 

    bash -c 'while true; do netstat -t; sleep 20 & wait; done'

I'll leave my reservations about this approach... Maybe reacting to websocket input and sending output only after this is better way... This way Javascript in HTML could only ask for more data when it's ready to process more.

**Comment by angelopoerio** [comment]
Thank you for your answer ... If I was a Go developer I would try to send a pr to fix this. This could be a good reason to dig into the language :)

**Comment by asergeyev** [comment]
Yes, but those are really console level tools. they wrap something to add convenient way of working with something simple. Exactly same layer where websocketd exists. Wrapping actual top is way more work than wrapping ps command with appropriate options.

**Comment by angelopoerio** [comment]
Yes, basically every tools that takes control of the terminal will not work. Other tools with this behaviour are: iotop, htop(it is ncurses), nethogs etc ...
I would suggest to describe this problem in the wiki of the project for completness.
