### ISSUE TITLE
issue with a premature disconnect

### ISSUE THREAD

**Issue by pi-factory** [joewalnes/websocketd#183]
Hi,
I've been messing around with websocketd for a couple of months now, and I love its simplicity (as a dabbler).
However, it seems to break (or I break it) on a regular basis, the tail end of the debug messages as follows:
Thu, 19 Nov 2015 15:04:13 +0100 | DEBUG  | env        | url:'http://10.0.0.79:8080/' id:'1447941823128524723' remote:'10.0.0.14' command:'/root/projects/temp/a_new_socket' | Header variable HTTP_USER_AGENT=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:42.0) Gecko/20100101 Firefox/42.0
Thu, 19 Nov 2015 15:04:13 +0100 | ACCESS | session    | url:'http://10.0.0.79:8080/' id:'1447941823128524723' remote:'10.0.0.14' command:'/root/projects/temp/a_new_socket' origin:'http://10.0.0.79' | CONNECT
Thu, 19 Nov 2015 15:04:13 +0100 | DEBUG  | process    | url:'http://10.0.0.79:8080/' id:'1447941823128524723' remote:'10.0.0.14' command:'/root/projects/temp/a_new_socket' origin:'http://10.0.0.79' pid:'7106' | Process STDERR closed
Thu, 19 Nov 2015 15:04:13 +0100 | DEBUG  | process    | url:'http://10.0.0.79:8080/' id:'1447941823128524723' remote:'10.0.0.14' command:'/root/projects/temp/a_new_socket' origin:'http://10.0.0.79' pid:'7106' | Process 7106 terminated after SIGINT
Thu, 19 Nov 2015 15:04:13 +0100 | ACCESS | session    | url:'http://10.0.0.79:8080/' id:'1447941823128524723' remote:'10.0.0.14' command:'/root/projects/temp/a_new_socket' origin:'http://10.0.0.79' pid:'7106' | DISCONNECT

a_new_socket works just fine on its own. Is there something obvious I'm missing in the penultimate line?

Thanks in advance.

**Comment by asergeyev** [comment]
I wonder if you are connecting to this port just by simple browser request and not by javascript's websocket API.... No other ideas otherwise without knowing what your script does...

Maybe you can minimize code to create simple HTML and script as a test and I'll look into it for you?

**Comment by pi-factory** [comment]
Thanks for coming back - I had a pro look at it, and if his solution doesn't work, I'll take up your offer!
