### ISSUE TITLE
disable SSLv3 ?

### ISSUE THREAD

**Issue by jbardu** [joewalnes/websocketd#185]
How do we force TLS only in the SSL support of websocketd ?

https://gist.github.com/olov/eb60ab878eb73a7c5e22

**Comment by asergeyev** [comment]
It would be something for us to add I think...

**Comment by jbardu** [comment]
It would be helpful because as it stands, security best practice scanners produce warnings regarding POODLE (due to SSLv3), and the availability of RC4 as a cipher, as well.

**Comment by asergeyev** [comment]
We will re-compile release with 1.6 as it's going out. Right now if anyone interested in using SSL 1.6rc2 is your way to go.

**Comment by asergeyev** [comment]
I pre-released 0.2.12, there should be no more SSLv3 and RC4

**Comment by Zearin** [comment]
:+1:

**Comment by asergeyev** [comment]
I would just keep it closed if someone wants to re-open it, you're welcome to do so.
