### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by erm3nda** [joewalnes/websocketd#189]
I've tested that lib time ago and really worked out of the box.
Now I tried `websocketd bash --devconsole` and didn't load the dev console, but showing "404 page not found".
 
Console dev doesn't work on these examples:
This doesn't work: `websocketd bash --devconsole`
This doesn't work: `websocketd /bin/bash --devconsole`
But, the ws://localhost does work!

This does work ok: `websocketd --dir=/bin --devconsole`

Is not port bind and is not root perms.
It is something related to --devconsole ??

Devconsole is pretty usefull for me.

**Comment by mattwind** [comment]
try this if running websocketd from localfolder

websocketd --staticdir=.

or put in the full path

websocketd --staticdir=/home/username/directory/

also it will say 404 if you don't have index.html in the staticdir, unless you point to the proper file in your browser http://localhost/yourfile.html

**Comment by erm3nda** [comment]
But, I've used this program in the past with an short command like `websocketd bash --devconsole`
Of course i can also make aliases, scripts or whatever can circunvent. What i really wanna know is why i cannot use now like that.

`staticdir=.` did activate the CGI feature, shown my files and didn't activate --devconsole at all, maybe because both CGI and --devconsole want's the browser output...

Usually, i add --devconsole at the end of the params, but if you add at 1st positional param it adverts you with 
```
| FATAL  | server     |  | Invalid parameters: --devconsole cannot be used with --staticdir. Pick one
```
So now im pretty sure both options can't be run, by design.

**Comment by erm3nda** [comment]
OK! I found it.
As i got different results by positional arguments, now I've tried `websocketd --devconsole bash`, so seems I really didn't use `websocketd bash --devconsole` in the past...

Now it worked as expected.
Sorry for my mistake ;)

**Comment by asergeyev** [comment]
no prob. It's sometimes confusing that flag parsing works only one way in go programs but it's easier.
