### ISSUE TITLE
Need a logo

### ISSUE THREAD

**Issue by joewalnes** [joewalnes/websocketd#19]
Need a logo for websocketd. A big one for the website, and a favicon.

**Comment by jasonhinkle** [comment]
I nominate myself as the worlds second worst designer, but anyway...

![websocketd](https://cloud.githubusercontent.com/assets/313176/6207085/2191780e-b567-11e4-8fae-6222f652faab.png)

**Comment by joewalnes** [comment]
Thanks for the contribution. But no thanks. Just not my (completely subjective) taste.

Closing the issue - I don't want others to spend time on this.

**Comment by asergeyev** [comment]
http://www.designmantic.com/ tool come up with one interesting idea...
![create_thumb](https://cloud.githubusercontent.com/assets/715656/9974264/df5cd360-5e54-11e5-8334-8e604ae652bb.png)
