### ISSUE TITLE
how to use python greeter program in /examples/python?

### ISSUE THREAD

**Issue by shakeel-khan8879** [joewalnes/websocketd#190]
I was using the greeter.py program that has the stdin/out example and when I used this program I wasn't able to figure out how to send a message from the browser to the server, I get an lengthy (sort of) error that seems to be complaining about the line where the server prints out the message sent by the client to the server. How would I get that text input from the javascript application and send it to the server?
Thank You in Advance,
-S

**Comment by asergeyev** [comment]
Hi, I think that was already answered with this example :)

https://gist.github.com/asergeyev/a33f0f595ff551a5b8d3

Try it, with websocked --port 8080 python greeter.py  and loading HTML just from disk... (or you can put HTML into folder and do websocked --port 8080 --htmldir ./html/ python greeter.py
