### ISSUE TITLE
sub-process is not terminated when disconnect occurs (but main process is terminated)

### ISSUE THREAD

**Issue by jpwynn** [joewalnes/websocketd#191]
It appears that a websocket 'close' terminates the main process invoked by websocketd, but subprocesses of that main process do _not_ get terminated. Is that expected?

On a Mac (El Capitan) I have an executable python script test.py which websocketd executes. (During dev't I'm executing everything from a subdirectory where I want to dump a bunch of photos using the binary gphoto2)

```
../websocketd --port=8082 --devconsole ../test.py
```

../test.py executes an installed binary via subprocess():
```
result = subprocess.call('gphoto2 --force-overwrite --get-all-files' , shell=True)
```

There are 60-something photos that gphoto2 will copy when invoked as above, unless the process is terminated.

As expected: If I start the script directly from terminal, then control-C after a few files, the sub-process gphoto gets terminated and no more photos get copied.

However, if I use a browser connected to `http://localhost:8082/`, click the checkbox to start it, and then click the 'x' after a few files get copied:

a) I see from the websocketd terminal output the expected DISCONNECT immediately
b) I see on the browser devconsole the expected 'close' and 'onclose' events immediately
c) I see python disappear from the process monitor (Activity Monitor on the Mac) so the test.py does appear  to terminate immediately
__however__
d) the gphoto2 subprocess keeps running, so all the photos get copied.

That was surprising to me since running test.py via the command line then hitting control-C does terminate the subprocess.

**Comment by asergeyev** [comment]
General idea is that If you fork process, you're responsible for supervising it. Tracking child processes from one that websocketd supervises could be task beyond simple principle...

But I think you could try workaround here...

Ctrl^C is not truly sending signal to your process. At least this is what I suspect. It goes to forked copy of bash that runs is. And when that copy of bash gets signal it does some work to kill whole process group.

Therefore I suggest simulating it... Try to execute websocketd with bash -c "./yourcommand.py" and see if it makes things better. Let me know please, it would be interesting for me to investigate other solutionif this trick would not work.

**Comment by jpwynn** [comment]
I tried that just now a couple of times... same result... a very clever suggestion nonetheless.

I agree entirely a solution to 'children running wild' isn't really the responsibility of the websocketd process, I'm just a bit surprised linux/python/bash don't handle it automatically.

However, I noticed if I kill the websocketd process (via control-C in the window in which I ran the websocketd command) that DOES stop the sub-process. Not too surprisingly, hitting control-C also shows the following in the console output where I ran websocketd:

```
Sun, 17 Jan 2016 00:42:12 +0000 | ERROR  | process    | url:'http://raspberrypi.local:8082/' id:'1452991318183200623' remote:'192.168.0.2' command:'/bin/bash' origin:'http://raspberrypi.local:8080' pid:'3379' | Unexpected error while reading STDERR from process: read |0: bad file descriptor
```

However, if I run `kill <pid>` to kill the websocketd process pid that does NOT stop the subprocess.

(Incidentally, I got the same result son a Mac and a Raspberry Pi.)

**Comment by asergeyev** [comment]
I guess whole "CTRL+C" is different in interactive bash...
http://stackoverflow.com/questions/6108953/how-does-ctrl-c-terminate-a-child-process

I'll work on creating simulation of this in shell and then see if we would find way to kill process group. This should take care at least those situations where all forks are well-behaved.

**Comment by jpwynn** [comment]
Here are two short files, both python scripts, that can be used to illustrate the issue.

1. Make them both executable in some directory
2. invoke `../websocketd --port=8080 --devconsole ./sample_parent.py`
3. load `http://localhost:8080/` in a browser
4. click the checkmark to start
5. click the 'x' to close the websocket when it gets about halfway thru the 10 fake copy-file (eg you see `copy 5` or `copy 6`)

You'll see by viewing sample_log.log that 
(a) the parent task gets terminated immediately
(b) the child task kept running from 0 to 9
(c) naturally, the parent task does not re-invoke the child again since the parent was terminated

sample_parent.py:
```
#!/usr/bin/python

import threading, time, subprocess, re, os
from random import randint
from sys import exit

logfile = "sample_log.log"

def log_this(msg):
  subprocess.call("echo '" + msg + "' | tee -a " + logfile, shell=True)

subprocess.call("echo 'start new log' > " + logfile, shell=True)

for attempt in range(5):
  msg = 'Parent loop ' + str(attempt) 
  subprocess.call("echo '" + msg + " " + str(attempt) + "'", shell=True)
  log_this(msg)
  result = subprocess.call('set -o pipefail && ./sample_child.py  | tee -a ' + logfile , shell=True, executable='/bin/bash')
  subprocess.call("echo 'Parent result = " + str(result) + "'", shell=True)
 
print "Parent done"
```

sample_child.py:
```
#!/usr/bin/python

import threading, time, subprocess, re, os
from random import randint
from sys import exit

logfile = "sample_log.log"

for attempt in range(10):
  subprocess.call("echo '  copy " + str(attempt) + "'", shell=True)

  time.sleep(1)

print "Child done"
```

**Comment by asergeyev** [comment]
Thanks!

**Comment by asergeyev** [comment]
I actually tried last time after you brought your example... Nothing seem to work reliably. I can do some trickery in Linux with process groups and such but that would create code divergence between Windows and Mac/Linux/BSD/Solaris versions which I don't want to have. 

Do you think it would be enough for people like you if we illustrate this on example (similar to yours) and recommend workaround?

**Comment by Zearin** [comment]
Just learned about the existence of websocketd.  I haven’t started using it yet, but a predictable behavior for the lifetime of subprocesses is a must-have for me.  This project looks **awesome**…but I’ll be waiting for some progress on this issue before I try it out.  (Subscribed to this issue. ☻)

**Comment by asergeyev** [comment]
@Zearin you should try it with your application. I think we really could only find workaround here, it's unlikely websocketd itself would do things differently to allow applications that fork/exec their child processes to behave correctly.

**Comment by asergeyev** [comment]
@jpwynn  your parent reworked to behave:

```
#!/usr/bin/python

import threading, time, subprocess, re, os
from random import randint
from sys import exit
import signal

logfile = "sample_log.log"

def log_this(msg):
  subprocess.call("echo '" + msg + "' | tee -a " + logfile, shell=True)

def handler(signum, frame):
    log_this("SIGNAL %d" % signum)
    os.killpg(os.getpid(), signal.SIGTERM)
    exit(1)

signal.signal(signal.SIGINT, handler)

try:
    os.setsid()
except:
    pass # running from UNIX shell it's auto-set to be a leader

subprocess.call("echo 'start new log' > " + logfile, shell=True)

for attempt in range(5):
  msg = 'Parent loop ' + str(attempt) 
  subprocess.call("echo '" + msg + " " + str(attempt) + "'", shell=True)
  log_this(msg)

  try:
    result = subprocess.call('./sample_child.py  | tee -a ' + logfile , shell=True, executable='/bin/bash')
    subprocess.call("echo 'Parent result = " + str(result) + "'", shell=Tr
  except:
    pass # suppress error when subprocess.call crashes due to signal

```

**Comment by asergeyev** [comment]
I'll close this as one that has workaround.
