### ISSUE TITLE
add a parameter to avoid closing socket after send message

### ISSUE THREAD

**Issue by quentinlamamy** [joewalnes/websocketd#193]
Hi,

Your websocket is very simple , it's cool but in my project the socket need to stay alive after sending message. Is that possible with a parameter ?

Regards

**Comment by asergeyev** [comment]
If your program stays alive after sending message and client does not call ws.close() webocketd would keep socket open.

**Comment by LamamyIVS** [comment]
seems, not. Weird....

**Comment by asergeyev** [comment]
Can you let me know how you're noticing it or simulate it with some other program running behind websocketd?

**Comment by asergeyev** [comment]
I'll close this but if you got example feel free to re-open
