### ISSUE TITLE
Data blips at client

### ISSUE THREAD

**Issue by Shrest** [joewalnes/websocketd#196]
Hi,
    Im using websocketd to stream data from a sensor to web browser and plot it using smoothie library. However, I see blips in the data approx. every 30secs. The value jumps to  (+/-) 36893488147419103000 for a sample and retains the sensed measurement in the next sample. When I use parseFloat() function for the same value, the value jumps to 2 or -2.

I checked with my C code on my Raspberry Pi, but running it locally. It is fine and there are no blips over here. But when data streams over to the web browser, I see consistent blips. 

If it helps, I tried Chrome and Internet Explorer web browsers and the response is similar.

Seems to me to be a issue with websocketd, but I don't what it is. Request your help.

**Comment by asergeyev** [comment]
I don't see how websocketd could change data that your script emits so technically it never should lead to confusing values. But worth checking anyway...

Try to replace your actual sensor script to some fake data emitter. For example you can use following bash script that prints sequence of numbers:

    websocketd ... [options] bash -c 'while true; do for i in 0 1 2 3 4 5 6 7 8 9 10 9 8 7 6 5 4 3 2 1; do echo $i; sleep 0.1; done; done'

then try to chart those numbers and see if you have anything odd.

**Comment by Shrest** [comment]
Hi @asergeyev Good to hear from you. It was surprising to me as well, so first thing I did was check the server code locally, which was fine.
I will try the fake sensor script and update you on the response from Raspberry Pi.
Thanks.

**Comment by aj664** [comment]
Utter speculation:   what format is you rasp pi generating floating point numbers?   is JavaScript able to accept floating point numbers in that format?     I suspect JavaScript can't do the full range of floats.

If this is true, try truncating you floats to a few less decimal places.


On 10 February 2016 3:08:13 am AEDT, Shrest <notifications@github.com> wrote:
>Hi,
>Im using websocketd to stream data from a sensor to web browser and
>plot it using smoothie library. However, I see blips in the data
>approx. every 30secs. The value jumps to  (+/-) 36893488147419103000
>for a sample and retains the sensed measurement in the next sample.
>When I use parseFloat() function for the same value, the value jumps to
>2 or -2.
>
>I checked with my C code on my Raspberry Pi, but running it locally. It
>is fine and there are no blips over here. But when data streams over to
>the web browser, I see consistent blips. 
>
>If it helps, I tried Chrome and Internet Explorer web browsers and the
>response is similar.
>
>Seems to me to be a issue with websocketd, but I don't what it is.
>Request your help.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/joewalnes/websocketd/issues/196

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Shrest** [comment]
Hello @asergeyev . The fake data emitter worked. 

@aj664  the floating point formats for RPi and Javascript are similar. But I should thank you for the "utter speculation", as it helped me debug. I had to change the function return value from float to double and it worked.

Thanks @asergeyev and @aj664.
