### ISSUE TITLE
Release 0.2.12

### ISSUE THREAD

**Issue by asergeyev** [joewalnes/websocketd#197]
Pre-released today. I'd give it couple weeks to test out...  Hopefully last 0.2;

**Comment by bentranter** [comment]
Nice, I'll hold off on updating the Homebrew formula until this is officially released

**Comment by asergeyev** [comment]
I'll add 3-4 days in order to check windows behavior, few people asked there in tickets and time actually lines up well for that.

**Comment by asergeyev** [comment]
Just out of curiosity.. Anyone tried or uses pre-released binaries?
