### ISSUE TITLE
Unable to bring output from a shell script

### ISSUE THREAD

**Issue by evozenn** [joewalnes/websocketd#199]
Hi there,
I'm testing the tool for a very simple accomplishment which is to output my PostgreSQL log filtered by the database I want to monitor.
In that sense I created the shell script below which outputs the log with the correct word filtering (grepping):
--- monitora.sh ---
```
#!/bin/bash
log=/mnt/d1/postgresql/logs/postgresql-`date +%u`.log
echo "Please add the database name to be monitored below: "
read banco
echo "Lets monitor ${banco} from now on..."
/usr/bin/tail -f $log | grep -i "${banco}"
```
And then I issue below's command: 
`./websocketd --devconsole --loglevel=debug --port=1012 ./monitora.sh`

In my browser I type the location and then add the database name as needed, but I only get its output from the script after 37 to 41 lines are added to the logfile, whereas if I execute the very same script with the same variable value ($banco), I instantly get its output on my shell-screen.

Apparently there is a buffer on websockted to be fullfilled before it sends the required output to my browser.

Am I doing something wrong or am I missing something else?

Cheers,
Lauro Ojeda

**Comment by gabordemooij** [comment]
I think the shell buffers, 

http://stackoverflow.com/questions/3465619/how-to-make-output-of-any-shell-command-unbuffered

**Comment by gabordemooij** [comment]
In citrine use: Program flush.

**Comment by evozenn** [comment]
Thanks Gabor.
The problem was solved using the references you gave, specifically instructing grep to use line-buffering based on this article: [](http://www.pixelbeat.org/programming/stdio_buffering/)

Now the solution was only a slight change in my last line of the script which follows:
`/usr/bin/tail -f $log | grep** --line-buffered** -i "${banco}"`

The "unbuffer" and "stdbuf -i0 -o0 -e0" tricks didn't work for me.

Thanks again. Hope this helps somebody else.

Cheers,
Lauro Ojeda
