### ISSUE TITLE
Passing $_GET variables (or similar) to script called by websocketd

### ISSUE THREAD

**Issue by fb35523** [joewalnes/websocketd#202]
Hi!

I have websocketsd working to graph some parameters from a CMTS with SmoothieCharts and it all works like a charm. Now I'd like to improve the solution to be more "dynamic", so the link I click determines what CMTS and which parameters I want to graph.

Please be gentle, I'm not a fully fledged programmer, but I do use bash, perl and php from time to time at a level slightly above newbie :)

The idea:

Send a request to monitor certain interfaces on a certain CMTS ("cable modem router")

```
<a href="/test.html?CMTS=C4&US=1,2,3,4"></a>
```

In test.html:

````
var canvas = document.getElementById("mycanvas");
function createTimeline() {
...
chart.streamTo(document.getElementById("mycanvas"), 0);
}
var ws = new ReconnectingWebSocket('ws://194.23.63.222:8080/test?CMTS=C4&DS=1,2,3,4&CALL=WS');
````

I can populate the above parameters via php in that html file, something like this:

````
var ws = new ReconnectingWebSocket('ws://194.23.63.222:8080/test?CMTS=$cmts&DS=$param_list&CALL=WS');
````

Please note that this is not the issue here. I have the static "ws://194.23.63.222:8080/test?CMTS=C4&DS=1,2,3,4" for now until I get those params propagated to the next step.

It is the parameters CMTS and US I want to pass to the PHP script below:

The websocketd:

```
/path/websocketd --port=8080 --staticdir=/path/static --passenv=QUERY_STRING,REMOTE_PORT --loglevel=debug /path/wsscript.php
```

In wsscript.php I have tried multiple methods of reading the query strings (remote port was just a test):

```
$CMTS=$_POST["CMTS"];
$US=$_GET["US"];
$QUERY_STRING=$_POST["QUERY_STRING"];
$REMOTE_PORT=$_GET["REMOTE_PORT"];

$REQ=var_dump($_REQUEST);
var_dump($GLOBALS);
```

I get absolutely NOTHING in the $_GET or even $_REQUEST when the script is called via the ws, even though the websocketd debug output mentions those params:

```
Thu, 17 Mar 2016 12:27:22 +0100 | DEBUG  | env        | url:'http://host-ip:8081/test?CMTS=C4&DS=9,10,11,12&CALL=WS' id:'1458214042400844263' remote:'client-host' command:'/path/wsscript.php' | Std. variable: QUERY_STRING=CMTS=C4&DS=9,10,11,12&CALL=WS
```

Basically, this is the flow I want:

```
var ws = new ReconnectingWebSocket('ws://194.23.63.222:8080/test?CMTS=C4&DS=1,2,3,4&CALL=WS');
```
passes params CMTS and US (and CALL for debug) to:

```
/path/websocketd --port=8080 --staticdir=/path/static --passenv=QUERY_STRING,REMOTE_PORT --loglevel=debug /path/wsscript.php
```

The above seems to work according to the debug output, but websocketd doesn't send params CMTS and US to wsscript.php the way I expect. I want to read the params in wsscript.php and do snmp queries to the right CMTS and filter out the right US interfaces to monitor.

wsscript.php is supposed to do essentially this:

```
snmp2_real_walk("$cmtsip", "$community", ".1.3.6.1.2.1.10.127.1.1.4.1.5");
```

and output up to 8 values to stdout that SmoothieCharts then graphs.

Ideas?

/Fredrik

**Comment by asergeyev** [comment]
Disclaimers:

* I did not read whole thing ;) What I got is that you want to use $_GET as you would in php script running under Apache/Nginx.
* I don't use php. I don't know if $_GET is even something that you should use in php nowadays. 

Well... there is solution I can think of.

In order for what you want to work you need some way of setting that _GET. In Apache it's done by mod_php, in Nginx QUERY_STRING gets to php-frm and also converts to hash.

Websocket is not really running PHP-frm since it's not talking HTTP to program. You need to convert QUERYSTRING yourself.   This way probably (might need adjusting):

````
parse_str($_SERVER['QUERY_STRING'], $_GET);
````

You can wrap it with conditionals to only do this when you work under websocketd.


p.s.
You don't need QUERY_STRING in passenv. Standard HTTP variables are generated and passenv is for storing value your shell had before starting websocketd and passing it to every command.

**Comment by fb35523** [comment]
Sorry if I was a bit overly detailed, but sometimes answers get better if "all" info is provided in the inital post (less hazzle for the resonder in terms of asking for more info).

I really just want to pass variables to the script, not necessarily via $_GET, and I'll try your idea tonight.

Thanks a lot!

/Fredrik

**Comment by fb35523** [comment]
Works like a charm! Thanks once again!

parse_str($_SERVER['QUERY_STRING'], $_GET);
$CMTS=$_GET["CMTS"];
$US=$_GET["US"];

Btw, in my first post, I had DS and US mixed up. Took me a while to sort that one out...

/Fredrik

**Comment by asergeyev** [comment]
:)
