### ISSUE TITLE
Using php-cgi as cgi is not working

### ISSUE THREAD

**Issue by mmmint** [joewalnes/websocketd#203]
Wed, 23 Mar 2016 18:23:05 +0100 | ACCESS | http       | url:'http://192.168.1.1/info.php' cgiscript:'/www/info.php' | CGI
2016/03/23 18:23:05 cgi: bogus header line: <b>Security Alert!</b> The PHP CGI cannot be accessed directly.
2016/03/23 18:23:05 cgi: missing required Content-Type in headers

**Comment by asergeyev** [comment]
Could you post how you're running websocketd? (it's command line)

**Comment by mmmint** [comment]
- Adding **cgi.force_redirect = 0** to php.ini

- Adding **#!/usr/bin/php-cgi** a the top of every php file

Now lets start the fun:
./websocketd --port=80 --cgidir=/alpha_www  php-cgi

**Comment by asergeyev** [comment]
Why would you need php-cgi with websocketd and not with say apache?
