### ISSUE TITLE
array of requests

### ISSUE THREAD

**Issue by progman** [joewalnes/websocketd#204]
websocked starts application as CGI.
I think is very slow process.
Maybe create array of requests and will start applocation as FastCGI?
it will be absolutely perfect!

**Comment by progman** [comment]
I say about this: websocked starts application. application wait request. browser open websocket, send request. websocked proxy request to application and proxy request from application. browser recv responce and close websocket. application still live and sleep on read. application waits other requests from other browser. you can make special protocol for this behavior from websocked to application (as FastCGI)

**Comment by progman** [comment]
you cat make special option for this behavior in websocketd

**Comment by asergeyev** [comment]
I don't think we have really good reason to turn to FastCGI direction. There are plenty of good servers which can do that. Mixing it with websocket server is kind of out of scope of websocketd. We already have --cgi that's in the way... Adding fastcgi mode makes everything even more complicated.

**Comment by progman** [comment]
This can be special mode. This will be very fast mode without start and stop application for each request. I tell do not about FastCGI, I tell about mode like FastCGI, I tell about mode without start and stop application for each request. I think this is very important for this project. if you dont make it then this make others and they will be faster then your project.
