### ISSUE TITLE
Unreasonable CPU usage while idle and connected

### ISSUE THREAD

**Issue by brettnem** [joewalnes/websocketd#205]
Hello,
I'm using version 0.2.11 (go1.4.2)

I have about 8 sockets connected, doing nothing. The process websocketd is calling is consuming about 12% CPU. The machine isn't doing *any* other tasks. System load is uncomfortably high (8+)

Performing an strace appears to be also idle on the same pid producing the load:

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
22796 root      20   0  678896  18160   1424 S 14.9  1.8   2986:22 testws.py
22574 root      20   0  514528  17316   1324 S 14.3  1.7   2987:39 testws.py
 1143 root      20   0  514528  17308   1308 S 12.3  1.7 747:01.43 testws.py
 3275 root      20   0  514528  18028   1920 S 12.3  1.8 744:41.68 testws.py
20156 root      20   0  514524  19200   1452 S 12.3  1.9 769:21.55 testws.py
21664 root      20   0  514528  15120   1144 S 12.3  1.5 767:05.90 testws.py
22708 root      20   0  661992  18792    848 S 12.3  1.9   2987:09 testws.py
12636 root      20   0  440536  16872   1428 S 11.9  1.7 785:42.83 testws.py

root@websocket:~# strace -p 12636
Process 12636 attached
futex(0x2a1b0d0, FUTEX_WAIT_PRIVATE, 0, NULL
<nothing happens here.. waited about 10-20 seconds>

Any ideas? I know this isn't specifically websocketd doing the hang, but this is just a python script doing nothing really.

**Comment by brettnem** [comment]
Actually, I'm thinking the issue here is that if you follow the python examples, you'll see reads from STDIN in a tight loop, which is what we did. I'm thinking that this is hard on the system. Does that seem reasonable? Is there a better way to do this that doesn't overuse CPU?

Thx

**Comment by asergeyev** [comment]
I think you are right, it's from python, since you'd see websocketd in top if it'll eat resources.

Any opinion on how to rewrite those python examples? I'd be happy to accept your PR.

**Comment by brettnem** [comment]
I'm testing this out with a sleep(0.1) in the while loop. I think it just needs some breathing room. I'll report back with my results.

**Comment by brettnem** [comment]
That did the trick. Without the sleep it's a CPU hog. Please make a note in the examples. FWIW other languages probably have similar issues. 

Thanks!

**Comment by asergeyev** [comment]
Thanks
