### ISSUE TITLE
New option for shutdown process gracefully.

### ISSUE THREAD

**Issue by aplicacionamedida** [joewalnes/websocketd#207]
Hi,
when the websocket is disconnected the process is killed abruptly. Some programming languages (for example Tcl) can detect when the channel is closed, in this case, stdin. When the stdin is closed, the program can do all the necessary cleanup, before to exit. This cleanup is necesary for some programs. Websocketd awaits 100 milliseconds but maybe this is not enough in some cases. I propose a new option, for example -no-kill-process, or a similar name, to avoid conditionally in this file:
>      process_endpoint.go

inside the function *Terminate()*, all the instructions that follows "pe.process.stdin.Close()":
```go
func (pe *ProcessEndpoint) Terminate() {
    terminated := make(chan struct{})
    go func() { pe.process.cmd.Wait(); terminated <- struct{}{} }()

    // for some processes this is enough to finish them...
    pe.process.stdin.Close()
    // All the next instructions are not processed if the option -no-kill-process is true
```
I am not a go programmer but I think that this should be easy to implement adding a new command line option to websocketd and a if condition inside the Terminate() function.

**Comment by asergeyev** [comment]
It was always concerning to leave zombies behind... Having option that would not send signals is probably good workaround.  I wonder if it's still good to send INT and TERM as signals that process could handle gracefully and just not send kill or if the option should be to not send signals upon socket closure (and stdin) at all...

Thoughts? @joewalnes? others?

**Comment by aplicacionamedida** [comment]
Hi asergeyev,thanks for your quick answer. Some programming languages like Tcl, can not handle signals. Others like Python can handle signals using the signal module. Maybe it's better an option to indicate the signal. And the values for this option are: "none" for no signal, or the name of a signal, for example, int.

**Comment by aplicacionamedida** [comment]
This is my solution. It works for all programming languages:
Add a new option:
>    -no-kill-process message
(the option name could be -no-kill-process or something similar).

If this option is present:
      If *message* is a non empty string:
            Send this special text message to the program to notify that the websocket has been closed.
            Close stdin.
      If *message* is an empty string:
           Only close stdin.

If this option is not present:
    websocketd kills the process abruptly.

The drawback of using signals to notify to the process to close gracefully are:
- not all programming language can handle signals
- signals are operating system dependent

**Comment by asergeyev** [comment]
I was thinking more of regulating delay...  

--closems milliseconds  // specifies time process needs to gracefully finish before websocket 
                                     // will send termination signals to it

100 stays as default; 0 would not send any signals after closing STDIN and it's not recommended, IMO anyone is better off with 10000 than 0 :)


I don't like message part because same string could be sent from browser and websocketd has no responsibility to filter/fix input lines. Protocol promise would not change: we send everything we receive to running program and nothing else.

**Comment by aplicacionamedida** [comment]
Hi asergeyev, I think that both ideas are good. Many times it's better to guive total responsability of the cleanup to the process. Many times it's not possible to know the exact time of this cleanup in advance. The communication between process and browser can follow a protocol. For this reason, I think that to send a message to signal a websocket connection closed opens a new possibility to the developer. I think that botth options should be provided, because my suggestion open another possibilities to the developer,and sometimes it's not possible to know in advance the exact time of this cleanup.

**Comment by asergeyev** [comment]
No comments, merging as it stands.
