### ISSUE TITLE
Keeps closing after about 12 hours...

### ISSUE THREAD

**Issue by mmmint** [joewalnes/websocketd#209]
Im continously feeding the browser with a dataset every second via websocketd, but always after about 12 hours the connection closes...As far as I know, the connection should be kept-alive by periodically having the application send a message down the pipe and thats exactly what Im doing...

Is this a known issue?

**Comment by asergeyev** [comment]
Any chance you can see something in logs or enable full logs (--loglevel debug) and find lines that lead to termination? Ideally you never should assume socket would not close accidentally from network issues but I totally agree that having exactly 12 hours multiple times is strange.

**Comment by asergeyev** [comment]
Anyone wants to try to replicate that?

**Comment by asergeyev** [comment]
I've seen  ```websocketd --devconsole --port 8080 bash -c 'while true; do date; sleep 10; done'``` work more than 12 hours (browser sitting in devconsole). I'm repeating this once more but really wonder if someone else would check it too.

**Comment by asergeyev** [comment]
Yep. Worked for me fine, after second 12 hours I even suspend/restored my laptop few times and it was still chugging along. Could be OS/firewall/browser limits.

**Comment by asergeyev** [comment]
Keep me posted if you find something else. I'll close for now.
