### ISSUE TITLE
Can not Send dot "."

### ISSUE THREAD

**Issue by s-mohammad-dabir** [joewalnes/websocketd#216]
I can not receive dot with websocket form my custom remote app 
app example:

    for (i = 1; i <= 10; i++) {
        printf(".");
        usleep(500000);
    }

**Comment by mattgodbolt** [comment]
I believe by default `stdout` is line-buffered. Try putting an `fflush(stdout);` after the `printf` and see if that helps.

**Comment by asergeyev** [comment]
or start it with unbuffer if your OS has it.

**Comment by asergeyev** [comment]
I'd close. Let us know if flushing buffer helped you.

**Comment by s-mohammad-dabir** [comment]
I tried something else.ok I will test it again and say the result.thank u
for your response.
