### ISSUE TITLE
support for STDERR redirection

### ISSUE THREAD

**Issue by rockonedege** [joewalnes/websocketd#219]
I am using websocketd to wrap a toolset and leverage the devconsole as client console. Everything works fine except that the toolset being wrapped prints errors to STDERR, which is right per se, but part of the information is lost from the devconsole.

Is it possible to added a switch to control where STDERR should be printed,  on the local console or over websocket to the client?

**Comment by asergeyev** [comment]
You probably better off creating script that would redirect stderr and running it inside of regular websocketd...

     websocketd  --port 8080 bash -c 'command 2>&1'

would do the trick

**Comment by rockonedege** [comment]
this looks neat. But... I'm on Windows. do you know what's the equivalent in Windows commandline?

**Comment by rockonedege** [comment]
just googled and tried.  appending ' 2>&1' to the command does the same trick. Thanks, Alex. A good learning.

**Comment by asergeyev** [comment]
You're welcome
