### ISSUE TITLE
garbage characters 

### ISSUE THREAD

**Issue by rockonedege** [joewalnes/websocketd#220]
it looks some how websockedd would added some garbage to the STDOUT and STDERR randomly, i.e. not for every message.

Examples:

devconsole for STDOUT:
 [1m[32m2016-07-14 11:27:57 Completed command 'tfs_get' in 21.970703 sec[0m[0m  

console for STDERR:
Thu, 14 Jul 2016 11:26:24 -0400 | ERROR  | stderr     | url:'http://127.0.0.1:8099/' id:'1468509955507750000' remote:'127.0.0.1' command:'f:\sandbox\runner\\main.exe' origin:'http://127.0.0.1:8099' pid:'20756' | ←[1m←[31mERROR: 'sdafSDAF' not foundin folder 'd:\'←[0m←[0m

**Comment by asergeyev** [comment]
Could you please add your OS and version? I doubt it's websocketd though. Those strings are likely coming from the program you're running under websocketd... Did you try to run it without wrapping and see if it prints them?

**Comment by rockonedege** [comment]
Windows 7 inside VMWare. They only exist when being hosted with websocketd. It looks to me something about the std i/o buff flush. But I am not sure how.

**Comment by rockonedege** [comment]
Notice how they surround a line of message, not breaking into anyone,if they appear.

**Comment by rockonedege** [comment]
If this helps: I have a set of command line tools I'd like to access remotely. Think of the git commands. in order keep them in a same process. I have a simple c++ console program, all it does being getting inputs and calling system(...) in a loop, and it is hosted by websocketd.

Without being hosted, the c++ program does not print the extra characters in question.

**Comment by asergeyev** [comment]
I still don't see where those may appear if not from your program. When you run it in your console without websocketd... do you see any weird chars?

**Comment by rockonedege** [comment]
I just checked again,it only appears on browsers,ie,chrome and Firefox when be hosted. It's clean without websocketd. 

more observation that may help.
- the enclosing char are almost fixed, i.e. Not random.
- the message body itself is redirected from stderr to stdout thru " 2>&1"

**Comment by rockonedege** [comment]
I got it. When the message body has its font color changed,say red or green, those char show. On a native console, it changes the color,somehow websocketd converts those extra chars.

It has one to do with stderr per se, just that error are red

I don't know how the conversion happens and the fix though. Would love to see an explanation.

**Comment by asergeyev** [comment]
Your program thinks it can print colors to terminal. And terminal emulator generally ok to show them. Problem is that websocketd is not a terminal emulator. It does not set TERM variable or does not do anything else that makes other programs run in input/output mode. But program you're running is likely built assuming that no-terminal situation never happens, therefore it dumps colors into output without checking anything. 

It could not be fixed unfortunately. This kind of behavior of the program in unix land is possible to fix by running sed (e.g. http://www.commandlinefu.com/commands/view/3584/remove-color-codes-special-characters-with-sed ) but I don't' know how to help you in windows.

I'll keep it open for another couple weeks in case if someone would have recipe for you.

**Comment by rockonedege** [comment]
Thanks， Alex.  I did some research. It's actually some standard thing known as  [ANSI escape color code](https://en.wikipedia.org/wiki/ANSI_escape_code).

Do you think it's good idea to convert, rather than remove, them to html colors inside the console template?

**Comment by asergeyev** [comment]
Not really, but quick search finds that something like this one might work: https://www.npmjs.com/package/ansi-to-html

I'm not sure though

**Comment by rockonedege** [comment]
I was referring to built-in developer console.  It might be a one line of change with regex replacing every sting received, I'll take a try later.

**Comment by asergeyev** [comment]
I'll keep this closed for now, feel free to follow up
