### ISSUE TITLE
Python script worked once and then I got (fork/exec "": no such file or directory)

### ISSUE THREAD

**Issue by maco1717** [joewalnes/websocketd#221]
Hi,

Is there a log file or any advice I could get about troubleshooting this issue?

I'm trying to run a script that sends the context of a file in and infinite loop, when that "variable changes it changes what it sends...

[this ](http://ballingt.com/nonblocking-stdin-in-python-3)is the code im using with some variations...

this is what is get when trying to connect to the server:

> Fri, 22 Jul 2016 23:48:04 +0000 | ERROR  | process    | url:'http://192.168.1.140:8000/' id:'1469231284916529497' remote:'.home.' command:'websocketd/socket' origin:'http://192.168.1.122' | Could not launch process websocketd/socket  (fork/exec websocketd/socket: no such file or directory)

> 
Fri, 22 Jul 2016 23:54:18 +0000 | ACCESS | session    | url:'http://192.168.1.140:8000/' id:'1469231658663742139' remote:'.home.' command:'websocketd/socket' origin:'http://192.168.1.122' | DISCONNECT

dont know why would it disconnect as the script if an infinite loop.

Thanks.

**Comment by asergeyev** [comment]
Could you add your command line, how you starting websocketd with that program?

**Comment by maco1717** [comment]
On that case:

> ./websocketd/websocketd --port=8000 ./websocketd/socket

I've also tried from the actual directory...

> ./websocketd --port=8000 ./socket

also tried with the devconsole, which wont work for me, tried browsing to end htt://point also adding the "path to file" at the end of the address in the browser, no luck...

> ./websocketd/websocketd --port=8000 ./websocketd/socket.py --devconsole

**Comment by asergeyev** [comment]
Hm.. Does the script itself work when you run it as ./websocketd/socket or ./websocketd/socket.py --devconsole  or  ./socket.py ?

**Comment by maco1717** [comment]
I'm using linux. The script it self and it work.

Are you saying that the dev console command would be:

`script_name --devconsole`

haven't managed to figure out how to run the devconsole...

what do you mean by adding "env -i" in front of it? on the websocketd command? could you please give me an example of how to implement this? I've tried...

command:
`pi@raspberrypi:~/websocketd $ ./websocketd --port=8000 env -i ./socket.py`

result:
```
Sun, 24 Jul 2016 01:31:55 +0000 | ACCESS | session    | url:'http://192.168.1.140:8000/' id:'1469323915905171628' remote:'.home.' command:'/usr/bin/env' origin:'http://192.168.1.122' | CONNECT
Sun, 24 Jul 2016 01:31:55 +0000 | ERROR  | stderr     | url:'http://192.168.1.140:8000/' id:'1469323915905171628' remote:'.home.' command:'/usr/bin/env' origin:'http://192.168.1.122' pid:'1246' | /usr/bin/env: ./socket.py: No such file or directory
Sun, 24 Jul 2016 01:31:55 +0000 | ACCESS | session    | url:'http://192.168.1.140:8000/' id:'1469323915905171628' remote:'.home.' command:'/usr/bin/env' origin:'http://192.168.1.122' pid:'1246' | DISCONNECT
```

also:
```
pi@raspberrypi:~/websocketd $ ./websocketd env -i --port=8000 ./socket.py
Sun, 24 Jul 2016 01:43:04 +0000 | INFO   | server     |  | Serving using application   : /usr/bin/env -i --port=8000 ./socket.py
Sun, 24 Jul 2016 01:43:04 +0000 | INFO   | server     |  | Starting WebSocket server   : ws://raspberrypi:80/
Sun, 24 Jul 2016 01:43:04 +0000 | FATAL  | server     |  | Can't start server: listen tcp :80: bind: permission denied
```

command:
`sudo python env -i socket.py`

result:
`python: can't open file 'env': [Errno 2] No such file or directory
`

also:

```
pi@raspberrypi:~/websocketd $ sudo python env -i socket.py
python: can't open file 'env': [Errno 2] No such file or directory
pi@raspberrypi:~/websocketd $ ls
bootstrap.html  count.sh  openboot.sh  socket.py  websocketd
CHANGES         LICENSE   README.md    var        websocketd-0.2.11-linux_arm.zip
pi@raspberrypi:~/websocketd $ sudo python env -i ./socket.py
python: can't open file 'env': [Errno 2] No such file or directory
```

script running:

```
pi@raspberrypi:~/websocketd $ sudo python socket.py
on
on
on
on
on
on
hello
hello
on
hello
on
on
Traceback (most recent call last):
  File "socket.py", line 41, in <module>
    time.sleep(.5)
KeyboardInterrupt
pi@raspberrypi:~/websocketd $
```

I've modified the script to print the valued in a file "variable" and print hello when a key is pressed...

edit on the original script:
```
try:
                c = sys.stdin.read(1)
                #print(repr(c))
                print("hello")
            except IOError:
                with open('var', 'r') as myfile:
                    data=myfile.read().replace('\n', '')
                    print(data)
            time.sleep(.5)
```

**Comment by asergeyev** [comment]
See, you're running your script as  sudo python socket.py, while websocket would end up running it as just  ./socket.py in example above..

You need to use command that works. So in your case it's ```websocketd [options] sudo python socket.py```...  You can potentially move sudo (I don't know why you're using it)... and you can move python to script's headline and adding executable bit to script.py permissions. But one rule always applies  "command you're using behind websocketd should work on it's own too"

**Comment by asergeyev** [comment]
And --devconsole is just one of the options, you could use it in websocketd command line before actual command.

**Comment by maco1717** [comment]
Hi,

this is just a bad habit of mine, the script runs without sudo fine...

`pi@SmartDoor:~ python websocketd/socket.py
off
off
off
Traceback (most recent call last):
  File "websocketd/socket.py", line 51, in <module>
    time.sleep(1)
KeyboardInterrupt
pi@SmartDoor:~ $
`

but still get this with websocketd...


`pi@pi:~ $ websocketd/websocketd --port=8081 websocketd/socket.py
Wed, 27 Jul 2016 11:03:35 +0100 | INFO   | server     |  | Serving using application   : websocketd/socket.py
Wed, 27 Jul 2016 11:03:35 +0100 | INFO   | server     |  | Starting WebSocket server   : ws://SmartDoor:8081/
Wed, 27 Jul 2016 11:04:27 +0100 | ACCESS | session    | url:'http://192.168.1.140:8081/' id:'1469613867249537063' remote:'.home.' command:'websocketd/socket.py' origin:'http://192.168.1.122' | CONNECT
Wed, 27 Jul 2016 11:04:27 +0100 | ERROR  | process    | url:'http://192.168.1.140:8081/' id:'1469613867249537063' remote:'.home.' command:'websocketd/socket.py' origin:'http://192.168.1.122' | Could not launch process websocketd/socket.py  (fork/exec websocketd/socket.py: no such file or directory)
Wed, 27 Jul 2016 11:04:27 +0100 | ACCESS | session    | url:'http://192.168.1.140:8081/' id:'1469613867249537063' remote:'.home.' command:'websocketd/socket.py' origin:'http://192.168.1.122' | DISCONNECT`

**Comment by asergeyev** [comment]
Again, you add "python" in first command line and decide to omit it in second one, you need

```websocketd/websocketd --port=8081 python websocketd/socket.py```

**Comment by maco1717** [comment]
Hi,

Thanks for you suggestion I haven't been able to try this, I have put this on hold for the time being. Just thought I'd get back to you on this, at the moment im implementing the "socket" on bash.

Thanks.
