### ISSUE TITLE
QUERY_STRING not passed

### ISSUE THREAD

**Issue by neusgaten** [joewalnes/websocketd#223]
Hi, 

I'd like to use the QUERY_STRING variable to determine what my program should do. However this is not passed to the program, even when i use  `--passenv=QUERY_STRING` 

For the sake of simplicity I used the count.sh script. 

```
#!/bin/bash
for ((COUNT = 1; COUNT <= 10; COUNT++)); do
  echo $COUNT
  sleep 0.5
done

NAMES="""
  QUERY_STRING
  REQUEST_URI
  UNIQUE_ID
"""

for NAME in ${NAMES}
do
        echo "${NAME}=${!NAME:-<unset>}"
done

# Additional HTTP headers
env | grep '^HTTP_'
```

Whenever the page is called I see the following in my terminal:

```
Mon, 01 Aug 2016 10:13:01 +0000 | ACCESS | http       | url:'http://webtoolkit01:8080/count.html?name=me' | STATIC
Mon, 01 Aug 2016 10:13:01 +0000 | ACCESS | session    | url:'http://webtoolkit01.ourname.lan:8080/count.sh' id:'1470046381719560579' remote:'T500-NG.ourname.lan.' command:'/home/bitnami/websocketd/count.sh' origin:'http://webtoolkit01:8080' | CONNECT
Mon, 01 Aug 2016 10:13:06 +0000 | ACCESS | session    | url:'http://webtoolkit01.ourname.lan:8080/count.sh' id:'1470046381719560579' remote:'T500-NG.ourname.lan.' command:'/home/bitnami/websocketd/count.sh' origin:'http://webtoolkit01:8080' pid:'13633' | DISCONNECT
```
So `?name=me` is passed to the server. 

However, the output of count.sh, printed in my webbrowser:

```
CONNECT
NUMBER: 1
NUMBER: 2
...
NUMBER: QUERY_STRING=<unset>
NUMBER: REQUEST_URI=/count.sh
NUMBER: UNIQUE_ID=1470046381719560579
DISCONNECT
```

I start websocketd using:
`./websocketd/websocketd --port=8080 --dir=/home/bitnami/websocketd --staticdir /home/bitnami/websocketd/pages --passenv=QUERY_STRING &`

I might be doing something wrong, if so, please let me know.

**Comment by asergeyev** [comment]
Use of passenv tells websocketd to force use of your environment.  You need to try without passenv to see QUERY_STRING var to work (passenv in your case works like destroyer of values read from Request URL)

**Comment by neusgaten** [comment]
When I start websocketd with the next command, I can see the QUERY_STRING:
./websocketd/websocketd --port=8080 --dir=/home/bitnami/websocketd --passenv=QUERY_STRING --devconsole &

**Comment by neusgaten** [comment]
Found it, the passing from within javascript to websocketd was not properly done.

Sorry for the inconvenience.
