### ISSUE TITLE
Sharing data between websockets

### ISSUE THREAD

**Issue by Archina** [joewalnes/websocketd#224]
Hello!

I have to say this is a very nice project and just started to fiddle around with it. Yet I feel like there is a quite important part missing.

Maybe I did overlook something or understood things wrong but is it possible to share data between the processes that are created per WebSocket connection? I have seen that there has already been a discussion about this in #50 and #95, but for all I know efforts into that direction have been dropped.

My suggestion would be the solution to implement two processes. One that will be spawned for every WebSocket connection and one that is spawned for the whole lifetime of the WebSocket port. Let's call WebSocket connection processes children and the lifetime process as a parent. Then we could have these children interact with shared data through pipes to their parent.

I tried working around this with my python scripts but searching out IDs of running processes sounds rather ambiguous.

Would that be at all be a feasible solution? If not I would be very happy to find a hint into the right direction. This may also be very interesting for the documentation and help people understand this already powerful tool.

Thank you for your effort.

**Comment by blondie101010** [comment]
The solution I use is to have all the connector processes open a bidirectional channel (fifo) to a dispatcher which does exactly what you're talking about.

Making it generic implies building a whole API or framework, which is (at least currently) way beyond the scope of the project.
