### ISSUE TITLE
build instructions under windows

### ISSUE THREAD

**Issue by rockonedege** [joewalnes/websocketd#225]
I did some search but could not found a script file or tutorial on how to build on Windows. Did I miss any place?

**Comment by asergeyev** [comment]
Ok, if you have go installed you'd need to just do "go get github.com/joewalnes/websocketd/libwebsocketd" and then in websocketd dir "go build -o websocketd.exe *.go"  

You can build on other platforms too using GOOS=windows env. variable.

**Comment by asergeyev** [comment]
Sorry for not answering for long and closing now but I don't think this issue needs to be kept active.
Feel free to continue here, I'll get better instructions.

Note that we have unresolved issue with SSL on windows.
