### ISSUE TITLE
unable to run websocketd on Ubuntu 14.04

### ISSUE THREAD

**Issue by jonmalave** [joewalnes/websocketd#227]
I extracted the websocketd-0.2.11-linux_amd64.zip onto my Ubuntu 14.04 server. Checked that the websocketd file was executable, it is when I check permissions with ll command. Although when I try to execute websocketd nothing happens. I am provided with "bash: .: websocketd: cannot execute binary file" error.  

Please advise.

**Comment by asergeyev** [comment]
1) could you post result of your "uname -a" command?
2) Why do you use 0.2.11, not 0.2.12?
3) I could not repeat that on my 12.4 but who knows if there is special things about 14.4.. so I'd appreciate comments

**Comment by jonmalave** [comment]
1) Linux jvm-1 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
2) I used 0.2.11 because that was the version I was linked to through the website's download section under linux 64-bit version. I missed the download link here on Github, although the website should also be updated. 
3) I'll try 0.2.12 and reply with results...

**Comment by jonmalave** [comment]
@asergeyev I just tried the latest version, and still same issue. I'm hosting on Digital Ocean. Not sure if that is a factor, but shouldn't be. Maybe it's the way i'm trying to execute it? Shouldn't I be able to just extract the executable and in command link type " . websocketd " to execute it? Or am I doing this all wrong and i'm an ultra noob? lol

**Comment by asergeyev** [comment]
Oh, no, this is program, not bash script so you should do ./websocket

**Comment by jonmalave** [comment]
@asergeyev thanks for clearing this up... sorry for the trouble! I mostly use Linux to run LAMP server, and haven't ever used the ./ command to launch executable. You learn something new everyday! Thank you sir!

**Comment by asergeyev** [comment]
Done with this discussion I think.
