### ISSUE TITLE
how to rely messages to multiple clients via PHP?

### ISSUE THREAD

**Issue by jonmalave** [joewalnes/websocketd#228]
Forgive me for asking this question if this is not considered an issue.... I ask because I think it's an issue that there is not enough good examples or documentation of how to properly use Websocketd for relying messages.  I would think this is one of the primary purposes of Websockets to begin with, relying messages send / receive in real-time.

I was able to get the example PHP demo to work, but it's not very helpful for me because I really want to use Websocketd to push and receive messages. Again I have to share I was able to accomplish this using Pusher in a matter of minutes. I apologize for the on going comparison, but I read online that Websocketd was a good alternative to a Websocket hosted service like Pusher. But still I keep hitting a wall... 

There is alot of work to be done to make Websocketd a real alternative to something like Pusher. So far I have found Websocketd very frustrating to use going on day two. Maybe this was not designed for users like myself who are looking for a more turnkey like solution. But when I read Websocketd is an alternative, I expect some similar usability, but that's far from the case.

Sorry for venting... you can close this ticket if you like and just ignore my rant. 

I really wanted to consider Websocketd as a real alternative to Pusher, but this is just frustrating...

**Comment by asergeyev** [comment]
I think we covered this in multiple tickets before. Websocketd is special program for converting STDIO programs to Websocket endpoints. Just pushing same output to multiple clients is for other tools and may be for other types of endpoints.
