### ISSUE TITLE
crashes randomly under OSX

### ISSUE THREAD

**Issue by jbardu** [joewalnes/websocketd#229]
I'm exploring speed limits under various browsers etc and can't seem to
find stability under load.

Here it crashes soon after handling 400 megabit of incoming messages.
Each message is less than 1mb, and the sender is not letting too many
pile up before throttling. Sometimes websocketd lasts for a while other
times it crashes out with what looks like a random signal error.

The child process is just a perl script that sysreads after select on STDIN
it functions ok.

Doesn't matter what browser: both Safari and Chrome can send fast
enough to crash websocketd in this way. Tried two OSX machines to
run websocketd a macbook (127.0.0.1) and an iMac (remote IP) and
both crash.

fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x6dae0c58d38c pc=0x153eb]

runtime stack:
runtime.throw(0x497fa0, 0x2a)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/panic.go:530 +0x90
runtime.sigpanic()
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x619880)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(_mheap).freeSpan.func1()
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/mheap.go:726 +0x186
runtime.systemstack(0xc820035d70)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(_mheap).freeSpan(0x619880, 0x6a6480, 0x1)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/mheap.go:727 +0x44
runtime.(*mspan).sweep(0x6a6480, 0x2c9b00002c00, 0x200000001)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/mgcsweep.go:342 +0x6ef
runtime.sweepone(0x39632)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/mgcsweep.go:112 +0x23e
runtime.gosweepone.func1()
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/mgcsweep.go:124 +0x21
runtime.systemstack(0xc820016000)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/proc.go:1048

goroutine 3 [running]:
runtime.systemstack_switch()
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/asm_amd64.s:245 fp=0xc820022f58 sp=0xc820022f50
runtime.gosweepone(0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/mgcsweep.go:125 +0x3d fp=0xc820022f80 sp=0xc820022f58
runtime.bgsweep(0xc82004a000)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/mgcsweep.go:66 +0xb6 fp=0xc820022fb8 sp=0xc820022f80
runtime.goexit()
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820022fc0 sp=0xc820022fb8
created by runtime.gcenable
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/mgc.go:191 +0x53

goroutine 1 [chan receive, 2 minutes]:
main.main()
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/main.go:88 +0xb7e

goroutine 5 [IO wait]:
net.runtime_pollWait(0x6f48c8, 0x72, 0x6ef050)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/netpoll.go:160 +0x60
net.(_pollDesc).Wait(0xc82004a450, 0x72, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(_pollDesc).WaitRead(0xc82004a450, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/net/fd_poll_runtime.go:78 +0x36
net.(_netFD).accept(0xc82004a3f0, 0x0, 0x6f49c0, 0xc820010300)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/net/fd_unix.go:426 +0x27c
net.(_TCPListener).AcceptTCP(0xc820026030, 0x573e0, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820026030, 0x0, 0x0, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/net/http/server.go:2427 +0x41
net/http.(_Server).Serve(0xc820070180, 0x6f4988, 0xc820026030, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/net/http/server.go:2117 +0x129
net/http.(_Server).ListenAndServe(0xc820070180, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/net/http/server.go:2098 +0x136
net/http.ListenAndServe(0xc82000f140, 0x5, 0x0, 0x0, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/net/http/server.go:2195 +0x98
main.main.func1(0xc820012500, 0xc820054300, 0xc82000f140, 0x5)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/main.go:83 +0xd9
created by main.main
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/main.go:85 +0xb10

goroutine 11 [select]:
github.com/joewalnes/websocketd/libwebsocketd.PipeEndpoints(0x72f360, 0xc8200af580, 0x72f3a0, 0xc8200af5a0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-path/src/github.com/joewalnes/websocketd/libwebsocketd/endpoint.go:22 +0x2ea
github.com/joewalnes/websocketd/libwebsocketd.(_WebsocketdHandler).accept(0xc820012690, 0xc8200fe2d0, 0xc82000ba40)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-path/src/github.com/joewalnes/websocketd/libwebsocketd/handler.go:85 +0x77a
github.com/joewalnes/websocketd/libwebsocketd.(_WebsocketdHandler).wshandler.func1(0xc8200fe2d0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-path/src/github.com/joewalnes/websocketd/libwebsocketd/handler.go:63 +0x33
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc8200af060, ...)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-path/src/golang.org/x/net/websocket/server.go:89 +0x2d2
golang.org/x/net/websocket.Server.ServeHTTP(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc8200af060, ...)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-path/src/golang.org/x/net/websocket/server.go:70 +0x4e
github.com/joewalnes/websocketd/libwebsocketd.(_WebsocketdServer).ServeHTTP(0xc8200ae940, 0x72f058, 0xc8200560d0, 0xc8200bc1c0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-path/src/github.com/joewalnes/websocketd/libwebsocketd/http.go:112 +0x18a4
net/http.(_ServeMux).ServeHTTP(0xc820014ab0, 0x72f058, 0xc8200560d0, 0xc8200bc1c0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820070180, 0x72f058, 0xc8200560d0, 0xc8200bc1c0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/net/http/server.go:2081 +0x19e
net/http.(_conn).serve(0xc8200c0300)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(_Server).Serve
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/net/http/server.go:2137 +0x44e

goroutine 22 [syscall]:
syscall.Syscall(0x3, 0x8, 0xc8200e4000, 0x1000, 0x0, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x8, 0xc8200e4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0x8, 0xc8200e4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/syscall/syscall_unix.go:161 +0x4d
os.(_File).read(0xc8200dc058, 0xc8200e4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/os/file_unix.go:228 +0x75
os.(_File).Read(0xc8200dc058, 0xc8200e4000, 0x1000, 0x1000, 0xf700000000, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/os/file.go:95 +0x8a
bufio.(_Reader).fill(0xc82001ff00)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/bufio/bufio.go:97 +0x1e9
bufio.(_Reader).ReadSlice(0xc82001ff00, 0xc82001ff0a, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/bufio/bufio.go:328 +0x21a
github.com/joewalnes/websocketd/libwebsocketd.(_ProcessEndpoint).log_stderr(0xc8200af580)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-path/src/github.com/joewalnes/websocketd/libwebsocketd/process_endpoint.go:143 +0xfe
created by github.com/joewalnes/websocketd/libwebsocketd.(_ProcessEndpoint).StartReading
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-path/src/github.com/joewalnes/websocketd/libwebsocketd/process_endpoint.go:98 +0x35

goroutine 23 [syscall]:
syscall.Syscall(0x3, 0x6, 0xc820124000, 0x1000, 0x1b, 0x0, 0x21ba3)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x6, 0xc820124000, 0x1000, 0x1000, 0x1b, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0x6, 0xc820124000, 0x1000, 0x1000, 0x1b, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/syscall/syscall_unix.go:161 +0x4d
os.(_File).read(0xc8200dc048, 0xc820124000, 0x1000, 0x1000, 0x1b, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/os/file_unix.go:228 +0x75
os.(_File).Read(0xc8200dc048, 0xc820124000, 0x1000, 0x1000, 0x1b, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/os/file.go:95 +0x8a
bufio.(_Reader).fill(0xc820043ef0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/bufio/bufio.go:97 +0x1e9
bufio.(_Reader).ReadSlice(0xc820043ef0, 0x33e0a, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/bufio/bufio.go:328 +0x21a
bufio.(_Reader).ReadBytes(0xc820043ef0, 0xc8200d030a, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/bufio/bufio.go:406 +0xa9
github.com/joewalnes/websocketd/libwebsocketd.(_ProcessEndpoint).process_txtout(0xc8200af580)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-path/src/github.com/joewalnes/websocketd/libwebsocketd/process_endpoint.go:109 +0xfe
created by github.com/joewalnes/websocketd/libwebsocketd.(*ProcessEndpoint).StartReading
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-path/src/github.com/joewalnes/websocketd/libwebsocketd/process_endpoint.go:102 +0x82

goroutine 24 [running]:
    goroutine running on other thread; stack unavailable
created by github.com/joewalnes/websocketd/libwebsocketd.(*WebSocketEndpoint).StartReading
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-path/src/github.com/joewalnes/websocketd/libwebsocketd/websocket_endpoint.go:56 +0x60
[signal 0xb code=0x1 addr=0x6dae0c58d38c pc=0x153eb]

runtime stack:
runtime.throw(0x497fa0, 0x2a)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/panic.go:530 +0x90
runtime.sigpanic()
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x619880)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(_mheap).reclaimList(0x619880, 0x61a118, 0x1, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/mheap.go:345 +0xd7
runtime.(_mheap).reclaim(0x619880, 0x1)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/mheap.go:374 +0x6b
runtime.(_mheap).alloc_m(0x619880, 0x1, 0x23, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/mheap.go:428 +0x96
runtime.(_mheap).alloc.func1()
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc8204f5e58)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(_mheap).alloc(0x619880, 0x1, 0x10000000023, 0x1508f)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/mheap.go:503 +0x63
runtime.(_mcentral).grow(0x61baa0, 0x0)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/mcentral.go:209 +0x93
runtime.(_mcentral).cacheSpan(0x61baa0, 0xc8200c6510)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/mcentral.go:89 +0x47d
runtime.(_mcache).refill(0x69f960, 0xc800000023, 0xc820047c10)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc820016000)
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
    /home/asergeyev/go/src/github.com/joewalnes/websocketd/release/go-local/1.6/go/src/runtime/proc.go:1048

**Comment by jbardu** [comment]
Just for the general performance information.

Running websocketd reading 1mb messages at 600 megabit/second splits cpu usage on a 2 core intel 3.1ghz i7, about evenly with a browser (Chrome), accessing 127.0.0.1.
So the cpu is divided between the two, and fully used at this speed, it as fast as I can get it working. 

Adding additional web sockets just spreads the bandwidth without adding anything to the total.
The end-point run by websocketd is just issuing sysread()s and is using almost no cpu.

If websocketd is moved to a server, the browser has extra cpu and can go a bit faster along with websocketd too, the maximum goes up towards 1000 megabit/second.

Either way it crashes with the unexpected signal error after a random amount of time.

**Comment by asergeyev** [comment]
Any chance you can try to compile it natively under mac and go 1.7 and see if it's not a problem anymore?

**Comment by asergeyev** [comment]
Any news on this? Did you test it with 1.7? Do you have any way to replicate this problem with a script?

**Comment by asergeyev** [comment]
I'll close, it's been few months now..
