### ISSUE TITLE
reverselookup should default to false

### ISSUE THREAD

**Issue by jbardu** [joewalnes/websocketd#230]
I think reverse lookup for the purpose of logging should always default to false..
this is standard for web servers for some time because a random IP is often not going
to have a fast reverse lookup and could be denied service(?) while the DNS lookup happens.

Unless logging somehow is avoiding slow reverse lookups. But then you're potentially
stalling logging so that would be bad  as well..

**Comment by asergeyev** [comment]
I agree PR? :)

**Comment by asergeyev** [comment]
Did it from browser in downtime... this was reason for odd number of commits....
