### ISSUE TITLE
Binary data between websockets

### ISSUE THREAD

**Issue by tiandiwuyou** [joewalnes/websocketd#232]
Hello!
I'm trying to send binary data from a server end to a chrome browser. I've set this 
ws.binayType = "arraybuffer"
However chrome gives a error message below.
"WebSocket connection to 'ws://192.168.1.101:8080/' failed: Could not decode a text frame as UTF-8." 
Would it be caused by inappropriate opcode websocketd server sent? How can i solve this?
Thank you.

**Comment by tiandiwuyou** [comment]
Sorry, just find that there's an "binay" option to enable it.

**Comment by tiandiwuyou** [comment]
Sorry, just found that there's an "binary" command option.

**Comment by asergeyev** [comment]
Did it work for you?
