### ISSUE TITLE
i have some issues with the websocketd --dir option

### ISSUE THREAD

**Issue by Botnary** [joewalnes/websocketd#233]
```
websocketd 
          --port=8118 
          --ssl --sslcert="ssl.cert" 
          --sslkey="ssl.key" 
          --dir="/scripts"
```
if i connect like this
```
var wss = new WebSocket('wss://localhost:8118/scripts/event.sh');
```
it works, but if i try to use sub directories 
```
var wss = new WebSocket('wss://localhost:8118/scripts/dir1/event.sh');
```
i get this error:
```
Could not launch process /scripts/dir1/event.sh(fork/exec /scripts/dir1/event.sh: no such file or directory)
```
The file exists and is executable.
Is this some kind of issue ? Or it was intended not to support sub categories?
Thanks.

**Comment by Botnary** [comment]
Looks like when
```
#!/bin/program -- is missing or wrong path
```
websocketd throws the same error: no such file or directory

**Comment by mattgodbolt** [comment]
As does `bash` and any other shell/interpreter. This is a linux shortcoming, unfortunately.

**Comment by Botnary** [comment]
Yes i understand that, that's why closed the issue, because it is not related to websocketd.
