### ISSUE TITLE
runtime error linux 32bit

### ISSUE THREAD

**Issue by maxime-schuck** [joewalnes/websocketd#236]
Hi,

I downloaded your 32 bit version of websocketd for linux and its a pleasure to use it.
So i made a little bash script for a messaging application.

I start websocketd via systemctl, so my service file start the application like this:
ExecStart=/path/to/websocketd --port=8080 /path/to/myscript.sh

I opened my port 8080 and made an html page to use it.

Well a night later, i see the journal log of systemctl to check the service and here is the log,
a connected user (certainly a bot) and many other, but i see a runtime error, what does it mean?  
note: i just want to know if it can rise to a security problem, thanks

Nov 27 16:48:59 myname websocketd[1344]: 2016/11/27 16:48:59 http: panic serving 46.174.191.29:33652: runtime error: index out of range
Nov 27 16:48:59 myname websocketd[1344]: goroutine 81 [running]:
Nov 27 16:48:59 myname websocketd[1344]: net/http.func·011()
Nov 27 16:48:59 myname websocketd[1344]: /u/go/src/github.com/joewalnes/websocketd/release/go-local/1.4.2/go/src/net/http/server.go:1130 +0xa8
Nov 27 16:48:59 myname websocketd[1344]: github.com/joewalnes/websocketd/libwebsocketd.(*WebsocketdServer).TellURL(0x18636570, 0x82cf3d8, 0x4, 0x0, 0x0, 0x18636644, 0x1, 0x0, 0x0)
Nov 27 16:48:59 myname websocketd[1344]: /u/go/src/github.com/joewalnes/websocketd/release/go-path/src/github.com/joewalnes/websocketd/libwebsocketd/http.go:182 +0x1ac
Nov 27 16:48:59 myname websocketd[1344]: github.com/joewalnes/websocketd/libwebsocketd.(*WebsocketdServer).ServeHTTP(0x18636570, 0xb76d8170, 0x1863c5b0, 0x1863c540)
Nov 27 16:48:59 myname websocketd[1344]: /u/go/src/github.com/joewalnes/websocketd/release/go-path/src/github.com/joewalnes/websocketd/libwebsocketd/http.go:84 +0x19f
Nov 27 16:48:59 myname websocketd[1344]: net/http.(*ServeMux).ServeHTTP(0x1860a5a0, 0xb76d8170, 0x1863c5b0, 0x1863c540)
Nov 27 16:48:59 myname websocketd[1344]: /u/go/src/github.com/joewalnes/websocketd/release/go-local/1.4.2/go/src/net/http/server.go:1541 +0x126
Nov 27 16:48:59 myname websocketd[1344]: net/http.serverHandler.ServeHTTP(0x1863a340, 0xb76d8170, 0x1863c5b0, 0x1863c540)
Nov 27 16:48:59 myname websocketd[1344]: /u/go/src/github.com/joewalnes/websocketd/release/go-local/1.4.2/go/src/net/http/server.go:1703 +0x145
Nov 27 16:48:59 myname websocketd[1344]: net/http.(*conn).serve(0x1863e120)
Nov 27 16:48:59 myname websocketd[1344]: /u/go/src/github.com/joewalnes/websocketd/release/go-local/1.4.2/go/src/net/http/server.go:1204 +0x9d8
Nov 27 16:48:59 myname websocketd[1344]: created by net/http.(*Server).Serve
Nov 27 16:48:59 myname websocketd[1344]: /u/go/src/github.com/joewalnes/websocketd/release/go-local/1.4.2/go/src/net/http/server.go:1751 +0x2ce

**Comment by asergeyev** [comment]
(*WebsocketdServer).TellURL(0x18636570, 0x82cf3d8, 0x4, 0x0, 0x0, 0x18636644, 0x1, 0x0, 0x0)

this is what I think is most important and really should never happen... Are you sure websocketd is not out of memory at that time?

Can you send me that trace as TXT file since some pieces are trimmed in your post?

Can you compile websocketd yourself with go1.7 and see if it crashes?

**Comment by maxime-schuck** [comment]
1) out of memory : 
i dont know if it is the case, how can i check if websocketd is out of memory ??

2) trace:
i pasted a part of the trace , the rest give same result , with other ip as caller ( i did not keep the file, sorry...)

3) compile with go
i will try it

**Comment by asergeyev** [comment]
I'll close.... feel free to keep commenting here.
