### ISSUE TITLE
question:  how to I set environment variables 

### ISSUE THREAD

**Issue by logicminds** [joewalnes/websocketd#239]
When I install my gem and then start websocketd it cannot find the gems that were just installed because they are not part of the default gem path.

I suppose that when websocketd executes the command it does so in a shell that has minimal environment settings and does not inherit from the parent shell.

So in order to get my program to work I have to wrap everything in a script and then execute the script with wegsocketd.

My question is how can I set environment variables for websocketd to use without the wrapper script?

`websocketd --port 5003 --devconsole wrapper_script.sh`
wrapper script
```
export GEM_PATH=/usr/local/bundle:/root/.gem/ruby/2.3.0:/usr/local/lib/ruby/gems/2.3.0
puppet debugger

```

Normal gem env (GEM PATH)
```
RubyGems Environment:
  - GEM PATHS:
     - /usr/local/bundle
     - /root/.gem/ruby/2.3.0
     - /usr/local/lib/ruby/gems/2.3.0
```

Websocketd GEM PATH  (captured from devconsole)

```
  - GEM PATHS: 
     - /usr/local/lib/ruby/gems/2.3.0 
     - /.gem/ruby/2.3.0 


```

**Comment by logicminds** [comment]
I found this  but I am not sure what it does or how exactly to use it.

```
--passenv VAR[,VAR...]         Lists environment variables allowed to be
                                 passed to executed scripts.
```

**Comment by asergeyev** [comment]
if you have this one:

```export GEM_PATH=/usr/local/bundle:/root/.gem/ruby/2.3.0:/usr/local/lib/ruby/gems/2.3.0```

You should be all set to use --passenv GEM_PATH

If you have bash in your system, you can experiment with :

```env GEM_PATH=testgempath websocketd --devconsole --port 8080 --passenv GEM_PATH bash -c 'echo gem_path var is `$GEM_PATH`'```

**Comment by evaisse** [comment]
Does that come from the latest release, because I can't reproduce the behavior

**Comment by asergeyev** [comment]
passenv is from 0.2.9, may have some quirks until 0.2.11

**Comment by logicminds** [comment]
I did get this to work passing in all the variables I wanted to use.
