### ISSUE TITLE
Problem when create websocket using ip address instead of "localhost" or "hostname" ?

### ISSUE THREAD

**Issue by buidanhquy** [joewalnes/websocketd#244]
With internet access, there isn't any problem, smooth and efficient.
Without internet access, when using IP address instead of "localhost" or "hostname" to create websocket ( _new WebSocket('ws://192.168.2.50:8080')_ ) , I have to wait a few seconds until the websocketd console print the output. 
As the output, the connection is CONNECT but then DISCONNECT immediately.

./websocket --loglevel=debug --port=8080 --staticdir=. ./whatever.sh 
Fri, 06 Jan 2017 15:45:25 +0700 | INFO   | server     |  | Serving using application   : ./whatever.sh 
Fri, 06 Jan 2017 15:45:25 +0700 | INFO   | server     |  | Serving static content from : .
Fri, 06 Jan 2017 15:45:25 +0700 | INFO   | server     |  | Starting WebSocket server   : ws://ubuntu:8080/
Fri, 06 Jan 2017 15:45:25 +0700 | INFO   | server     |  | Serving CGI or static files : http://ubuntu:8080/

Fri, 06 Jan 2017 15:45:27 +0700 | ACCESS | http       | url:'http://192.168.2.50:8080/count.html' | STATIC

Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: SERVER_SOFTWARE=websocketd/DEVBUILD (go1.4 linux-amd64) --
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Parent envvar: PATH=/home/ubuntu/Qt5.7.0/5.7/gcc_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/bin:/home/ubuntu/workspace/cross-arm-2010q1/bin
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: REMOTE_ADDR=192.168.2.50
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: REMOTE_HOST=192.168.2.50
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: SERVER_NAME=192.168.2.50
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: SERVER_PORT=8080
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: SERVER_PROTOCOL=HTTP/1.1
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: GATEWAY_INTERFACE=websocketd-CGI/0.1
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: REQUEST_METHOD=GET
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: SCRIPT_NAME=/
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: PATH_INFO=/
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: PATH_TRANSLATED=/
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: QUERY_STRING=
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: AUTH_TYPE=
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: CONTENT_LENGTH=
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: CONTENT_TYPE=
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: REMOTE_IDENT=
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: REMOTE_USER=
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: UNIQUE_ID=1483692334485300915
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: REMOTE_PORT=49500
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Std. variable: REQUEST_URI=/
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Header variable HTTP_SEC_WEBSOCKET_KEY=p0npal6NdSPlWoEdq92WdA==
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Header variable HTTP_CONNECTION=keep-alive, Upgrade
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Header variable HTTP_UPGRADE=websocket
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Header variable HTTP_ACCEPT_ENCODING=gzip, deflate
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Header variable HTTP_SEC_WEBSOCKET_VERSION=13
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Header variable HTTP_ACCEPT=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Header variable HTTP_ACCEPT_LANGUAGE=en-US,en;q=0.5
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Header variable HTTP_ORIGIN=http://192.168.2.50:8080
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Header variable HTTP_COOKIE=user=
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Header variable HTTP_PRAGMA=no-cache
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Header variable HTTP_CACHE_CONTROL=no-cache
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | env        | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' | Header variable HTTP_USER_AGENT=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0
Fri, 06 Jan 2017 15:45:54 +0700 | ACCESS | session    | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' origin:'http://192.168.2.50:8080' | CONNECT
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | websocket  | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' origin:'http://192.168.2.50:8080' pid:'9678' | Cannot receive: read tcp 192.168.2.50:49500: connection reset by peer
Fri, 06 Jan 2017 15:45:54 +0700 | DEBUG  | process    | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' origin:'http://192.168.2.50:8080' pid:'9678' | Process 9678 terminated after SIGTERM
Fri, 06 Jan 2017 15:45:54 +0700 | ACCESS | session    | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' origin:'http://192.168.2.50:8080' pid:'9678' | DISCONNECT
Fri, 06 Jan 2017 15:45:55 +0700 | DEBUG  | process    | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' origin:'http://192.168.2.50:8080' pid:'9678' | Process STDOUT closed
Fri, 06 Jan 2017 15:45:55 +0700 | DEBUG  | process    | url:'http://192.168.2.50:8080/' id:'1483692334485300915' remote:'192.168.2.50' command:'./whatever.sh' origin:'http://192.168.2.50:8080' pid:'9678' | Process STDERR closed

Please advise. Thank you.

**Comment by asergeyev** [comment]
I'm not really sure I understand problem you're having. I'm mostly confused since when you don't have internet access and your computer is not connected to any network you (normally) would not have an IP address.

**Comment by asergeyev** [comment]
I'm closing this one, feel free to get back and clarify your question.
