### ISSUE TITLE
How do I do ws.send directed to different scripts?

### ISSUE THREAD

**Issue by sandeepbl** [joewalnes/websocketd#245]
I know there is an option to serve an entire directory of scripts with the --dir=DIR option. 

I am using python as my server program. Can you please tell me how I could direct the ws.send from the JavaScript in the HTML client?

Thanks,

**Comment by asergeyev** [comment]
You get something like this eventually:

```const u1 = "ws://....", u2 = "ws://...";
let ws1 = WebSocket(u1), ws2 = WebSocket(u2); 
ws1.onmessage = function() { ... };
ws2.onmessage = function() { ... };
```

You can have same handlers or same URL but idea is to create multiple websocket objects with each of them associated with it's own TCP connection.

**Comment by asergeyev** [comment]
I think this one is safe to close.

**Comment by sandeepbl** [comment]
it still doesn't tell me how !!!

i can have multiple instances of websocketd running with different URIs but ***how do I*** run one websocketd instance and serve the whole directory with dir=DIR option and ***then*** how do I redirect requests to specific scripts?
