### ISSUE TITLE
Custom path for websocket URL

### ISSUE THREAD

**Issue by Aamir010** [joewalnes/websocketd#246]
Hello,
Can you please help me how do I create custom path of WS url's. I have 10 script which I need to run via WebSocket so instead opening 10 port on our firewall I just wants to add single port and launch specific script via custom URL say url:'http://localhost:8080/task-1/', url:'http://localhost:8080/task-2/' and so on

**Comment by asergeyev** [comment]
Put them all to same folder (or put small bash scripts that call your scripts in same folder) and use that with websocket as  ```--dir /path/to/folder```   every file inside folder becomes URL ```ws://host.name.tld/yourfilename``` (+ .extension if you have one) ... You can use symlinks too.

To get closer to your question, you can have --dir with "task-1" script and "task-2" scripts in it.. then you can use URLs you wrote above... Final slash should not be a problem.

**Comment by Aamir010** [comment]
Thank you so much for your response, I will try in a while and update you with the status.
