### ISSUE TITLE
how to pass parameter to script

### ISSUE THREAD

**Issue by sandeepbl** [joewalnes/websocketd#247]
Hi Guys,

Can someone tell me how I can pass a parameter (string) from the URI to the script that I run ?

I am running  a python script with websocketd

Thanks

**Comment by sandeepbl** [comment]
**Got the solution** from the example code :+1: 

I used the below python code to get the query string in the URI:

> `os.environ.get('QUERY_STRING', '<unset>')`

Thanks

**Comment by sandeepbl** [comment]
will leave it open in case other people have the same question

**Comment by underscoredam** [comment]
I created a gist to solve exactly this. 

https://gist.github.com/underscoredam/d695bda974eaa6dee4b4d37db118af33
