### ISSUE TITLE
Apache & c

### ISSUE THREAD

**Issue by sparx104** [joewalnes/websocketd#248]
First, thanks for this tool!

After some experimenting, I've got a sample application written in c (echos back what it's sent) and instructions for connecting to websocketd via Apache's modproxy_wstunnel.

If you want them, do I send them to someone or shall I add them to the Wiki myself?

Cheers
Chris

**Comment by asergeyev** [comment]
It's totally fine if you add wiki page describing your problem and solution. Thanks!

**Comment by asergeyev** [comment]
Let me know if I should change permissions for that. Not sure how it works.
