### ISSUE TITLE
Less strict parameter parsing.

### ISSUE THREAD

**Issue by bradennapier** [joewalnes/websocketd#250]
Run into the situation where the parameters are fairly strict for parsing.  For example, executing from a lanaguage and surrounding the path with quotes `--staticdir="/path/to/file"` ended in "can not access `'"/path/to/file"'` - it would make sense to me that this should be checked and understood.  I'm guessing it's expecting `--staticdir='path/to/file' ` which is not standdard in the language I am using.  Simple enough fix, just a thought.  I would use no quotes but this has spaces in it.

**Comment by asergeyev** [comment]
Any chance you can write it and send PR? :)

**Comment by dolmen** [comment]
I suspect this is a platform specific issue (Windows).
The workaround here is to put the double quotes around the whole parameter: `"--staticdir=/path/to/file"`

**Comment by asergeyev** [comment]
Interesting solution, thanks!
