### ISSUE TITLE
Global Path

### ISSUE THREAD

**Issue by bradennapier** [joewalnes/websocketd#251]
With my app I use a router and single page design and I want to also connect a websocket to it.  Would need a way to route ALL paths in a directory to a single endpoint for the webserver to accomplish this. 

aka /home /hi /whatever/i/need /ok/then would all route to the same place then the javascript can handle the path using the location value.  Is this possible?

With express its something like

```
app.get('*', function(req, res) {
  res.sendFile(path.join(__dirname, 'src/index.html'))
})
```

**Comment by asergeyev** [comment]
It's not super efficient to use websocketd as HTTPserver for plain files.

It's definitely your choice to make but I'd suggest using websocketd only for websocket communicatoin and run it on different port than your HTTP server.

Alternatively you could use proxying to websocketd running on localhost interface using your webserver (nginx, apache, etc)

**Comment by bradennapier** [comment]
I would understand that for a true HTTP server, this is one that will almost never have more than a single client connected so its nice to have it all in a single binary on an embedded system.  Is it far slower and more resource intensive or something?

The global thing is mostly just about convenience in that regard.

**Comment by asergeyev** [comment]
Sorry. Long delay looking here... 

You want any path lead to same endpoint?  You can just run websocketd with single command but if you want combination of static files and bunch of other URLs go to websocks  it's not implemented unfortunately.  I can give you advise on how it'll look to patch our routing if you interested in coding.
