### ISSUE TITLE
No binding on ipv4

### ISSUE THREAD

**Issue by froiloc** [joewalnes/websocketd#252]
Hi,

though I use the parameter --address=0.0.0.0 on Linux Ubuntu 16.04 64-bit it does not bind to ipv4. When I use netstat to show the ports opened it only shows tcp6 for the assigned port. And I cannot access it using the ipv4 address.

What could be the issue and how can I solve it? Help ist appreciated.

Thank you very much.

**Comment by asergeyev** [comment]
Since you closed it I hope it's resolved.

**Comment by froiloc** [comment]
It is, thanks for asking. Great help your program. Thank you very much.

Greetings Alex

2017-03-27 22:43 GMT+02:00 Alex Sergeyev <notifications@github.com>:
