### ISSUE TITLE
How to disconnect websocket when the Google Chrome page is refreshed

### ISSUE THREAD

**Issue by liuxg123** [joewalnes/websocketd#253]
I meet a problem, websocket still connect when the Browser's page is refreshed.
Here's my code.
`
package com.cloudfoundry.websocket;

import java.io.IOException;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import javax.websocket.OnClose;
import javax.websocket.OnError;
import javax.websocket.OnMessage;
import javax.websocket.OnOpen;
import javax.websocket.Session;
import javax.websocket.server.PathParam;
import javax.websocket.server.ServerEndpoint;

import com.cloudfoundry.dao.LogsDao;
import com.cloudfoundry.utils.SpringContextUtils;

@ServerEndpoint("/websocket/{token}/{applicationId}")
public class WebSocketLogs {

	LogsDao logsDao = (LogsDao) SpringContextUtils.getApplicationContext().getBean("logsDao");

	private Map<String, Session> sessionMap = new ConcurrentHashMap<>();//save session
	
	@OnOpen
	public void onOpen(@PathParam("token") String token,@PathParam("applicationId") String applicationId,Session session) {
		sessionMap.put(token+applicationId, session);
		System.out.println("======================"+sessionMap.get(token+applicationId).getId());
		try {
			logsDao.stream(token, sessionMap.get(token+applicationId), applicationId);
		} catch (Throwable e) {
			e.printStackTrace();
		}
		System.out.println("Client connected  "+token);
	}

	 /**
     * disconnect method
     */
    @OnClose
    public void onClose(@PathParam("token") String token,@PathParam("applicationId") String applicationId,Session session)throws IOException{
    	if(sessionMap.get(token+applicationId).isOpen()){
    		sessionMap.get(token+applicationId).close();
    	}
    	sessionMap.remove(token+applicationId, session);
        System.out.println("Connection closed");
    }
	@OnMessage
	public void onMessage(@PathParam("token") String token,@PathParam("applicationId") String applicationId,String message) {
		try {
			sessionMap.get(token+applicationId).getBasicRemote().sendText(message);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	@OnError
	public void onError(Session session, Throwable error) {
		System.out.println("发生错误");
		error.printStackTrace();
	}
}
`
AnjularJs code:
`vm.socket;
	
	// getLog function
	var getLog = function() {
		var socketPath = Server.wssAddress + 'websocket/' + Auth.getAuthorization() + '/' + $stateParams.appid;
		console.log(socketPath);
		vm.socket = new WebSocket(socketPath); //创建一个websocket对象
		//open connect
		vm.socket.onopen = function(event) {
			console.log('socket.onopen');
			//socket.send('this message from client');
			// close
			vm.socket.onclose = function(event) {
				console.log('==========================================socket.onclose', event);
			};
				
			vm.socket.onmessage = function(event) {
				$(".logs").append('<p>' + event.data + '</p>');
			};
			
			vm.socket.onerror = function(event) {
				console.log('socket.error');
				console.log(event);
			};
		};
	};
	getLog();
`
How to disconnect websocket when the Google Chrome page is refreshed?
thanks a lot.

**Comment by asergeyev** [comment]
You already should have it disconnecting if you hit browser refresh button. Let me please know if it's not the case and what you see happening instead.

**Comment by liuxg123** [comment]
Here's my webscoket setting,
`@OnOpen
	public void onOpen(@PathParam("token") String token,@PathParam("applicationId") String applicationId,Session session) {
		System.out.println("open");
		this.session = session;
		if(SessionUtils.getSession(token, applicationId)!=null){
			System.out.println(SessionUtils.getSession(token, applicationId).getId()+", session is close");
			SessionUtils.removeSession(token, applicationId);
		}
		SessionUtils.addSession(token, applicationId, session);
		System.out.println("size ======================"+SessionUtils.getSessionSize());
		try {
			logsDao.stream(token, SessionUtils.getSession(token, applicationId), applicationId);	
		} catch (Throwable e) {
			e.printStackTrace();
		}
		System.out.println("Client connected  "+token);
	}
`
it will create new connect when i refresh page
here's console output,
first:
`
open
size ======================1
sessionId = 1
`
second:(refresh page)
`
open
size ======================2
sessionId = 2
`

**Comment by asergeyev** [comment]
Sure but is there onClose that you have too that would print info when browser refreshes? Also if I misunderstood you and you want to avoid refresh re-open, it's not possible. Protocol specs say "close connection when you destroy javascript variable that holds it"  and when you refresh page all variables get wiped out in window context.
