### ISSUE TITLE
Using binary data

### ISSUE THREAD

**Issue by Yatekii** [joewalnes/websocketd#258]
Hi!

Could you give me a hint how to send/receive binary data?
Also: is it possible to mix binary/nonbinary requests?

Thanks
Yatekii

**Comment by asergeyev** [comment]
What kind of binary data producer you have? 
#38 has some discussion points

Normally you should use  --binary and that should stat working but if your scripts have buffering or very large blocks of data in each transmission it could not work exactly as expected...
