### ISSUE TITLE
--Devconsole cuts off 

### ISSUE THREAD

**Issue by ren-kun** [joewalnes/websocketd#260]
I'm not sure why, but after a while the connection closes with this error:

conclose [Clean: true, Code: 1005, Reason: none]

**Comment by bkrajendra** [comment]
Similar thing happening with me too.
I'm trying to use it on Windows 10 pro 64 bit.
tried with vbscript and count.sh but it does not work. basically socket connect and then
disconnects immediately.

![image](https://cloud.githubusercontent.com/assets/994083/26207404/02b78bd6-3c05-11e7-9607-2a020803eed7.png)

**Comment by asergeyev** [comment]
Is there anything in chrome developer console during that?

**Comment by bkrajendra** [comment]
Issue seems to be related to executable execution.
It works if internal command is used. It does not work if batch or cmd is used.
I'm working on windows.
My issue got resolved when I used internal command.

**Comment by asergeyev** [comment]
Gotcha... I wonder if there are special permissions app has to have in order to create sub processes

**Comment by asergeyev** [comment]
Looks like we need much more work on Windows. Websocketd adds dot-path to programs ran without path and this seem to confuse windows 10.  It does seem hard to run websocketd under win10 currently. Will see what we can do in new version :(

**Comment by asergeyev** [comment]
Ok... Now I wonder if it'll work in 0.3.0

There were bunch of things broken under windows due to lack of system environment after os.Clearenv() call

**Comment by bkrajendra** [comment]
its working for me now in windows 10 now #129

**Comment by asergeyev** [comment]
Great, thanks for confirming!
