### ISSUE TITLE
Not able to find the gpg key

### ISSUE THREAD

**Issue by xaon** [joewalnes/websocketd#261]
![image](https://cloud.githubusercontent.com/assets/1102785/26282935/6b183d06-3e1c-11e7-8cf2-4ea402aaf449.png)

**Comment by asergeyev** [comment]
Thanks. I'll look into it. I think my self-signature that I used is expired now. pgp.mit.edu shows that.

**Comment by asergeyev** [comment]
![image](https://user-images.githubusercontent.com/715656/32419566-de373128-c249-11e7-8a26-fabba7d549a7.png)


Finally got to fix it, sorry for such huge delay, thanks for noticing it again.
