### ISSUE TITLE
Websocketd chat on yun openwrt mips

### ISSUE THREAD

**Issue by scenaristeur** [joewalnes/websocketd#262]
Hi, i've just bought an arduino yun and wanted to put a chat server on it, using nodejs and socket.io, but socket.io needs a nodejs > 4, and it's very hard to compile it, with all dependancies, modules, so i'm looking for a deeper answer.
Websocketd sounds good but i don't see the Yun/openwrt/mips architecture in what you propose. Perharps a websocketd implementation for all/generic openwrt systems would be a good thing, but i don't know how to transform your go code into an opkg installable  package for my yun. 
It would be a good thing for me and for for community, then we could run  scripts on a iot machine just with a webbrowser. Or put a webchat in every iot object 😉. Or easily communicate with robots...
And the data stay local and not feeding all gafa... And millions of other good things...

So if someone could help me to package websocketd for my openwrt yun, i think this method could help : 
https://wiki.openwrt.org/doc/devel/packages

Thx .
David

**Comment by asergeyev** [comment]
https://github.com/GeertJohan/openwrt-go/issues/12 this suggests mips32 output would suit openwrt... still want to try? Do you have experience building go programs on your computer (not on wrt device) ? Can you install go on your machine?

**Comment by scenaristeur** [comment]
Thx for your response, i found another way. 
using openwrt package, one was node-socket.io and it is made for that architecture. 
Now my socket.io chat is working on my Yun.
