### ISSUE TITLE
The reuse problem of TCP port under multiple network connections

### ISSUE THREAD

**Issue by V-MI** [joewalnes/websocketd#265]
Hi，when I run the python code in websocketd, It shows the error “socket.error: [Errno 98] Address already in use”.
When there are multiple connections to websocketd，port 5001 is used for a welcome socket for TCP, is there a way to reuse it?
Thank you！
```
from sys import stdout
from socket import *
import threading
def tcplink(sock, addr):
    while 1:
        data = sock.recv(1024)
        print(data)
        stdout.flush()
    sock.close()
serverPort = 5001
serverSocket = socket(AF_INET,SOCK_STREAM)
serverSocket.bind(('',serverPort))
serverSocket.listen(5)
while 1:
    sock, addr = serverSocket.accept()
    t = threading.Thread(target=tcplink, args=(sock, addr))
    t.start()
```

**Comment by asergeyev** [comment]
What are you trying to do? websocketd will run multiple copies of your program. You can solve that with SO_REUSEADDR, SO_REUSEPORT but I think it might be not what you actually need.

**Comment by V-MI** [comment]
I want to receive temperature data from a IoT device and push the temperature data to all open web pages.

Whether websocketd can run only one program to all connections, rather than multiple copies of the program，to achieve the same push for all pages.

**Comment by asergeyev** [comment]
two ways of doing it
1) create one script that dumps content of sensor to file every X minutes run websocket with program that dumps that file to connected clients. You might need some kind of locking.
2) write your own program similar to websocketd, it's relatively easy if you use it as starting point. IMO it's best choice for any serious websocket-service. websocketd is good as flexible tool that does not necessarily solves all the problem.
