### ISSUE TITLE
Responses not being passed to client

### ISSUE THREAD

**Issue by sgilbertson** [joewalnes/websocketd#266]
I have a program running on Windows 10 (64 bit) that responds to ASCII commands on port 60000, and I'd like to expose that interface as a websocket.

I can do "telnet localhost 60000" and it works fine. I grabbed netcat-win32-1.12.zip from [https://eternallybored.org/misc/netcat/](https://eternallybored.org/misc/netcat/), and "nc64 localhost 60000" also works fine.

By "works fine" I mean when I type a command, I see the response text coming back.

I also have websocketd-0.2.12-windows_386, and I tried "**websocketd --devconsole --port=60001 nc64 localhost 60000**", then tested it using [http://127.0.0.1:60001/](http://127.0.0.1:60001/) in a web browser. Connect is OK, and when I send commands, my custom program shows that it both received them and sent responses. No responses appear in the web browser, though.

I then tried "**websocketd --devconsole --port=60001 cmd**", and in that case the devconsole interface works fine in the web browser. Entering "dir", for example, I see the directory contents.

I don't understand why one of those cases works and the other doesn't. In both cases websocketd is controlling a program with stdin/stdout ASCII interfaces, and in both cases the responses use CR-LF line endings.

Adding "--loglevel-debug" didn't help. It doesn't emit anything related to commands and responses -- only connect and disconnect events.

How do I go about troubleshooting this problem?
Is there a way to get websocketd to emit even more debug info?

**Comment by sgilbertson** [comment]
Additional info...

Running a Ubuntu VM on the same Windows PC, I grabbed websocketd-0.2.12-linux_386.zip and ran:
` ./websocketd -devconsole --loglevel=debug --port=60001 nc 192.168.1.60 60000`
(my Windows PC is 192.168.1.60 on the LAN)

Then in Firefox under Ubuntu I loaded http://localhost:60001/ -- worked fine, by which I mean I could type commands and see the responses. To round out the set of combinations I accessed the Ubuntu websocketd devconsole from Windows (worked fine) and vice-versa (no responses).

So the common denominator is which OS is hosting websocketd and netcat:
- If websocketd and netcat are running on Ubuntu, connecting to my custom Windows program, everything is OK
 - If websocketd and netcat are running on Windows, also connecting the the same Windows program, there are no responses

Either there's a problem with winsocketd on Windows or it doesn't like the Windows version of netcat I'm using.

**Comment by sgilbertson** [comment]
Of course seconds after clicking "Comment" the obvious (in retrospect) thought hit me -- find a different build of netcat for Windows. I grabbed one here: https://nmap.org/ncat/ and did:

`websocketd --devconsole --loglevel=debug --port=60001 ncat localhost 60000`

That works.

So while it would still be good to know why the original netcat program doesn't work properly with websocketd, I'm up and running now.

**Comment by asergeyev** [comment]
I don't think there is way to know how original one is actually working with terminal.
