### ISSUE TITLE
Redirecting STDERR from the Windows Command Line not working

### ISSUE THREAD

**Issue by vbalasu** [joewalnes/websocketd#268]
I am on a Windows machine, and trying to set up a command line session with websocketd. 

`websocketd --port=8080 --devconsole cmd /k  2>&1`

I ran into a similar issue as described in [this post](https://github.com/joewalnes/websocketd/issues/219)
If I run a simple *valid* command from my web browser, such as `dir`, the output is displayed, no issues

However, if I enter an *invalid* command, the error output (eg. `'ijgo45ij' is not recognized as an internal or external command, operable program or batch file.`) is not shown at all, in spite of the `2>&1` command above.

How can I get the STDERR output to appear?

**Comment by asergeyev** [comment]
Ok, this would not work since 2>&1 applies to websocketd, not to program... You might try to do something like a cmd file in which you include  call to cmd and 2>&1 redirection and run that cmd file out of websocketd.

**Comment by vbalasu** [comment]
That was it - thanks!

I got it to work by changing it to the following:
`websocketd --port 8080 --devconsole cmd /k winshell.cmd`

where the contents of winshell.cmd are as follows:
`cmd /k 2>&1`

Thanks again for your help!
