### ISSUE TITLE
Send Message form Client to PHP Server 

### ISSUE THREAD

**Issue by daslicht** [joewalnes/websocketd#269]
Hi,
is it possible to send messages via socket to something php based ?
How would that work please?

 ~ Marc

**Comment by Sa1ch** [comment]
JS
`var ws = new WebSocket('ws://localhost:9000/test.php');
ws.send("Hello");
`
PHP
`$stdin = fopen('php://stdin', 'r');
$line = fgets($stdin);
print "You sent :: $line \n"
`

**Comment by daslicht** [comment]
thank you !
