### ISSUE TITLE
Carriage return required 

### ISSUE THREAD

**Issue by limenleap** [joewalnes/websocketd#271]
Hi
This is actually not an issue -- I thought it was. I thought I should write it down here, as it may help others. I had written a bash-script that uses inotifywait to check the presence of new files in a directory ... then it reads out the content of the new file to stdout. I daemonized that bash-script using websocketd

After struggling a lot I realized that websocketd would pass it onto the connected browser ONLY if there is a new line at the end of the text! I guess that is how it determines what to send next to the connected socket

I hope this will save others with a similar situation!

**Comment by asergeyev** [comment]
You can use --binary to fetch script output in batches similar to those that script writes.
But if your script is line buffering it'll require you to have \n anyway

**Comment by asergeyev** [comment]
Closing, hope binary helps.
