### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by lucabecchetti** [joewalnes/websocketd#272]
Hi, thanks for you amazing project, is there a way to add any type of authorization?

**Comment by asergeyev** [comment]
What kind of auth would you like to see? Normally it should be handled by higher lever authorizing web-proxy but if there is something in webocket land we might need to consider it.

**Comment by coderofsalvation** [comment]
how about the browser's builtin basic http auth, because that also works for https (when the ssl certs are configured for websocketd):

```
func basicAuth(username, password string) string {
  auth := username + ":" + password
  return base64.StdEncoding.EncodeToString([]byte(auth))
}

func redirectPolicyFunc(req *http.Request, via []*http.Request) error{
  req.Header.Add("Authorization","Basic " + basicAuth("username1","password123"))
  return nil
}

func main() {
  client := &http.Client{
    Jar: cookieJar,
    CheckRedirect: redirectPolicyFunc,
  }

  req, err := http.NewRequest("GET", "http://localhost/", nil)
  req.Header.Add("Authorization","Basic " + basicAuth("username1","password123")) 
  resp, err := client.Do(req)
}
```

**Comment by tonyho** [comment]
> how about the browser's builtin basic http auth, because that also works for https (when the ssl certs are configured for websocketd):↳
> 
> ```
> func basicAuth(username, password string) string {
>   auth := username + ":" + password
>   return base64.StdEncoding.EncodeToString([]byte(auth))
> }
> 
> func redirectPolicyFunc(req *http.Request, via []*http.Request) error{
>   req.Header.Add("Authorization","Basic " + basicAuth("username1","password123"))
>   return nil
> }
> 
> func main() {
>   client := &http.Client{
>     Jar: cookieJar,
>     CheckRedirect: redirectPolicyFunc,
>   }
> 
>   req, err := http.NewRequest("GET", "http://localhost/", nil)
>   req.Header.Add("Authorization","Basic " + basicAuth("username1","password123")) 
>   resp, err := client.Do(req)
> }
> ```

Hope  it can add this feature.
