### ISSUE TITLE
websocketd for http

### ISSUE THREAD

**Issue by timsuchanek** [joewalnes/websocketd#273]
Websocketd is an awesome project.
Do you know of a solution with a similar approach for http?

**Comment by dhopf** [comment]
Without completely understanding your request: Isn't [inetd](https://www.freebsd.org/cgi/man.cgi?query=inetd&sektion=8) something to look into?

**Comment by asergeyev** [comment]
Since there is no clarification on question I'll close it but feel free to re-open.
