### ISSUE TITLE
Support in websocketd to send 'ping' and 'pong' control frames?

### ISSUE THREAD

**Issue by dhopf** [joewalnes/websocketd#275]
Does websocketd offer any support for 'ping' and 'pong' control frames as specified in [section 5.5](https://tools.ietf.org/html/rfc6455#section-5.5) in RFC 6455? By looking at a Wireshark capture it doesn't look like websocketd is sending any such frames by default (although my Google Chrome browser at the client doesn't seem to send 'ping' control frames either).

My actual issue is that my websocket connection gets closed after some random time, even if I send dummy keep-alive messages periodically. I now was wondering if it actually is a timeout issue and if utilizing the ping/pong control frames might help to keep the websocket connection alive.

**Comment by Arno0x** [comment]
I ran into the very same problem today: IE sends a WebSocket PONG request and Websocketd replies with a WebSocket CLOSE :(

**Comment by asergeyev** [comment]
I'll look soon into it. Sorry but until we migrate to other websocket library things would not improve... I was always hoping itll not be necessary and standard lib would improve but looks like things stuck in time there... and they even started to recommend using gorilla lib...

https://github.com/golang/net/tree/master/websocket

If anyone wants to beat me and PR gorilla migration, it would be greatly appreciated :)

**Comment by asergeyev** [comment]
Ok.. I made version of PR and will pre-release binaries when I check few things...

**Comment by dhopf** [comment]
Hi Alex,
Sorry for asking again: Do you have a rough estimate on when you will be able to release the PR-capable binaries? I would like to test that in our implementation and double-check with Wireshark captures.

**Comment by asergeyev** [comment]
Do you need windows server side? Currently SSL under windows is not behaving correctly. That's why I'm holding on binaries. What system do you use to run websocketd currently?

**Comment by dhopf** [comment]
We’re using websocketd on a Linux System running on a Beaglebone, so we just need an ARM-binary for Linux.

**Comment by asergeyev** [comment]
I published pre-release. Any chance you can risk and check it? I can always describe how to compile things on your own if you don't trust the binaries

**Comment by asergeyev** [comment]
@dhopf any luck trying to see if anything about PING/PONG is not working in 0.3.0 release?

**Comment by asergeyev** [comment]
@Arno0x  maybe?

**Comment by Arno0x** [comment]
I can do the same check from IE to websocketd to see if the problem is gone. This would not be a comprehensive testing of a proper support of the ping/pong mechanism, but at least it would be a clue.

I'll reach out to you once I've found some time to do this test.

Thanks by the way for implementing this into a new release.

**Comment by dhopf** [comment]
Sorry for not answering for a long time @asergeyev .
I didn't find the time to test the new release due to christmas holidays and unavailability of the target system currently. I try to duplicate the linux-arm target system next week and verify the PING/PONG functionality.

**Comment by dhopf** [comment]
Hi again,
I now setup basically a similar setup here and try testing the Ping/Pong functionality.

Maybe you can help me in moving on:
I'm using Chrome 64, but still if I do a websocket connection, I never see any websocket PING/PONG frames. Isn't Chrome (and other state of the art browsers) supposed to send ping or pong frames on a regular basis when a websocket connection is open? Or do I have to implement/trigger some "send websocket ping control frame"-functionality in javascript myself?

The only thing I see with both, the old websocketd version as well as 0.3.0, is regular TCP keep-alives on the websocket-port, but I guess this is normal behavior of TCP?

Thanks!

**Comment by asergeyev** [comment]
```An endpoint MAY send a Ping frame any time after the connection is
   established and before the connection is closed.

   NOTE: A Ping frame may serve either as a keepalive or as a means to
   verify that the remote endpoint is still responsive.
```

IMO since there is tcp keepalives and other means of knowing connection is open or down browsers have little need for ping/pong frames. But as report above suggests IE is using them.

I don't think PING should be passed to script therefore currently it just going to be responded with PONG without ever emitting PINGS on its own from websocketd to clients. 

Websocketd is currently not equipped to manage timed-out client connections so there is no need to deal with PING as reset for timeout. We might need to start separate thread for adding that (specially if people see high inactive connection numbers).
