### ISSUE TITLE
Broken! Project Example: real-time sensor plots with websocketd 

### ISSUE THREAD

**Issue by johnkelton** [joewalnes/websocketd#278]
I followed the following tutorial word by word:
http://www.perrygeo.com/raspberry-pi-real-time-sensor-plots-with-websocketd.html

But my plot is empty i.e. no data point. Even though my log.txt file has data points. My python script and WebSocketd is working as I can see the index.html turn green and also --devconsole works. You can download the project from here and try it:

https://github.com/perrygeo/pi_sensor_realtime

**Comment by asergeyev** [comment]
I really could not help with that other project, there is just no time to investigate something I don't really understand and it seem noone could jump on this for you right away too.. so I'll close this, sorry.
