### ISSUE TITLE
Release as deb/rpm/pkg

### ISSUE THREAD

**Issue by thedrow** [joewalnes/websocketd#28]
[jordansissel/fpm](https://github.com/jordansissel/fpm) allows you to easily create packages in multiple formats such as *.deb, *.rpm and *.pkg for Mac (and even tarballs for those who do not want them).
[bernd/fpm-cookery](https://github.com/bernd/fpm-cookery) also helps creating packages by allowing to write small scripts that use fpm.
With those two projects, it should be fairly easy to build packages in multiple formats.

**Comment by omarali-me** [comment]
![image](https://user-images.githubusercontent.com/47008784/51791651-adceeb80-21bf-11e9-8033-e528a828fb3a.png)

I was trying to install the deb package and got this.. I think you need to fix it by adding the name or something..
