### ISSUE TITLE
Optionally Pass `stderr` To Client

### ISSUE THREAD

**Issue by Swivelgames** [joewalnes/websocketd#281]
I'm currently experimenting with `websocketd`, and it looks like it is exactly what I need for my current implementation. However, the only piece missing is the ability to optionally pipe `stderr`.

Maybe via a `-stderr` option that would `Also streams stderr output to client`?

In my case, `stderr` is written to in cases where the application does not actually exit, but I need access to those messages.

**Comment by asergeyev** [comment]
Why not to write your script that does it (not saying it's only option, just curious)?

Could be as easy as ```websocketd --port  bash -c "./program 2>&1"`` `

**Comment by Swivelgames** [comment]
@asergeyev I feel kind of silly now. That's actually exactly what I need. I'm running it within a docker container running Alpine 3.6.

To test, I used the following and it worked:

```
docker container run -ditp 9999:9999 --read-only CONTAINER_TAG_NAME:latest websocketd --port=9999 --address=0.0.0.0 --devconsole /bin/sh -c '/bin/sh 2>&1'
```

Thanks!

**Comment by asergeyev** [comment]
Great! Thanks for following up!
