### ISSUE TITLE
Process connection

### ISSUE THREAD

**Issue by Sa1ch** [joewalnes/websocketd#284]
Hello!
If you open two tabs in the browser, a new process will be created for each tab. How can you not produce processes, but connect already with the existing ones?

**Comment by asergeyev** [comment]
No, websocketd designed to run process per connection. It does not really work well for heavy processes that need too much resources but on lightweight it can handle thosands of processes without problems.

We discussed it before and decided that it's better for our users to write custom program in situation when they need multiplexing/demultiplexing than to try to redesign websocketd in way that would satisfy all usecases.
