### ISSUE TITLE
weird 'cached' output ?

### ISSUE THREAD

**Issue by onty** [joewalnes/websocketd#285]
So, soon as I able to compile it per Alex's instructions, I ran some small test : 
ubuntu@pegasus:~/websocketd/src/github.com/joewalnes/websocketd$ ./websocketd.arm64 --port 8001 --staticdir=. **ls**
Thu, 14 Dec 2017 06:18:12 +0000 | INFO   | server     |  | Serving using application   : /bin/ls 
Thu, 14 Dec 2017 06:18:12 +0000 | INFO   | server     |  | Serving static content from : .
Thu, 14 Dec 2017 06:18:12 +0000 | INFO   | server     |  | Starting WebSocket server   : ws://pegasus:8001/
Thu, 14 Dec 2017 06:18:12 +0000 | INFO   | server     |  | Serving CGI or static files : http://pegasus:8001/
_**Thu, 14 Dec 2017 06:18:34 +0000 | ACCESS | http       | url:'http://pegasus.local:8001/' | STATIC
Thu, 14 Dec 2017 06:18:34 +0000 | ACCESS | http       | url:'http://pegasus.local:8001/favicon.ico' | STATIC**_

It works fine.

Now, I am using the same port again, 8001, but this time with different command to execute : 

ubuntu@pegasus:~/websocketd/src/github.com/joewalnes/websocketd$ ./websocketd.arm64 --port 8001 --staticdir=. **uname -a**
Thu, 14 Dec 2017 06:19:38 +0000 | INFO   | server     |  | Serving using application   : /bin/uname -a
Thu, 14 Dec 2017 06:19:38 +0000 | INFO   | server     |  | Serving static content from : .
Thu, 14 Dec 2017 06:19:38 +0000 | INFO   | server     |  | Starting WebSocket server   : ws://pegasus:8001/
Thu, 14 Dec 2017 06:19:38 +0000 | INFO   | server     |  | Serving CGI or static files : http://pegasus:8001/
**_Thu, 14 Dec 2017 06:22:29 +0000 | ACCESS | http       | url:'http://pegasus.local:8001/' | STATIC
Thu, 14 Dec 2017 06:22:31 +0000 | ACCESS | http       | url:'http://pegasus.local:8001/' | STATIC
Thu, 14 Dec 2017 06:22:48 +0000 | ACCESS | http       | url:'http://pegasus.local:8001/?' | STATIC
Thu, 14 Dec 2017 06:23:05 +0000 | ACCESS | http       | url:'http://192.168.0.136:8001/' | STATIC
Thu, 14 Dec 2017 06:23:05 +0000 | ACCESS | http       | url:'http://192.168.0.136:8001/favicon.ico' | STATIC_**

Here is the weird thing. I keep getting the same result as 'ls' in my browser.
From that log output you can also see that I have tried different ways to access the websocketd, either by using hostname or direct ip address, in a hope that this is just some nasty browser cache. But looks like it keeps giving me the same first output 'ls' eventhough I changed the command into 'uname -a'.

I am using go 1.6.2 in my arm64 with the latest 0.3.0 version *I think.
![screen shot 2017-12-14 at 06 29 24](https://user-images.githubusercontent.com/34977/33978550-321ec55a-e098-11e7-92bd-9d0a1abe7877.png)

**Comment by asergeyev** [comment]
Unless you upgrade connection to use Websocket protocol you will not see anything but files in your directory since static handler takes care of serving your HTTP requests. What are you expecting to do using --static? Something maybe that --devconsole does?
