### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by asergeyev** [joewalnes/websocketd#286]
Since there are positive responses on pre-release we're going to release gorilla migrated code on Dec 25th or 26th if I miss it. :)

**Comment by asergeyev** [comment]
Merry Christmas, it's posted!

**Comment by joewalnes** [comment]
👍🎉

**Comment by asergeyev** [comment]
Ah, needs website edits

**Comment by asergeyev** [comment]
Fixed
