### ISSUE TITLE
How to pass data from served static site back to the app?

### ISSUE THREAD

**Issue by kwmlodozeniec** [joewalnes/websocketd#288]
I have a web app running on a raspberry pi, serving up a simple HTML page with some barcode scanning capability (normal USB scanning, not video processing). Some JS captures output from the barcode scanner and passes that back to my Flask program.

There are various issues I am experiencing with this setup, mainly the unreliability of web server. So in my research, I have come across websocketd. On the surface, it does what I want to achieve aside from passing the barcode data back from the page to the running program. In my Flask example, I have used socket.io but that seems to be letting me down and seems way too complicated for my application.

How can I achieve two-way conversation between the static page and my python app?

**Comment by asergeyev** [comment]
I'd say you can try our examples (e.g. basic one and then greeting in python) to see if it's good enough for you.   Having something running as server is still required, if it's not stable (rebooting or loosing network connections often) websocketd would likely be worse.

**Comment by kwmlodozeniec** [comment]
I tried the example and for me it works better thank Flask and gunicorn combo.
