### ISSUE TITLE
Is websocketd supposed to send msg to all connected clients?

### ISSUE THREAD

**Issue by darylwilliams** [joewalnes/websocketd#289]
Hi joewalnes I just ran across your websocketd program and it looks very interesting. Is this still an active project? I'm an old time unix guy so I like your approach here.

My question is stated in the subject and I haven't had any success getting it to work across multiple clients. I'm just not sure if I'm missing something? I have tried the greeting.php example and I've modified the C code to write messages from an input box to stdout but the output is limited to the single browser being used and messages are not passed to the other connected browsers. Perhaps I've misunderstood the application of your websocketd program?

Thanks,

Daryl

**Comment by asergeyev** [comment]
Each client connected to separate script/process so if you need to send something to all clients  backs need to generate message at same time (really as inetd used to do for tcp/udp connections).
