### ISSUE TITLE
could not launch process fork/exec ... is not a valid Win32 application

### ISSUE THREAD

**Issue by wwnje** [joewalnes/websocketd#293]
could not launch process fork/exec ... is not a valid Win32 application
![aaa](https://user-images.githubusercontent.com/17811868/37583473-7d1c293c-2b8c-11e8-87f8-3c1ff88de550.png)

**Comment by asergeyev** [comment]
Did you try to use python executable before your script?

``` websocketd --port=8080 python path/to/script```

**Comment by firework-wyw** [comment]
> 
> 
> 您是否尝试在脚本之前使用 python 可执行文件？
> 
> ` websocketd --port=8080 python path\to\script`

牛呀
