### ISSUE TITLE
URL Encode commandline arguments for called script?

### ISSUE THREAD

**Issue by alexfederlin** [joewalnes/websocketd#294]
When using the --dir=DIR option, this enables me to call any script in that DIR.
Is there also a way to pass arguments to that script?

I tried with `http://localhost:8080/script.sh%20argument` but that resulted in "script not found"
I also tried with `http://localhost:8080/script.sh?argument` and `http://localhost:8080/script.sh?arg=argument` but $1 in the bash script I called remained empty.

**Comment by asergeyev** [comment]
Arguments are seen by script as environment variable QUERY_STRING per [RFC3875](https://tools.ietf.org/html/rfc3875). 

This is part of CGI standard and while it's good to pass them this would limit ability to run scripts as  `websocketd script arg arg`.

**Comment by alexfederlin** [comment]
Thanks! That answers my question!
