### ISSUE TITLE
get error message when output Chinese

### ISSUE THREAD

**Issue by beebon** [joewalnes/websocketd#298]
code in python with windows 7 system,the cmd console have errors when output Chinese,following is my codes:

> #coding=utf-8
> 
> print('这是一个中文测试！') 

the errors in cmd console is

> Wed, 28 Mar 2018 19:35:38 +0800 | ERROR  | process    | url:'http://localhost:8989/' id:'1522236913000568300' remote:'::1' command:'C:\Windows\py.exe' origin:'file://' pid:'11232' | **SIGINT unsuccessful to 11232: not supported by windows**
> Wed, 28 Mar 2018 19:35:38 +0800 | ACCESS | session    | url:'http://localhost:8989/' id:'1522236913000568300' remote:'::1' command:'C:\Windows\py.exe' origin:'file://' pid:'11232' | DISCONNECT

it's correct if I print some english words. I guess this issue may happend in printing non-english string,please have a look of it. ths!

**Comment by asergeyev** [comment]
It might be that Python running under websocketd in Windows could not find some system files ....
What version of websocketd are you using? You need 0.3.0 to avoid that.

**Comment by beebon** [comment]
I use just version 0.3.0,that's info by running in cmd

> D:\app\wsocket>websocketd --version
> websocketd 0.3.0 (go1.9.2 windows-amd64) --

**Comment by beebon** [comment]
there's no problem in *nix system,anyway I use a hacking-way to avoid it,Thank u

**Comment by asergeyev** [comment]
hm,.... still interesting why windows fails.. Maybe others could find something I'll keep this open for couple months more.

**Comment by GalaxySnail** [comment]
I think I have found a solution:
```python3
import sys
import io

sys.stdin = io.TextIOWrapper(sys.stdin.detach(), encoding="utf-8")
sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding="utf-8")
```
I tryed setting up environment variables (`PYTHONIOENCODING`, `PYTHONUTF8`), `chcp`, and some others, but none of them solved the problem. That's really confusing. Only this way works.
