### ISSUE TITLE
download websocketd-0.3.0-windows_amd64 zip 

### ISSUE THREAD

**Issue by jiemeizhang** [joewalnes/websocketd#301]
when I decompress the zip ,click the websocked.exe program,the client shutdown immediately，then  websocketd --port=8080 ./counter.sh，the shell throw bash: websocketd: command not found
can you give me assistance to reslove the issues.Thank you very mush

**Comment by asergeyev** [comment]
what operating system and version of it are you using? 

(I don't really understand how Bash is  in play on Windows)

**Comment by jiemeizhang** [comment]
windows-64 bit operating system 
git bash

**Comment by asergeyev** [comment]
Can you just run ./counter.sh and it works?  that example is really not made for windows so it might fail for many reasons unfortunately :(

**Comment by sectokia** [comment]
in windows you may have to run it like this:
websocketd --port=8080 "c:\path\to\bin.exe" "c:\path\to\whatever.script"

Obviously you would have to replace both with the exact file names, which would be bash command shell executable and the counter.sh file.
