### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by thomsa** [joewalnes/websocketd#302]
Hey,

I'm trying to connect from another host and it's failing because of CORS. Can I do something about it from the command which is being executed?

**Comment by asergeyev** [comment]
What browser do you use?   Do you have CORS rejection before upgrading to websocket?

You probably need to add headers to your websocketd  --header="..."  

Otherwise I'd love to see more info from your browser somehow... What requests it makes and what answers it receives from websocketd
