### ISSUE TITLE
Query: Server and multi-client setup

### ISSUE THREAD

**Issue by NickSutton** [joewalnes/websocketd#303]
Hey, I have websocketd running, but my approach is off and I can’t complete the final step of my project.

I have a 4 Raspberry Pi, one working as a server and three as clients.

When any of the clients does something (registers a GPIO pin state change in this case) I need to let the other clients know about this.

So far I have gotten each of the clients to tell the server of the state change by using websockets.

I run a web page for each client on the server, this will write the websocket message to a text file.

There is very low traffic on the system, and extremely unlikely that more than one client will be sending a message at any time.

The final piece, is that a instance of websocketd is running on the server, reading the text file that is being written by the incoming websocket connections from the clients. I would have thought to connect all the clients web browser to this instance to be able to share the text file contents between the clients (via the server)...

Is there a better way to do this? It’s like I need websocketd to talk to another websocketd, which will then broadcast to all the other websocketd’s!!

**Comment by asergeyev** [comment]
Or you can use one websocketd to write events and another to tail log where they recorded.
