### ISSUE TITLE
PHP : a " added before the string in the send() function. **I need help**

### ISSUE THREAD

**Issue by ben7244** [joewalnes/websocketd#305]
Hi!
I'm enjoy to discover this websocket but I meet this problem that I can not solve... 

Html
`<a class="navbar-brand" OnClick="ws.send('hello');">`

When I check the value sent by the client in my ws-socket.php.
('hello'=='hello') return false...
`$f = fgets(STDIN);
if($f=='hello'){
    echo 'OK';
}
else
{
	echo 'NOK : '.$f ;
}`
Client side :
`ws.onmessage = function(event) { 
				     alert(event.data);};`
The alerte function  shows me : NOK : hello
If I try:
`$f = fgets(STDIN); strlen($f);` the return is : 6 ??? 
`var_dump($f) ` return : string(6) "hello
Where is coming this" ? 
So I try to remove it with `substr($f,1);` but `ws.onmessage = function(event) {alert(event.data);};`
shows : NOK : ello

It's inapprehensible for me, I'm blocked on this problem and I have no other ideas. 
Can someone help me?

**Comment by asergeyev** [comment]
When you have fgets(STDIN) your string will contain line break in the end.
So you need something like `trim(fgets(STDIN))`

**Comment by ben7244** [comment]
Thank you!
"hello" == "hello"!!! 
But, now, I try to answer "hello world!" to the client and the alert return only "hello" ... 😪
`
set_time_limit(0); 
while(true){
		$f = fgets(STDIN); 
		if($f === false){
				break; 
		}
			if(trim($f)=="hello"){
				echo $f." world!"; 
			}
			else
			{
					echo  "bad ".$f;
	 		}
}
`
It's the same kind of problem ?

**Comment by asergeyev** [comment]
yes, you need end of line in your output to be processed by websocketd

**Comment by ben7244** [comment]
OK !
Thank you very much! 
So, now I'm ready to websocketd?
