### ISSUE TITLE
colours / html

### ISSUE THREAD

**Issue by mo8Zomo0** [joewalnes/websocketd#306]
Hello!

I wonder is it somehow supported to use colours of the source either ANSI 
or pass through html colours or other html formatting through the web socket
so it shows up as more as pure text?

**Comment by mo8Zomo0** [comment]
Noticed #292 to late. Even if ANSI is not supported directly. There are tools like aha to transform it to html tags. Is there a way to interpret the html tags instead of showing them as raw text?

**Comment by asergeyev** [comment]
Not sure what you mean. Your application defines "showing". So if you receive html you can decide way to insert it to DOM, simplest way is to change innerHTML of an element.
