### ISSUE TITLE
Having trouble with websocketd windows 64-bit download

### ISSUE THREAD

**Issue by nyasha145** [joewalnes/websocketd#309]
Is anyone having a similar problem?

I downloaded the windows 64-bit installer and when I extract the files from the zip folder and try to run the executable, I get a box that appears then quickly disappears. So I can't install websocketd. I'm not sure what's wrong. Is there something else I need to download? Thank you!

**Comment by asergeyev** [comment]
Which version of windows do you have and what zip file were you downloading?

You can try to install go and build websocketd yourself with "go get github.com/joewalnes/websocketd"  (find executives in %gopath%\bin likely, not 100% sure how that works on windows)

**Comment by sectokia** [comment]
There is no installer... the exe is the program itself in its entirety. 

Put it in a folder and run it from a command prompt. If you double click it it will just execute with no args, causing the windows console to pop up and disappear.

**Comment by nyasha145** [comment]
Ahh thanks for the clarification!
