### ISSUE TITLE
Documentation for --dir use

### ISSUE THREAD

**Issue by dealerwrx** [joewalnes/websocketd#310]
Can you please cover how to use the --dir command. Obviously it is to server multiple docs, but how does one access those different pages or "channels" though websocketd?

**Comment by asergeyev** [comment]
Say you have two scripts:   count.sh and sayhi.pl

You make them both executable, put into a directory called "somename" and run websocketd with --dir=somename and --port=someport (while in directory that contains somename)

This will provide you opportunity to use two different scripts using same websocketd instance:

http://address:someport/count.sh  will route you to one script and
http://address:someport/sayhi.pl will route you to second one.

It's only useful when you have multiple scripts. Without --dir you give one script to websocketd and it will run it regardless of which URL you'd use.

**Comment by dealerwrx** [comment]
Thanks!
