### ISSUE TITLE
Any update/future for subscribe?

### ISSUE THREAD

**Issue by dealerwrx** [joewalnes/websocketd#311]
I know it was mentioned in the past, but just checking if an progress has been made on a "subscribe mode" allowing users the connect to the same websocket & sub-process.

The intended use is for a notification system for my application. I have about 20-30 users that log into a page to get "alerts" from other users. Since they all see the same thing, it would be beneficial if the server allowed connection to the same sub-process rather than having that many of the same process running.

(this is also a type of hack to accomidate IE not supporting HTML5 sse)

**Comment by dealerwrx** [comment]
bump ?

**Comment by asergeyev** [comment]
If you really need shared queue you'd need to implement it outside websocketd.
If you want convenience of websocketd you end up playing along and could (assuming example task in your ticket) just create REST API to post notifications into log (and maybe to database or somewhere else) and connect all users via websocketd to tail that log indefinitely.
