### ISSUE TITLE
QUERY_STRING blank

### ISSUE THREAD

**Issue by bgailer** [joewalnes/websocketd#312]
Platform: windows 10
server invocation: `websocketd --port=8080 --staticdir=. c:/python35/python wsd_server2.py `
Firefox browser URL: `http://localhost:8080/nvc/xxx.html?id=574678`

wsd_server2.py:
```
#!/usr/bin/python
# File: wsd_server2.py
from sys import stdout, stdin, stderr, exit
import os
def cons(*tt): [stderr.write(t +'\n') == stderr.flush() for t in tt]
cons('q=' + os.environ.get('QUERY_STRING', 'no qs'),)
exit(0)
```

Server console:
`q=`

Why is os.environ['QUERY_STRING'] blank?

**Comment by dealerwrx** [comment]
I don't believe the stderr.flush() sends the needed '\n' (new line). try adding that to the end.

**Comment by bgailer** [comment]
You don' seem to understand. It is not an issue of how to write to the console.
1 - My code `stderr.write(t +'\n')` provides the \n 
2 - The result of `'q=' + os.environ.get('QUERY_STRING'` is written to the console as I indicated under Server console:
`q=`
The fact that only `q=` is written tells me that os.environ['QUERY_STRING' is returned, and it is an empty string.

**Comment by bgailer** [comment]
I have simplified my code:
```#!/usr/bin/python
# File: wsd_server2.py
from sys import stdout, stdin, stderr, exit
import os
q = os.environ['QUERY_STRING']
stderr.write('q="' + q  + '"\n') 
exit(0)
```
When I invoke this code with the URL `http://localhost:8080/nvc/xxx.html?id=574678` 
the following appears on the server console:
```
CONNECT
 q=""
 DISCONNECT
```
Does that help clarify the situation? 
It is obvious that os.environ['QUERY_STRING'] returns an empty string.

According to the docs  (https://github.com/joewalnes/websocketd/wiki/Environment-variables):

QUERY_STRING

Everything after the ? in the URL.

Example: If the requested WebSocket URL is ws://localhost:1234/somedir/myscript.py?name=me&msg=hello%20world, then:

QUERY_STRING=name=me&msg=hello%20world

I am hoping for a response from a websocketd developer.

**Comment by bgailer** [comment]
A workaround is: have the web page send document.url to the server program & parse the query string from that.

**Comment by dealerwrx** [comment]
As I am no a websocketd developer (or really very good at python, Im not sure I can help there. I can tell you that I am running my script as php, so my cli start line is:  
`websocketd --port=8080 php /var/www/websocket.director.php`
This does run my sql commands and returns the correct information. Now I had to wrap the return as a json to allow the line breaks to pass. 

Best of luck.

**Comment by bgailer** [comment]
Why an I getting responses that do not address my issue? Please only address the question "why is the environment variable QUERY_STRING blank, when I have provided a query string in my URL?"

**Comment by asergeyev** [comment]
Here is my test:

```
$ go get github.com/joewalnes/websocketd/libwebsocketd
$ go install github.com/joewalnes/websocketd
$ websocketd --port 8765 --devconsole ~/go/src/github.com/joewalnes/websocketd/examples/bash/dump-env.sh
```

then I opened localhost:8765 in browser and tried two different urls to the right of ✔ button (ws://localhost:8765/ and ws://localhost:8765/?ok)

Second time the output I got clearly included:

```REQUEST_URI=/?ok ```

and 

```QUERY_STRING=ok  ```

So I suspect something is just not working in your particular situation and we should first see if my way of exposing QUERY_STRING envvar would work for you.

**Comment by sectokia** [comment]
I think you are confused.... Your query string (?id=574678) is being passed to xxx.html, not to the websocketd. 

in your xxx.html I suppose you have javascript to make the request to the websocket, that URL needs the query string

please post contents of xxx.html so we can help
