### ISSUE TITLE
STDERR to websocket client?

### ISSUE THREAD

**Issue by asergeyev** [joewalnes/websocketd#315]
Based on discussion in #133 

In some situations STDERR is valid channel of communications but at times still should be partially filtered or distinguishable from actual strings read from STDOUT of monitored script...

So here are few possible solutions:

1) Second channel, maybe even one-way (e.g. server push) to send data about stderr
2) Mix with STDOUT, possibly by adding prefix to strings

On top of that there could be whitelist regexp given to filter strings to avoid including system info to web clients

So far all that makes more questions than answers so I'd gauge real need for it first.

**Comment by dolmen** [comment]
If you want to mix STDERR with STDOUT you can always wrap the program with a shell script that merges the two streams. No special support from the core websocketd is needed.

**Comment by asergeyev** [comment]
I think idea was to separate them and be able to treat them differently in browser later. But it's possible by wrapping too. And IMO since noone really supported that version so far I doubt it's that useful to go after anyway. Thanks for the opinion.

**Comment by asergeyev** [comment]
Been awhile, I'll close as there is no support.

**Comment by EvanCarroll** [comment]
I would have really liked to see this. The obvious default should be a mechanism to keep the two streams separate like wrapping them both in a `{stream:stderr|stdout, msg}` but even combining them is at least less insane then just dropping stderr.
