### ISSUE TITLE
provide a way to run a command after initial command is complete.

### ISSUE THREAD

**Issue by slloyd88** [joewalnes/websocketd#317]
I am trying to figure out a way to kill websocketd once the command it is running has finished.

Something like the following:

/etc/websocketd --port=8033 timeout 600s ls -al  && pkill -f "websocketd --port=8033"  > /dev/null 2>&1 &

Unfortunately this does not work.  any suggestions?  Could you add an argument that tells websocketd to stop once the command is complete?

NEVER MIND figured it out.

**Comment by asergeyev** [comment]
You have complicated usecase which naturally easiest to handle writing your own server-side end point.

But... Assuming you still want to do this websocket... Here is code that handles process behind websocket.
https://github.com/joewalnes/websocketd/blob/master/libwebsocketd/process_endpoint.go

Flag --closems dictates how long server will wait after closing STDIN to your program and before sending SIGINT, then SIGTERM, then SIGKILL to it. (If it still running) We add 100ms before first, 250ms before second and 500ms before SIGKILL to make time stretch a bit more.

You can use that to fork separate program at the time websocket terminates main one. If you don't handle input you can handle SIGINT and fork some process before SIGTERM arrived. New process would need to disconnect from parent but it's easy.  It's just quite "special case", I don't think other users would need that sort of thing to be in websocketd...

**Comment by slloyd88** [comment]
Thanks. I will give that a try.  I appreciate your help.
