### ISSUE TITLE
send message to specific client

### ISSUE THREAD

**Issue by aze2201** [joewalnes/websocketd#319]
any documentation to send message from server to specific client ?

**Comment by sectokia** [comment]
What do you mean?

Websocketd executes what you ask it for each client that connects.

So for each client there is a seperate instance of your program. 

In your program you can use the remote address enviromemt vairable to determine the client that the instance is for. So you could conditionally output to stdout based on that value.

**Comment by asergeyev** [comment]
@sectokia  this was great answer I'll close since there was no follow up.
