### ISSUE TITLE
websocketd on CentOS

### ISSUE THREAD

**Issue by rsclmumbai** [joewalnes/websocketd#326]
Downloaded websocketd on CentOS release 5.4 (Final) - 2.6.18-164.el5.
chmod +x websocketd

Executed as follows:

[root@qwe scripts]# ./websocketd --port=8585
-bash: ./websocketd: cannot execute binary file

[root@qwe scripts]# ./websocketd --port=8585 websocketd-php.php 
-bash: ./websocketd: cannot execute binary file

[root@qwe scripts]# ll websocketd
-rwxr-xr-x 1 root root 7356019 Oct 29 19:42 websocketd

Any ideas what I may be missing?

Thanks

**Comment by asergeyev** [comment]
Where did you donwload it from?  Could you try RPM from https://github.com/joewalnes/websocketd/releases ?

**Comment by rsclmumbai** [comment]
http://websocketd.com/#download  >> https://github.com/joewalnes/websocketd/releases/download/v0.3.0/websocketd-0.3.0-linux_amd64.zip
Unzipped & uploaded to centOS. 
Would that not work?

**Comment by rsclmumbai** [comment]
`[root@qwe scripts]# wget https://github.com/joewalnes/websocketd/releases/download/v0.3.0/websocketd.0.3.0.x86_64.rpm`



```
[root@qwe scripts]# rpm -ivh websocketd.0.3.0.x86_64.rpm 
Preparing...                ########################################### [100%]
	package websocketd-0.3.0-1.x86_64 is intended for a x86_64 architecture
```


```
[root@qwe scripts]# websocketd --port=8585
-bash: websocketd: command not found
```


No joy :(

**Comment by rsclmumbai** [comment]
rpm worked!!
Thanks 👍
