### ISSUE TITLE
Documentation severely lacking

### ISSUE THREAD

**Issue by AELSchauer** [joewalnes/websocketd#327]
Documentation is severely lacking. The examples only show a counter, but when is that ever a legitimate use case? 

I want to start up my wsd program with a variable. How would I do that? I want to read a file on my server. How would I do that? 

The documentation is useless, and googling "websocketd tutorial" provides nothing.

**Comment by wowcut** [comment]
The documentation demonstrates that websocketd just reads from [STDOUT](https://en.wikipedia.org/wiki/Standard_streams#Standard_output_(stdout)) of your program and writes to [STDIN](https://en.wikipedia.org/wiki/Standard_streams#Standard_input_(stdin)) of your program, lilke any command line unix tool. You could write your program however you like and in any language, it is not part of websocketd and you explicitely have **not** to do anything special regarding websocketd - that _is the point of this standard unix method of data exchange_.

Your question makes no sense in this context. It is like asking the people at the post office how to write a letter - they can not tell you, you must write it yourself.

There are many programming tutorials on the internet - also you should read about unix stdin and stdout, e.g. [here](http://www.learnlinux.org.za/courses/build/shell-scripting/ch01s04.html)

If you understood this basics and later will come back to this question - you will have some fun :)

**Comment by asergeyev** [comment]
Please let's not try to say strong words like "no sense" there is always point. Written text is hard to pass all details from one person to many others.  I'm not trying to imply you wanted to start a confrontation, just let's all be softer anyway.

**Comment by asergeyev** [comment]
@AELSchauer I agree, there is not much documentation since we never got to write anything better than "intro". This is very small project, regardless of it having lots of stars. I'll appreciate any help.

Now about your use case. I'm not familiar with WSD... could you explain what your program does and why you want to use websocketd for it?

Counter is usecase that we go with since it could be written in few lines of code, without giving people too long of an explanation.

**Comment by asergeyev** [comment]
I'll close I doubt someone with WSD knowledge would be here to answer... @AELSchauer  feel free to  and re-open with some details
