### ISSUE TITLE
make fails due to go < version 1.7

### ISSUE THREAD

**Issue by pheloniusfriar** [joewalnes/websocketd#328]
Downloaded latest from GitHub on Nov. 3, 2018. Ran `make`. It downloaded "go", but failed on the "get". Output:

```
% make
mkdir -p go-v1.4.linux-amd64/
rm -f go-v1.4.linux-amd64/.done
Downloading and unpacking Go 1.4.linux-amd64 to go-v1.4.linux-amd64/
wget -q -O - http://golang.org/dl/go1.4.linux-amd64.tar.gz | tar xzf - --strip-components=1 -C go-v1.4.linux-amd64/
touch go-v1.4.linux-amd64/.done
chmod +x go
Created ./go wrapper
mkdir -p go-workspace/src/github.com/joewalnes
ln -s ../../../../ go-workspace/src/github.com/joewalnes/websocketd
./go get ./go-workspace/src/github.com/joewalnes/websocketd
package github.com/gorilla/websocket
        imports context: unrecognized import path "context"
package github.com/gorilla/websocket
        imports net/http/httptrace: unrecognized import path "net/http/httptrace"
make: *** [websocketd] Error 1
```
I tried running the `get` command directly and got:
```
% ./go get ./go-workspace/src/github.com/joewalnes/websocketd
package context: unrecognized import path "context"
package net/http/httptrace: unrecognized import path "net/http/httptrace"
```
With some searching, it looks like "context" was added in version 1.7 and the version of "go" installed by `make` is 1.4 ("go version go1.4 linux/amd64" on my system). Just changing the line "GO_VER=1.4" to "GO_VER=1.7" fixed the problem and `make` ran successfully. Fyi, as I looked at golang.org, their latest stable version is 1.11. I tried it again with that version (changed to "GO_VER=1.11"), and `make` ran successfully with that version of "go" as well. I have not tested the websocketd produced with either version of "go" (1.7 or 1.11).

**Comment by pheloniusfriar** [comment]
I tested the websocketd that was built with "GO_VER=1.11" (secure websockets behind Apache 2.4) and it worked like a charm. Just fyi.

**Comment by asergeyev** [comment]
yeah, if you don't plan to modify websocketd code and/or utilize libwebsocketd in your code it's better to just use binaries.
