### ISSUE TITLE
Is there anything we have to know if we want to autostart websocketd correctly with systemd?

### ISSUE THREAD

**Issue by wowcut** [joewalnes/websocketd#329]
It looks like systemd will redirect stdin and stderr to syslog - will this have any negative effect on websocketd? Do we need any special options for systemd to start websocketd on system startup?
It would be great if the author would like to add a system unit file to the wiki, thank you!

**Comment by asergeyev** [comment]
Websocketd's own STDIN is ignored and STDOUT is logging which is correct for systemd.

**Comment by wowcut** [comment]
Thank you very much for your quick reaction! So what would be the answer to my question? I am not a systemd expert but it sounds like it could be "You do not have to do anything special regarding systemd and could use a simple systemd unit file like this following one..." or is it more like "well, websocketd must be handled in a special way, better write your unit files like this:..." ???

I do not understand clearly what systemd does with STDIN and STDOUT of processes that start processes - as there are soooo many different things to explore it would be extremely friendly if you, the developer, would like to copy-pasta a simple systemd unit file that just works well with websocketd, so we, the users, do not have to study systemd architecture details. Also, if any kind of error occurs, it is always good to know that "it is not your self-baked unit file that causes this error" - because I have seen this trouble before with systemd, that is why I really like to get a no-problem-systemd-unit made by the people who understand best how their software relates to it. 

Thank you very much for your attention again!

**Comment by asergeyev** [comment]
I think you're confusing STDIN/STDOUT of program that websocketd manages and STDIN/STDOUT of websocketd itself managed by systemd. Most basic example of unit file would fit.

**Comment by wowcut** [comment]
Got it! Thanks for your patience!
