### ISSUE TITLE
not support cert made by openssl?

### ISSUE THREAD

**Issue by TOBACCOCN** [joewalnes/websocketd#332]
![image](https://user-images.githubusercontent.com/26536218/48900646-e71c6f80-ee8d-11e8-8a1c-ce47ce93b6f9.png)
![image](https://user-images.githubusercontent.com/26536218/48900727-26e35700-ee8e-11e8-9176-a4207ba07cf2.png)
![image](https://user-images.githubusercontent.com/26536218/48900772-4d08f700-ee8e-11e8-8094-ac3d0b54e996.png)
i make cert and key by this way:
![image](https://user-images.githubusercontent.com/26536218/48900872-922d2900-ee8e-11e8-9788-d73abd3a0764.png)

**Comment by asergeyev** [comment]
This is not websocket issue, your browser rejects cert. You need to explicitly trust it first somehow. 
You might try to open websocket's address in browser directly, check browser's warning and follow up to your HTML page again. But it'll not work for all other users, this is why self-signed certs are good for testing only. 

Real certs are free nowadays I just don't know if regulation in certain countries or US trade regulations could prevent users from obtaining them from sites like Letsencrypt.

**Comment by TOBACCOCN** [comment]
OK! Your suggestion should be nice. At first, I'll make sure that my brower does not reject self-signed certs. Secondly, whether that works or not, I will get cert from Letsencrypt and have a try with it. Thank you!
