### ISSUE TITLE
Intercept HTTP Upgrade request

### ISSUE THREAD

**Issue by woky** [joewalnes/websocketd#334]
Is it possible to intercept the HTTP Upgrade and respond with other HTTP status instead of 101? I realize it doesn't align with _do one thing well_ nature of websocketd and I can't even think out how it should work, but it could be that I've just didn't read enough. :-)

Use case: Authentication based on e.g. a query parameter (`https://example.com/?key=foo`) can return 401 if key is invalid instead of directly switching to websocket protocol. If I'm not missing something, currently such errors can be signaled only in custom websocket protocol.

**Comment by asergeyev** [comment]
I think you should not have big issues to fork for such thing. 

We have #141 to idealize about it. So far there is not much clarity but I think you got decent idea to have some sort of --before-upgrade="command"  kind of hook to have... Do you think this would be something that would help you?

**Comment by woky** [comment]
Currently in websocket handler I read the `key` from `QUERY_STRING` and just `exit 1` if it's not valid, so the initiator sees just connection closed. For the sake of better messages for the user, it'd be better to return HTTP status code before upgrade. What you propose sounds very straightforward and I could definitely use it. :-)
