### ISSUE TITLE
Using with screen command shows "Must be connected to a terminal"

### ISSUE THREAD

**Issue by theronic** [joewalnes/websocketd#339]
I'm sure this is a limitation of screen and not websocketd, but can I use websocketd with `screen` to dump serial output over WS?

Running `./websocketd -port 1234 screen /dev/ttyAMA0 115200` throws "Message be connected to a terminal."

I also tried `./websocketd -port 1234 script /dev/null && screen /dev/ttyAMA0 115200`, but then I just see "Script strated, file is /dev/null".

This seems like a common use-case for websocketd, so it would be nice to know if anyone has managed to get it working.

**Comment by arl** [comment]
I'm using https://github.com/yudai/gotty to share `tmux` sessions. I'm sure it also works with `screen` because it binds at the tty level, not stdin/stdout.
