### ISSUE TITLE
Can not support Chinese.

### ISSUE THREAD

**Issue by clouddea** [joewalnes/websocketd#348]
As the caption, that is why I will desert it.

**Comment by leonyu** [comment]
Works fine.

![screenshot_2019-02-13_02-35-23](https://user-images.githubusercontent.com/304902/52694542-092b0880-2f38-11e9-975f-55836771cbe7.png)

**Comment by asergeyev** [comment]
Yeah, websocketd pretty much only would work properly with utf-8 so if there is another encoding it's likely going to be tricky to support since there is no way for shell script to announce encoding it's going to use.... (and env vars and LOCALE are not easiest to agree on)

**Comment by asergeyev** [comment]
Thank you for posting the example, @leonyu

**Comment by clouddea** [comment]
perfet with python3!
@leonyu thank you
![2019-02-14_183412](https://user-images.githubusercontent.com/31328538/52781454-93ce4d80-3087-11e9-990a-2f69caa0b46a.jpg)

**Comment by necan** [comment]
for stdin, you should also reconfigure encoding.
```python
import select
import sys
import io

sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding='utf-8')


def send_message(content):
    print(f'服务端：{content}', end='')


while sys.stdin in select.select([sys.stdin], [], [], 0)[0]:
    line = io.TextIOWrapper(sys.stdin.buffer, encoding='utf-8').readline()
    if line:
        send_message(line)
    else:
        break
```
