### ISSUE TITLE
How do I make my websocketd public - ie accessible on the internet

### ISSUE THREAD

**Issue by McSwan** [joewalnes/websocketd#349]
How do I make my websocketd public - ie accessible on the internet.
I can access it locally eg ws://localhost:8080/

I created an azure virtual machine, put websocketd on it and ran it, but can't connect to except locally.
eg
http://ipaddress:8080/input.html

Also tried on local machine.

**Comment by asergeyev** [comment]
--port 80 or with --ssl and other ssl flags --port 443
