### ISSUE TITLE
stderr, QStandardPaths: XDG_RUNTIME_DIR not set

### ISSUE THREAD

**Issue by WIll-Xu35** [joewalnes/websocketd#354]
Hi all,

I'm new to wenbsocketd and just want to transmit a single message from python script. After going through the tutorial, I simply add print(message), stdout.flush() to my original python code. But things don't go well.

After I executed command: websocketd --port=8080 --staticdir=. python3 test.py
It gives the following error:

![Screenshot from 2019-05-27 09-41-23](https://user-images.githubusercontent.com/40563560/58390367-9fa4b500-8063-11e9-9d2f-8964e8f17507.png)

Any idea what might to wrong and how to make it work?
Many thanks.

**Comment by asergeyev** [comment]
Did you try it with some websocketd example scripts BTW, e.g. counter? I wonder if the result is same or different...

It seem that your python script uses some kinds of QT functionality that would only work when process is running from the console. OR, the python3 wrapper you use might be doing something funky. What OS do you use? Could you post your `python3 --version` here?

**Comment by WIll-Xu35** [comment]
@asergeyev Thank you for your reply. It turned out that I cannot use cv2.imshow() to print some frames along with websocketd. After I commented the cv2.imshow() part, websocketd worked perfectly.
