### ISSUE TITLE
websocketd output miss

### ISSUE THREAD

**Issue by Dustyposa** [joewalnes/websocketd#355]
I didn't get I wanted output by websocketd.
I directly run bellow script, output is:
cmdline: `/usr/local/bin/python3 -ubq ./show.py`
```
this is backend!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
this is a file 0
this is a file 1
this is a file 2
```
But when i  run websocketd, missed some output.
cmdline: `./websocketd --port=8080 python3 -ubq ./show.py`
Output in html:
```
this is a file 0
this is a file 1
this is a file 2
```
Why missed some output?

**Comment by Dustyposa** [comment]
Oh I got it. But how can I know it's time to send msg?
When websocketd catch stdin, but didn't send msg to frontend?
Can websocketd can send a flag to frontend when catch stdin.

**Comment by asergeyev** [comment]
I wonder if you could share your HTML code. IMO things should not be missed. Could you share your HTML code perhaps?

**Comment by asergeyev** [comment]
Any news, @Dustyposa ?

**Comment by Dustyposa** [comment]
@asergeyev Oh,sorry. I had forgot this thing. Now,it's greate for me. Thanks.
