### ISSUE TITLE
WebSocket connections maxing out at 150 

### ISSUE THREAD

**Issue by norandomtechie** [joewalnes/websocketd#356]
I'm developing a simulator that requires connecting back to the server to launch simulation software using a Python script, which is instantiated with websocketd. The simulator works by taking inputs to a simulated device from the user via the webpage, creating a WebSocket back to the server and sending those inputs. Those inputs are received by my simulation software script, passed to the simulation software, which will give real-time outputs (so new outputs get passed back regardless of inputs from the user). Those outputs are sent by my script back to the webpage through the WebSocket.

It works beautifully - up to around 152 concurrent simulations, and then any new simulations will simply not connect. The new WebSocket connections initiated by the JavaScript remain in the CONNECTING state. The page loads, but the simulation never starts because websocketd doesn't seem to be able to accept the 153rd incoming WebSocket. I find it odd that it happens exactly at 152 connections, regardless of if I use Chrome or Firefox.

I understand [from this](https://github.com/joewalnes/websocketd/issues/226) that websocketd isn't production-ready, but it also mentions this: 

> However, the nature of the kind of WebSocket systems I typically deal with tend to have 1000s of concurrent long lived connections to lightweight handlers, which is an ideal fit for websocketd.

The data I transmit back and forth is around 2 KB, with an in-between added transmission delay of 40 ms, so I assume my connections are lightweight. Is there a specific option I have to enable to allow more connections? Open new ports? Spawn a new websocketd when I hit my limit? Or is there something I'm missing?

**Comment by asergeyev** [comment]
Could you explain how you test that? What OS server is running? Is there firewall?

Are clients and server talk all the time or they sit idle after connect?

I have suspicion that connections become idle once some data is exchanged and go has some limits on idle connections that I need to raise.

**Comment by norandomtechie** [comment]
I tested it by writing a script that would open up hundreds of tabs on a browser (tried both Chrome and Firefox), navigating to the page and starting the simulation (therefore opening the websocket). 

Apache serves the site over HTTPS. I didn't want to open a port just for WebSockets, so I installed a proxy module that allows routing WebSocket connections through port 443 on the router to an internal secret port on which websocketd runs. The connection looks something like:

wss://mysimulator.com/wss --> ws://localhost:1234

I haven't set any rules on the firewall, and there's nothing affecting these ports from what I can see.
The idle time depends on what's happening in the simulation. There could be a constant stream of outputs from the server simulation software to the client's webpage, or nothing at all. In my tests, however, I made sure to run a simulation that would constantly receive output data from the server.

> I have suspicion that connections become idle once some data is exchanged and go has some limits on idle connections that I need to raise.

I don't think this is the issue for me. My testing involves constantly receiving data from the server simulation, so it definitely isn't idle. Is there some kind of limit on the number of concurrent connections it can support?

**Comment by norandomtechie** [comment]
I did a test with a Node.js websocket server and I found that the limit was still 150. I realized the issue was with `[Apache's own limit on concurrent connections, which is apparently 150](https://oxpedia.org/wiki/index.php?title=Tune_apache2_for_more_concurrent_connections)`. It looks like the issue isn't with websocketd.
