### ISSUE TITLE
windows amd 64 download

### ISSUE THREAD

**Issue by rexxitall** [joewalnes/websocketd#358]
Hi , 
 windows executables have to have the .EXE suffix.

The wecsockd file lacks this in the zip file. (Please check all windows versions)

please add it manually or tell your make file to rename it accordingly to the windows OS needs.
I am yuite sure that this is not needed under any UX but...

I am also quite sure taht not everybody is that crazy like me and just rename it to see what happens ;)

Best regards
Thomas

**Comment by asergeyev** [comment]
Looks like it's new bug introduced in last build. Thanks for reporting it.

**Comment by got991** [comment]
ok
that amd 64? i'm amd 64

**Comment by asergeyev** [comment]
Could you check new pre-release? 0.4.1 should have EXE files in zips.

**Comment by asergeyev** [comment]
Should be ok in 0.4.1
