### ISSUE TITLE
SIGTERM / SIGINT not supported by windows

### ISSUE THREAD

**Issue by sectokia** [joewalnes/websocketd#362]
When running websocketd on windows, when a client disconnects, I get ERROR "SIGINT unsuccessful to [pid]: not supported by windows" and ERROR "SIGTERM unsuccessful to [pid]: not supported by windows" and the command to execute is never terminated.

Obviously this is a big problem... as instances of the command will just pile up.

Surely I am missing something here? How do you get commands spawned for each client to be killed off?

I have a (poor) work around which is to have the client periodically send data to the command, and the command programmed to terminate itself if it gets no stdin for a while. 

But is there a better way?

**Comment by asergeyev** [comment]
Interesting... You should not see pile up since KILL will eventually take place and it works on Windows... But there is a code that should not send signals that not supported  in first place. So it might be a bug to fix...

**Comment by sectokia** [comment]
Ah yes this is actually a problem with antivirus which was interceptting command and calling it as a child, so websocketd was killing the antivirus instance for the command, and the actual command was just left to run.
I blame mcaffee.

**Comment by asergeyev** [comment]
I'll reopen just to not forget to check this at some point.

**Comment by asergeyev** [comment]
KILL seem to work on windows ok, just takes bit longer to get to it.
