### ISSUE TITLE
No way for a web api client to tell difference between no connection and fork limit exceeded?

### ISSUE THREAD

**Issue by sectokia** [joewalnes/websocketd#366]
When using --maxforks, if the limit is reached, websocketd will return HTTP 429.

This causes browsers to report unexpected code in handshake, causing 1006 as the web API websocket close/error event code. But this is the same code that is returned if websocketd isn't running at all!

Is there anyway that websocketd could return something else which would cause the javascript websocket api to use another return code? This way we would be able to make javascript code that differentiates between no connection to server, and server fork limit from too many clients. At the moment there is no way to do this?

Maybe this is this actually a poor implementation of the websockets by the webapi? Its seems rather strange that they return 1006 code for anything that goes wrong during handshake, and the exact same code if the server isn't even there.... and no connection at all is established.

**Comment by asergeyev** [comment]
Websocket api in browser only starts "properly" work after connection is upgraded. Before that you don't have good context so, yes, 429 rejection would look like any other.

I wonder if you can try to catch an exception and deal differently with its outcome. At least in my simple experiment wrapping everything that deals with websockets in try/catch definitely gives different error on "no connection" vs "429 answer".
