### ISSUE TITLE
docker: the input device is not a TTY

### ISSUE THREAD

**Issue by ValentinBossi** [joewalnes/websocketd#368]
Hi

I'm trying to publish a jshell with websocketd via a docker container.

When I execute `docker run -it openjdk:11-jdk-slim` in a terminal i can use the jshell from the docker container.

When executing `./websocketd --port=8080 docker run -it openjdk:11-jdk-slim` I get the error
> the input device is not a TTY

When executing `./websocketd --port=8080 docker run -t openjdk:11-jdk-slim` (without interactive flag) I get no error and can see (in my browser console where I'm connected to the websocket) the default start output from a starting jshell. Here the problem is that it's not possible to send anything. Actually its not that surprising because if `docker run -t openjdk:11-jdk-slim` is executed, in the terminal it's also not possible to get output after typing `ls`.

How can I achieve to send commands to a docker bash via websocketd? Something like `./websocketd --port=8080 docker run -it openjdk:11-jdk-slim`.

`./websocketd --port=8080 jshell` does work...

Thank you for the help.

**Comment by patrickschur** [comment]
@ValentinBossi To interact with a container you have to keep the option `-i` but remove `-t`. `./websocketd --port 8080 --devconsole docker run -i openjdk:11-jdk-slim`

**Comment by asergeyev** [comment]
--rm would be good to add to `docker run` to avoid piling up used image containers

**Comment by ValentinBossi** [comment]
so great thx!
