### ISSUE TITLE
Hope the server can process client data

### ISSUE THREAD

**Issue by singlelonghair** [joewalnes/websocketd#370]
I would like to know how the server handles the data sent by the client, thank you. Is it possible to do a function of saving it to a local file?

**Comment by asergeyev** [comment]
yes, example is in https://github.com/joewalnes/websocketd/blob/master/examples/bash/chat.sh which writes to file and shares it's context with connected users.

You can do different things using ENV vars  from another example, https://github.com/joewalnes/websocketd/blob/master/examples/bash/dump-env.sh
