### ISSUE TITLE
Execute Nodejs Script command

### ISSUE THREAD

**Issue by WenWenBo** [joewalnes/websocketd#372]
```
websocketd nodejs script.js
```
Wrong message:
```
Unable to locate specified COMMAND 'nodejs' in OS path.
```
Correct usage: 
```
websocketd --port=8080 node xxx.js
```

**Comment by asergeyev** [comment]
If you are on OSX/Linux and likes you can also make script file executable and have shell processing instruction:

```
#!/usr/bin/env node

console.log('Hello world')
```

will work with just `websocketd --port=8080 test.js`
