### ISSUE TITLE
Raw protocol support (for binary messages)

### ISSUE THREAD

**Issue by joewalnes** [joewalnes/websocketd#38]
I propose an option to allow websocketd to be run in "raw mode". In this mode, processes will send/receive message using the WebSocket data framing protocol as defined in RFC6455 (as opposed to newline delimited text).
http://tools.ietf.org/html/rfc6455#section-5

When you'd want this:
- For text messages that contain "\n"
- For binary messages
- For lower level control of ping/pong messages

Of course this adds complexity to programs as they now need to speak to the data framing protocol, which is more complicated than line delimited text, so programs should only use this when they need it.

In raw mode, websocketd will continue to act as a socket server, handle HTTP upgrades, perform WebSocket handshakes and route to the correct process. It is only the actual message framing that apps need to worry about.

**Comment by nichtich** [comment]
How about adding a mode to expect the script to print **filenames** and send these files as binary. The script could just print a list of existing files or use a temporary file in a write-file-print-name-loop. This would be the UNIX way, as far as I understand it.

**Comment by TazeTSchnitzel** [comment]
This would be useful for tunneling existing binary protocols.

For example, @charliesome's site uses [a script piping VNC (via unix socket) to stdio](https://github.com/charliesome/charlie.bz/blob/f5cffdad6590e9ce5c0b1e536d7d6311264ef78c/ws-bin/vnc) and then they have a node.js script to run the script and pipe stdio to websocket. If websocketd supported binary, there'd be no need for that script.

I think the simplest and best approach is to send binary frames whenever you get data. The data you're getting isn't segmented, the client can split it up if it needs to.

**Comment by asergeyev** [comment]
I wonder if we could just assume that  we could frame as much data as  received in certain new time interval (say 100ms by default) and ship it...   Would that work for folks who want binary?

**Comment by TazeTSchnitzel** [comment]
You don't even need to do that. Just send it as you get it.

**Comment by asergeyev** [comment]
I guess I have irrational fear of someone feeding one byte at a time :) Not sure how many programs would actually create that hazard though after you pointed it out again... Thanks.

**Comment by TazeTSchnitzel** [comment]
I think OS buffering means you wouldn't end up with it so small.

**Comment by joewalnes** [comment]
I gotta say, I really like this idea of sending as it's received. So simple and elegant.

The OS (and most lang specific IO libs) have great support for buffering and flush().

In the case of sending a single byte at a time, a user would typically have to explicitly disable buffering for this. And if they really want to do this, so be it (eg lower latency single byte command).

**Comment by joewalnes** [comment]
One question is how does websocketd know whether to be in flush or newline mode? I propose we use a websocket sub-protocol.

**Comment by asergeyev** [comment]
Imo this would add another flag anyway... maybe should be just  --binary for once?

**Comment by TazeTSchnitzel** [comment]
Just being `--binary` is simple and intuitive. If it's off, one text frame per line. if it's on, binary frames for buffered data.

You could also add `--text` to be explicit about the default.

By the way, sending binary frames with whatever data you get, as you received it, is how some other WebSocket proxies already work. My [Minecraft client](https://github.com/TazeTSchnitzel/manic.io) expects that handling of TCP to WebSocket proxying, for example.

**Comment by asergeyev** [comment]
Will get to it soon. Apparently it's a bit more involving than I imagined since ProcessEndpoint needs conversion from strings to bytes and eliminating one of the buffers. Then I need to verify it works stable for strings that way.

**Comment by sinm** [comment]
IMHO. It sounds dangerous to me. It's far more robust to re-serialize binary to text using current implementation. Or implement completely separate "ProcessEndpoint" to ensure there are no side-effects in the working one.

**Comment by TazeTSchnitzel** [comment]
Why would you need to convert between strings and bytes? For binary, you should just be passing bytes around everywhere.

**Comment by asergeyev** [comment]
In console.... Binary messages from websocket are shown as Blob objects... Anyone has idea how best to display them? Decode to ASCII with escapes or show as hex or doing something else?

**Comment by TazeTSchnitzel** [comment]
Hex sounds reasonable.

**Comment by asergeyev** [comment]
Well.. for now I decided to go with JSON.stringify... Code is in my branch but I'll likely re-do couple things before pull request.

**Comment by asergeyev** [comment]
test I found useful so far is running:

   websocketd  --devconsole --port 8080 --binary --devconsole stdbuf -i0 -o0 cat

but I'd like a suggestion what could be good example to write for demonstrating --binary use?

**Comment by asergeyev** [comment]
BTW, right now fast paced writes from process are not properly passed to user, will be working on that...

**Comment by TazeTSchnitzel** [comment]
You could have a server that streams images, and a webpage that displays them (`<img>` with `data:` or `blob:`), perhaps?

**Comment by njamescouk** [comment]
I have a program which reads stdin up to EOF, parses input and writes to stdout. this proposal would let me use my program with websocketd?

**Comment by Zucce05** [comment]
Hi, I'm pretty nub at all of this, but I'm trying to use websocketd for a project.
I was able to get it working with the binary flag on an Ubuntu test machine, but when I use the arm compiled version, I can't get the binary flag to work.
The error I'm getting is:
flag provided but not defined: -binary
Usage:
  Export a single executable program a WebSocket server:
    websocketd [options] COMMAND [command args]

  Or, export an entire directory of executables as WebSocket endpoints:
    websocketd [options] --dir=SOMEDIR

  Or, show extended help message using:
    websocketd --help 

I know it says -binary is undefined, but I've tried it with both --binary and -binary, and it gives that exact same message no matter which flag predicate I'm attempting.
Any ideas? What other details should I share?

**Comment by asergeyev** [comment]
How about websocketd --version?  I think you need more recent one to get --binary to work.

**Comment by thirdwheel** [comment]
Has anybody gotten this to work with noVNC?  This is what I get when I try:

```
C:\Apps\websocketd>websocketd.exe --binary --port=5801 plink -P 5900 VNC-PC
Wed, 16 Aug 2017 14:09:48 +1000 | INFO   | server     |  | Serving using application   : C:\Program Files\PuTTY\\plink.exe -P 5900 VNC-PC 
Wed, 16 Aug 2017 14:09:48 +1000 | INFO   | server     |  | Starting WebSocket server   : ws://THIS-PC:5801/
Wed, 16 Aug 2017 14:10:07 +1000 | ACCESS | session    | url:'http://jhe-dt36:5801/websockify' id:'1502856607419485800' remote:'10.0.0.67' command:'C:\Program Files\PuTTY\\plink.exe' origin:'http://novnc.com' | CONNECT
Wed, 16 Aug 2017 14:10:07 +1000 | ERROR  | stderr     | url:'http://jhe-dt36:5801/websockify' id:'1502856607419485800' remote:'10.0.0.67' command:'C:\Program Files\PuTTY\\plink.exe' origin:'http://novnc.com' pid:'17576' | FATAL ERROR: Network error: Connection reset by peer
Wed, 16 Aug 2017 14:10:07 +1000 | ACCESS | session    | url:'http://jhe-dt36:5801/websockify' id:'1502856607419485800' remote:'10.0.0.67' command:'C:\Program Files\PuTTY\\plink.exe' origin:'http://novnc.com' pid:'17576' | DISCONNECT
```

**Comment by asergeyev** [comment]
When process is run under websocketd with `--binary` any flush of output buffer process does would be considered "new message". If you run standard text output program those indeed would only flush when you print `\n` but it's not the case if your program using truly binary output.

**Comment by lafkpages** [comment]
But what about binary input? My script is trying to decode binary data that may contain `\n`, causing the original message to be read as two different messages by my program. I agree with @lukaaash, the way he described would allow binary messages to be read even when they contain newlines.

**Comment by asergeyev** [comment]
`\n` inside of the read would not do anything to frames websocketd forms when process run under --binary the only limit is not to go over 10MiB (messages will split) as described in https://github.com/joewalnes/websocketd/blob/master/libwebsocketd/process_endpoint.go#L125-L138

**Comment by lafkpages** [comment]
> `\n` inside of the read would not do anything to frames websocketd forms when process run under --binary

If the client sends `hel\nlo`, a simple Bash script that reads line by line has no way to tell if it's two different messages or one message with a line break in it.

**Comment by lafkpages** [comment]
That's why I think a protocol that specifies message size before the message instead of using delimiters would be a better option, but of course this should be opt-in for backwards-compatibility. Maybe with a CLI flag?

**Comment by lafkpages** [comment]
Or another possible solution would be that for each message received by websocketd, it encodes it in base64 and then sends it to the spawned script, with a delimiter of a newline. websocketd could also receive messages from the script in base64. Then there'd be no problems with binary data (Bash removes null bytes) or messages containing newlines.
