### ISSUE TITLE
CGI scripts on windows

### ISSUE THREAD

**Issue by sectokia** [joewalnes/websocketd#384]
How do you get CGI scripts to work on windows?

For example if --cgidir=foo and you have a foo\bar.pl and in your browser go to http://host/bar.pl then websocketd says "%1 is not a valid win32 application".

How to get websocketd to use the shebang in the perl script first line to run perl on the script? Or can cgi only run actual executables?

**Comment by asergeyev** [comment]
https://stackoverflow.com/questions/4727480/how-do-i-make-my-perl-scripts-act-like-normal-programs-on-windows

I wonder if this helps to get to what you want.

**Comment by asergeyev** [comment]
But overall it seems quite complex so maybe you would have bat or cmd script instead which would run perl interpreter for proper script?
