### ISSUE TITLE
No output from PHP

### ISSUE THREAD

**Issue by lilltiger** [joewalnes/websocketd#388]
I updated my server and suddenly websocketd does not provide any output from PHP-scripts (tried the example ones as well), it connects but no output at all. The bash-script works just fine.

PHP 7.4.6 (cli) (built: May 12 2020 15:48:23) ( NTS )

Is there an issue with websocketd and this PHP version?

I know that it works just fine with:
PHP 7.4.2 (cli) (built: Jan 21 2020 18:16:58) ( NTS )

**Comment by wutongshenyuan** [comment]
if you run the demo on windows , you should use PHP_ EOL replaces the "\n" in demo
