### ISSUE TITLE
How i can close connection from async function? (bash)

### ISSUE THREAD

**Issue by agent188** [joewalnes/websocketd#389]
Kill proccess cant close connection.
`kill -9 $$`

**Comment by asergeyev** [comment]
I'm not sure what the purpose, looks bit extreme. You can just exit your current script and websocketd will terminate the connection.

**Comment by agent188** [comment]
exit cant stop script, my script have async function.
`AsyncFunc &`

**Comment by agent188** [comment]
and i want stop script inside async func

**Comment by asergeyev** [comment]
If you post the example of script later, we can re-open to look into that but for now I don't see anyone providing you good solution so I'll close.
