### ISSUE TITLE
Piping data into the stdin of the websocket instance, Possible?

### ISSUE THREAD

**Issue by iambenkay** [joewalnes/websocketd#390]
So, I want to be able to access logs of my application in realtime and I am confused if websocketd can deliver on this.

The goal is being able to channel data from stdout of my application to stdin of the websocket instance. 
So connected clients can receive the log updates in realtime.

**Comment by RichardTMiles** [comment]
Look into forks, named pipes, or implement a socket with the executable you'll be passing to Websocketd

**Comment by asergeyev** [comment]
Ideally you just write to logfile and run websocketd with `tail -f /path/to/that/log`
