### ISSUE TITLE
Help with passing parameters to bash

### ISSUE THREAD

**Issue by linuxwizard** [joewalnes/websocketd#391]
I am trying to pass and read the parameters from websocketd to bash. Can anyone give me a sample on how it works. new to websockets

**Comment by asergeyev** [comment]
Do you need params passed same on each start or different depending on what sent from browser?

From the browser you could not do actual bash params. You have Environment variables and input. You could use them to construct new params and exec subsequent process with them. It's just all more complex that way.

If you could re-phrase, describing what you tried and what you could not achieve, it would be easier to provide help.
