### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [joewalnes/websocketd#392]
👋  it looks like been a while since last release (released on 2017), is there any plan to do a new formal release (even for the most recent release, it has been two years). Thanks! 

---

relates to https://github.com/Homebrew/homebrew-core/pull/69320

**Comment by asergeyev** [comment]
Ok, In progress.
0.4.1 should be working I just need to make sure things seem usable. I intend to remove pre-release mark it in next 3-4 days.

**Comment by chenrui333** [comment]
Sounds good, thanks!

**Comment by chenrui333** [comment]
I guess I probably have to wait for another 3-4 days, since the pre-release tag would fail the homebrew PR  (our audit process)

**Comment by asergeyev** [comment]
not sure what you mean really; what can I do to make your life easier besides finishing that release check?

**Comment by chenrui333** [comment]
Mark 4.0.1 as `latest release` would be sufficient for me. Thanks!

**Comment by asergeyev** [comment]
Yeah, hopefully tomorrow

**Comment by chenrui333** [comment]
no worries, take your time. :)

**Comment by asergeyev** [comment]
Ok, updated

**Comment by asergeyev** [comment]
I'll close, feel free to ping back on it.
