### ISSUE TITLE
std::stoi Not Working

### ISSUE THREAD

**Issue by Luke3924** [joewalnes/websocketd#394]
Hello, 

I just started using Websocketd today and I ran into an issue. It appears that, for some reason, if I use std::stoi, that value will always be zero. I have run the code without Websocketd and it works properly so I'm assuming that its something to do with Websocketd. If you have a solution to this problem, please let me know.

Thanks,

**Comment by mattgodbolt** [comment]
This seems very unlikely: can you post a code fragment? What are you passing to `std::stoi` ?

**Comment by Luke3924** [comment]
Sorry I just left work for the day. I’ll send the actual code when I get in tomorrow. Off the top of my head though, I’m reading a CSV file and using std::stoi to store the data as an integer. So something like this is what I 
input:
1234,10,0.0625

And my output is:
Linenumber=1234
Status=10
Duration=0.0625

That’s what the original code does before Websocketd. Like I said, I will post the code fragment when I get back to work tomorrow morning.

**Comment by mattgodbolt** [comment]
My best guess is there's some undefined behaviour in your code that just happens to show up when invoked by Websocketd: I'll try to help if I can if you can post a little more code tomorrow :)

**Comment by Luke3924** [comment]
Ok, thank you! Any help would be greatly appreciated! Here is the part of the code where I think the issue is coming from:
`ifstream myfile;
        myfile.open ("Data/qc1tempdata.csv");

        if(getline(myfile, tempnum, ','))
        {
            getline(myfile, tempnum, ',');
            linenum = std::stoi(tempnum);
            std::cout<<linenum<<"\n";
        }
        
        myfile.close();`
This code has no issues when I run it normally (command: /var/www/html/./LiveData) but when I run it with Websocketd (command: ./websocketd --port=10011 --devconsole /var/www/html/./LiveData) I don't get an output. When I looked at the dev console it had no messages.
![image](https://user-images.githubusercontent.com/65932233/106140578-f322ac80-613c-11eb-886a-adc7b814489b.png)

P.S. sorry if the image doesn't upload. I haven't really used github much so I have no idea if it will send. Its just a screenshot of the dev console.

**Comment by Luke3924** [comment]
I solved the Issue,

The problem was when I run the program normally it can just go to a subfolder inside the programs directory "Data/qc1tempdata.csv" but with Websocketd it needs to be expanded fully like this "/var/www/html/Data/qc1tempdata.csv"

**Comment by mattgodbolt** [comment]
Great stuff! Sounds like you need to check you opened `myfile` and report an error if not. C++ file handling is notoriously quiet on errors, unless you check on each call, or set the `ios::failbit` flag. Good luck; and congrats on working out the puzzle! :)
