### ISSUE TITLE
Exec all the scripts unbuffered

### ISSUE THREAD

**Issue by nikhildevshatwar** [joewalnes/websocketd#400]
When launching a C program which prints the data periodically, by default the stdout is cached
This causes websocketd to send the data in big chunks and loses the realtime ness of the data

This can be worked around if the program is called prefixed with unbuffer
I am requesting an option where the scripts are launched with unbuffered / line buffered stdout.
This way, we can pass the data from a program immediately.

**Comment by asergeyev** [comment]
I don't think it's possible to control from websocketd side how program behaves. No POSIX standard for executing child process unbuffered that I know of. 

The `unbuffer` program is not available in many operating systems by default.  As developers we leave choice to use `unbuffer` or other tricks to the administrator of websocketd.

**Comment by EvanCarroll** [comment]
You're misunderstanding how `unbuffer` works, it disables pipe buffering by redirecting through pseudo terminals,

> unbuffer connects to long_running_command via a pseudoterminal (pty), which makes the system treat it as an interactive process, therefore not using the 4-kiB buffering in the pipeline that is the likely cause of the delay.

If you have no pipe buffer or shell, you'll gain nothing.
