### ISSUE TITLE
Feature Request: exit codes on cmd

### ISSUE THREAD

**Issue by EvanCarroll** [joewalnes/websocketd#404]
It would be great if we got a message that provided the error/exit code that the program returned with. I would think some form of log-level would record this.

This is a duplicate of the request at https://github.com/vi/websocat/issues/113 which also (afaik) doesn't support this functionality.

**Comment by asergeyev** [comment]
This is hard. You'd think it's easy but normally program is not terminated at all and connection is broken from browser. That makes websocketd terminate the program.

What you suggest is doable but only for a program that exited. And it'll be only doable on POSIX systems, not on windows and we want to keep cross-platform compatibility here...

Why not to use the wrapper? I think lot of what you're asking today comes to composing your code that websocketd will monitor and proxy. E.g. this ask is possible to solve with:

```
bash -c 'some-program; echo exit code was $?'
```

**Comment by EvanCarroll** [comment]
@asergeyev out of necessity, we could create a wrapper. but you're talking about the bare minimum functionality here.

* STDIN, STDOUT, STDERR
* Exit Codes
* Environmental Variables.

If you can't cover those three things you're going to force everyone into using this tool with a wrapper.

And it's not like this isn't solved problem... If I problem terminates because of STDIN the programs gets the exit code sent to set a bitshifted return value with the return code and signal. The return code will be unset. And the signal will be set.

**Comment by asergeyev** [comment]
> you're going to force everyone into using this tool with a wrapper

I don't think wrappers are bad thing here :) but I'm ok with more users joining you on exit codes. There is a way to pass them in websocket close frame but that requires decent rework of connection termination. 

I'd like to repeat that websocketd more often used for long-living programs. They never exit and rather terminated by websocketd when browser disconnects.

But I wonder what people say here. Would that feature be lifechanging to avoid wrapper for exit code peeking?
