### ISSUE TITLE
Document request: clean/code/reason in dev console

### ISSUE THREAD

**Issue by EvanCarroll** [joewalnes/websocketd#405]
In `console.go` and the dev console I see,

* `clean`
* `reason`

However, neither of these are explained in the docs or filled out, and they never change. What do they do?

> appendMessage('onclose', '[Clean: ' + ev.wasClean + ', Code: ' + ev.code + ', Reason: ' + (ev.reason \|\| 'none') + ']');

**Comment by asergeyev** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent :)

**Comment by asergeyev** [comment]
I closed due to "off-topic" issue...  we try to focus on server part and not a client side.

**Comment by EvanCarroll** [comment]
I'm not sure that addresses the problem. I'm getting code 1006, and clean: false but no reason. My log reads,

```text
Tue, 30 Mar 2021 20:42:28 -0500 | DEBUG  | process    | url:'http://localhost:8080/' id:'1617154948254731874' remote:'::1' command:'/usr/bin/perl' origin:'http://localhost:8080' pid:'53857' | Process STDOUT closed
Tue, 30 Mar 2021 20:42:28 -0500 | TRACE  | websocket  | url:'http://localhost:8080/' id:'1617154948254731874' remote:'::1' command:'/usr/bin/perl' origin:'http://localhost:8080' pid:'53857' | Terminated websocket connection
Tue, 30 Mar 2021 20:42:28 -0500 | DEBUG  | process    | url:'http://localhost:8080/' id:'1617154948254731874' remote:'::1' command:'/usr/bin/perl' origin:'http://localhost:8080' pid:'53857' | Process STDERR closed
Tue, 30 Mar 2021 20:42:28 -0500 | DEBUG  | process    | url:'http://localhost:8080/' id:'1617154948254731874' remote:'::1' command:'/usr/bin/perl' origin:'http://localhost:8080' pid:'53857' | Process 53857 terminated after stdin was closed
```

I'm invoking with,

```
./websocketd --loglevel=debug --port 8080 --devconsole >log.err -- perl -E'say 42; exit 0'
```

And If I run this outside of websocketd, I get return code 0,

```sh
❯ perl -E'say 42; exit 0'
42
❯ echo $?
0
```

**Comment by asergeyev** [comment]
Websocket protocol (not our program) is very specific about those codes. There is no control from server over the values. 

https://tools.ietf.org/html/rfc6455#section-7.4.1

I guess we can send specific code that would be possible to translate to 0-255 code POSIX progams emit using something like:
https://github.com/gorilla/websocket/blob/c3dd95aea9779669bb3daafbd84ee0530c8ce1c1/conn_test.go#L362

But it'll be lot of reworking like I mention in #404 
You are assuming programs under websocketd are exiting and it's not the case normally. Most people use it to `tail -f` or similar never-ending programs. 

I'm willing to hear you out in #404 but right now it's only your voice and there are thousands of users who I'd like to join discussion if they care about this stuff.
