### ISSUE TITLE
No output from PHP

### ISSUE THREAD

**Issue by mrsnut** [joewalnes/websocketd#406]
So basically I need to proxy some websocket information with logic in between. Im currently testing through Redis but cant get a output in websocketd while I do if I simply use `php listener.php`
I do get output with the example sh and php files but I'm unsure what im doing wrong

```
#!/usr/bin/php
<?php
require(__DIR__ . "/../vendor/autoload.php");
date_default_timezone_set('Europe/Amsterdam');

$client = new Predis\Client([
    'scheme' => 'tcp',
    'host' => '127.0.0.1',
    'port' => 6379,
    'database' => 0,
    'read_write_timeout' => 0
]);

$adapter = new \Superbalist\PubSub\Redis\RedisPubSubAdapter($client);

$adapter->subscribe('myChannel', function ($message) {
	fwrite(STDOUT, $message);
});

?>
```

Is there anything im doing wrong?

**Comment by RichardTMiles** [comment]
Are you sure the $adapter is executing fwrite? You should log to a file to make sure. You're not checking the return of fwrite and in some env's STDOUT might not be a const set. You may need to open it manually (google it). You should just use print or echo to write to stdout. Check out https://github.com/RichardTMiles/PHP-Websockets for a pure php solution.

**Comment by RichardTMiles** [comment]
Also I'm not sure what you mean by proxy information.. information from Predis to stdout? 

You might also try appending a PHP_EOL to the end of any print stmt

**Comment by ctn-malone** [comment]
Like @RichardTMiles said, you're probably just missing a `\n` at the end of the message (and maybe a call to `fflush`, although I doubt it)

```
fwrite(STDOUT, "$message\n");
// shouldn't be needed
fflush(STDOUT);
```
