### ISSUE TITLE
Open a discussion board? 

### ISSUE THREAD

**Issue by RichardTMiles** [joewalnes/websocketd#407]
Many issues on this repo are really just questions that are not actually issues with Websocketd.
It may be time to open [a discussion board](https://docs.github.com/en/discussions). As I understand this is a relatively new thing for GitHub repos. 

When I see questions regarding PHP or C in websocketd I usually check it out. In PHP websocketd is the best way to use ws in windows systems as forking is currently not available in PHP-WIN OS. While I don't use it on my prod anymore, since I wrote the ws protocol in php for more usability regarding OS level ops. I use websocketd as a flaggable option still and will continue to do so with support to my users. I've added a bit of Doc here in the Wiki as well for PHP and C. While learning in college I found this to be an amazing stepping stone for my personal development. 

I hope to continue helping the community as long as this repo remains active. 

Thanks for everything :)

**Comment by asergeyev** [comment]
@joewalnes might be needed to create one if he feels like it.  

As a "maintainer" I personally have not found enough time to support this project better than fixing minor things lately and answering few questions each month...  I wish more people would participate answering to issues...  All above makes me think discussion board could be enthusiastic for a while but get very quiet eventually.
