### ISSUE TITLE
WebSocket server show error codes 

### ISSUE THREAD

**Issue by sytpb** [joewalnes/websocketd#410]
OS :windows 

install and files : 
![image](https://user-images.githubusercontent.com/12178686/126258815-72bcd014-0448-4790-bdc6-6054efa90bb4.png)

server:
![image](https://user-images.githubusercontent.com/12178686/126258689-d78364b2-087d-4862-9095-f00b755b8a3d.png)

client:
![image](https://user-images.githubusercontent.com/12178686/126258725-4097c0b5-cc5a-4770-83b5-15b452162d9e.png)

client code from git providing . 
```
<!DOCTYPE html>
<pre id="log"></pre>
<script>
  // helper function: log message to screen
  function log(msg) {
    document.getElementById('log').textContent += msg + '\n';
  }

  // setup websocket with callbacks
  var ws = new WebSocket('ws://localhost:8080/count.cmd');
  ws.onopen = function() {
    log('CONNECT');
  };
  ws.onclose = function() {
    log('DISCONNECT');
  };
  ws.onmessage = function(event) {
    log('MESSAGE: ' + event.data);
  };
</script>

```
where is wrong from this ? 

I found all tutorial  is about Linux ,  is there a windows example ?   thanks  a lot .

**Comment by asergeyev** [comment]
Is running `./count.cmd` possible on that machine? Websocketd does not do anything extremely clever, just executes the specified program
