### ISSUE TITLE
help make it work

### ISSUE THREAD

**Issue by Barabba11** [joewalnes/websocketd#411]
Hi! Sorry for opening an issue to ask this but I can't figure out how to make it work. My goal is to run a .bat file on the server side, I've placed websocked.exe on c:/ I've created a bat to launch it with proper paramenters 
websocketd --address 192.168.24.2 --port 6000 --dir=c:\
I've created next a simple bat file to execute. Websocket is running and port 6000 is opened, now I've created an html file containing: 
```
<!DOCTYPE html>
<pre id="log"></pre>
<script>
  // helper function: log message to screen
  function log(msg) {
    document.getElementById('log').textContent += msg + '\n';
  }

  // setup websocket with callbacks
  var ws = new WebSocket('ws://192.168.24.2:6000/');
  ws.onopen = function() {
    log('CONNECT');
  };
  ws.onclose = function() {
    log('DISCONNECT');
  };
  ws.onmessage = function(event) {
    log('MESSAGE: ' + event.data);
  };
</script>
```

I've specified the IP of server, same address with I executed websocketd. I put the file in the http server folder, I open the file with browser, it wrote disconnected, nothing is sent on port 6000. From your code I don't understand how it works, there is no call to the script, just `<pre id="log"></pre>` which I don't know what it means. No external libraries are invoked so you suppose the browser already knows what it should do. I don't see where to specify the command to execute (the bat file).
Thank you a lot to clarify me

**Comment by asergeyev** [comment]
This assumes that client that connects to webserver will be able to access 192.168.24.2 on port 6000 (which means access to private network) and that machine that carries IP 192.168.24.2 is running websocketd (or other something) lisstening on port 6000.

Lots of things could be in the way. You probably could check:

* correctness of the IP and that you only want to use this via your local network
* firewall that might prohibit connections to port 6000 on 192.168.24.2
* error log of the websocketd
* error log of the browser (eg. console of Chrome in web devtools panel)
