### ISSUE TITLE
Websocketd likely needs some resource limits in future

### ISSUE THREAD

**Issue by asergeyev** [joewalnes/websocketd#46]
To prevent forkbombing the server it would be interesting to discuss ability to limit possible amount of connections that server should sustain. After that new connections should be dropped.  

Also, for whom it might matter, might prefer to set timeouts on longest living websockets.

I don't know websocket golib well to know if some protection is already  there.

**Comment by silverkorn** [comment]
I've searched for how to limit connections and I finally found it in this issue via the linked commits information.

To avoid other people searching for this information, could you add the `--maxforks` option usage in the `help.go`?

Thanks!

**Comment by asergeyev** [comment]
good point

**Comment by silverkorn** [comment]
#186 was a duplicated request...
You can close this one.

**Comment by asergeyev** [comment]
Ah, right help was added after #186! Thanks
