### ISSUE TITLE
Is there a more convenient way to install this package?

### ISSUE THREAD

**Issue by fanchangyong** [joewalnes/websocketd#77]
Such as brew on OS X?
It's annoying to directly download the executable instead of using a package manager.

**Comment by LinusU** [comment]
Having this in `brew` would be awesome. I've written a few formulas and could certainly help with that part.

Anyone up for writing a manpage?

**Comment by asergeyev** [comment]
There is a man page, see https://github.com/joewalnes/websocketd/blob/master/release/websocketd.man

**Comment by LinusU** [comment]
@asergeyev Thanks for pointing that out

I just submitted a formula to the brew team. As soon as it's accepted, one should be able to install `websocketd` in one simple command. :beers: 

```sh
brew install websocketd
```

**Comment by keitayabu** [comment]
I am all lady  cheacked but I din"t under stand ....?

**Comment by garthk** [comment]
Looks like @LinusU's effort for `brew`[flamed out in June](https://github.com/Homebrew/homebrew/pull/37030).

**Comment by joewalnes** [comment]
I would welcome any contributors who can create builds for downstream packaging tools and take ownership of these in the long run. If anyone's looking for a way to get involved in an open source project, here's a great opportunity ;)

**Comment by bentranter** [comment]
I'm going to take a stab at writing a `brew` formula over the next few days. [Hugo](https://github.com/spf13/hugo) does it, so websocketd should be able to too, right?! :smile:

**Comment by bentranter** [comment]
Update: I have this `brew install`ing successfully on my local machine, but I still need to add the man page, (maybe) bash autocompletion, and then submit to the brew team. Progress though!

**Comment by joewalnes** [comment]
Very cool!

Can you commit to being a long term maintainer of this package? That would be super awesome!

**Comment by bentranter** [comment]
Yeah, definitely!

**Comment by bentranter** [comment]
**Update**: With the help of the Homebrew team, I've finally got this to pass their CI. Hopefully that means my websocketd formula will be merged into master very soon.

**Comment by LinusU** [comment]
Nice, good job @bentranter!

**Comment by bentranter** [comment]
Thanks @LinusU! Just saw that the websocketd formula has been merged (in https://github.com/Homebrew/homebrew/commit/bd1cfc82fd68b436385b26a2646c1b70c0778a07), so it's now possible to `brew install websocketd`. I'll continue updating the formula as releases occur.

**Comment by asergeyev** [comment]
Great news, thanks! Feel free to put PR for changing list of instructions in README and adding steps to install on Mac with homebrew.

**Comment by asergeyev** [comment]
Question though... Anything needs to be done to that formula if new version of websocketd will be released?

**Comment by bentranter** [comment]
I think just the URL for the release and the SHA need to be changed, the rest of the formula should be the same. If a new dependency is added though, a new `go_resource` would need to be added too.

**Comment by asergeyev** [comment]
Awesome, thanks for help. Closing this issue now.
