### ISSUE TITLE
Process output not broadcast to all clients

### ISSUE THREAD

**Issue by gima** [joewalnes/websocketd#95]
If multiple websocket clients connect to the websocketd at the same time, the output of the process is sent interleaved to each websocket client.

Rather it would be more useful to have the output *broadcast* to every client, as the whole purpose of this project seems to be to make **one** process's stdio accessible through websocket.

**Edit:**
Ah, I've understood the code a bit more. So it seems that for each websocket connection, a process is spawned. My feature request would then become this:
Enable the websocketd to spawn only one process and connect each websocket to it's stdio.

**Comment by agalazis** [comment]
hey people why not socketdBro ts just a proof of cpncept for now( only raspbian setup for my raspbery project) but you can provide similar or even better implementations using AMQ(fanout) +websocketd

**Comment by agalazis** [comment]
i hope I ll find some time in the near future to do a proper release

**Comment by joewalnes** [comment]
Closing this issue as I there's nothing actionable.
