### ISSUE TITLE
Update PHP example starting tag

### ISSUE THREAD

**Issue by jasonhinkle** [joewalnes/websocketd#97]
It might help to start the PHP example with `<?php` instead of the shorthand `<?` since some system defaults don't recognize the shorthand syntax anymore - which causes the server to simply output all of the source code instead of counting to 10.  It took me a few minutes of scratching my head to figure that out so it might save others the same grief.  Thanks!

**Comment by asergeyev** [comment]
Sorry, what file do you see that has "<?" in it? (examples/php all look ok to me)

**Comment by jasonhinkle** [comment]
Oh sorry, it's on this page http://websocketd.com/ under "10 second tutorial"

**Comment by asergeyev** [comment]
Fixed, thanks!
