### ISSUE TITLE
Python example does not work on OSX

### ISSUE THREAD

**Issue by mbrochh** [joewalnes/websocketd#98]
I tried the 64 bit and 32 bit binaries.

When I run `./server.py` I can see the countdown in my console. When I run `websocketd --port=8080 ./server.py` and then browse to `localhost:8080/index.html` the browser just hangs for 10 seconds and then I can see the number 10 (or I can see ten lines of console output at once).

When I try the bash example, it works in realtime as advertised. What am I doing wrong? Why is the stdout from my Python script not sent through the websocket immediately when it happens but all at once at the end of the script.

At first I thought that `print` does not append a newline character at the end so I added one manually, but that doesn't seem to be the issue because then the output looks like this:

```
1

2

3
```

So clearly, newlines are added by Python's print per default.

Any ideas?

**Comment by rossjones** [comment]
Probably buffering.

Do you have 

```python
   sys.stdout.flush() 
```

in your code?  Otherwise it'll buffer.  The other alternative, is to turn off buffering in your code by reopening stdout (may be py2 only).

```python
    sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
```

**Comment by joewalnes** [comment]
Also you can set the environment variable PYTHONUNBUFFERED=1 before starting websocketd. This disables python's builtin output buffering.
