### ISSUE TITLE
No Wiki Footbar

### ISSUE THREAD

**Issue by popey456963** [joewalnes/websocketd#99]
Can a repository member create a footer for the wiki.

**Comment by joewalnes** [comment]
What would it contain?

**Comment by popey456963** [comment]
"The websocketd user guide is a publicly editable wiki. Please contribute!"

It would probably look better there.

Also, footers generally look awesome.

**Comment by joewalnes** [comment]
Done. Don't really see the benefit, but then I don't have a strong opposition either.
